### ISSUE TITLE
Web > Job Seeker > Job feed 

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1015]
Add search in job feed

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/415a4512-81f5-4c69-8294-b5148aef4714)
The page is crashed while searching from the job feed.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/e75a82be-2ca1-4199-8d27-feccd9865c1e)
Done
