### ISSUE TITLE
Web > Jobseeker > Job feed > Functional > API

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1017]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/0434ac71-2651-4061-afe9-85a7909dad9d)
Data is not reflecting from Backend.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/836735f1-6017-4c3d-8e2b-8de40fede6bc)
Done
