### ISSUE TITLE
Web > Jobseeker > Jobfeed > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1018]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/42cc879a-4e7b-4958-a5af-ab3d8dc889bc)
UI is not proper for the salary filter. Kindly make this structured.

**Comment by vinayak-vayuz** [comment]
<img width="223" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/343d4bfd-73ef-4ef2-b4b1-a02715b99eb3">
Done

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/545f12c2-d9ab-4f79-b1bb-f8b8f3ae72c6)
Done

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/5eeb3797-d94d-4289-8776-08d0d46caa6f)
Inputbox is not visible clearly from the first view, minimum maximum spelling should be clear for the user .

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/53004f02-1c9a-4b0d-afdb-97eb644c72ca)
Done
