### ISSUE TITLE
Institute | Web | Application management  

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1023]
add clear filter button

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/aca56e14-19e0-49e2-aaa3-3d063c29dc87)
after clicking on this clear filter button the page is refreshing... fix this issue.. and after clicking on the clear filter button in the URL ?application_status= is reflecting.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/d01ed025-ccf4-4551-8da9-c7f8ad1e2745)
Done
