### ISSUE TITLE
Web > Job seeker > My Resume > dark mode

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1034]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/edf54f31-827e-4564-836d-521029e78f05)
Fix the issue

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/11b7f98a-601e-4c9d-a77a-da3c4c5b95f8">
Done
