### ISSUE TITLE
Web > Institute > draft course 

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1036]
Set the three dots over the draft card because they are not visible

**Comment by vinayak-vayuz** [comment]
<img width="216" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/393b049d-0fd1-4ef8-91ed-71b2fcfc829e">
I have increased its size now its visible, looking ugly outside the cover Image
