### ISSUE TITLE
Web | jobseeker | My resume 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1043]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/44d477b0-5627-4d1f-9ab4-18c5fec0b160)
fix this ui when click image then show this image.

**Comment by vinayak-vayuz** [comment]
<img width="958" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/edf3ab15-29f4-4fa6-8cdf-407f18b0a49a">
Done
