### ISSUE TITLE
Employer/Post job/ See comment below 

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1069]
The Salary should be **REQUIRED , but Employer have options to choose between to show it to candidates or No. 
And please SALARY PART do not be last one to write ,remove it behind employment type.... 

Also please change design  (attached picture as a example) need to know salary per month or per year or per hour if freelane job.

<img width="698" alt="2023-10-09" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/a5584599-3974-450a-9c80-c6ebf45da015">
)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b0519c55-fee9-409e-8398-14b7466336bc">
Done

**Comment by vinayak-vayuz** [comment]
over to @SaurabhattJi

**Comment by Jamalatm** [comment]
@vinayak-vayuz  as I informed before Skills and other benefits, technical skills, should be selected from system and write it if not available already in the system.

@vinayak-vayuz change design salary  as above image.

Salary case should be ABOVE after Employment type

**Comment by vinayak-vayuz** [comment]
> @vinayak-vayuz as I informed before Skills and other benefits, technical skills, should be selected from system and write it if not available already in the system.
> 
> @vinayak-vayuz change design salary as above image.
> 
> Salary case should be ABOVE after Employment type

I've added salary case after employment type but It was not looking good as per the current design.
