### ISSUE TITLE
Employer/post Job/ GENDER FRAME TOOOO BIG 

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1072]
Unable to select gender in the attached picture. Please reduce the frame. ( will be better same for all frames)

**Age frame,need to show AGES FROM 18 Years... to select what I want.**

<img width="960" alt="2023-10-09 (5)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/136c087c-ffca-4459-a731-cadd6cd824cf">

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/90861da9-b96d-4fe9-b908-a1545885360c)
Kindly check, make it others instead of both

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/0d793854-7034-463d-b066-8e60a9614255)
Done.

**Comment by Jamalatm** [comment]
Both not OTHERS

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/38e8ba89-0984-432b-9498-2a4d55f81eb1)
Done sir
