### ISSUE TITLE
Employer/ Post Job/  Add Nationalities And Religions

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1073]
Please Add Nationality, and Employer can add Nationalities+++++ (Optional not Required)

**Please Add Religion (be optional not Required)**

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/7289cbff-0b02-483b-bc81-daac89b7b12d)
Remaining work from backend

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/5736b99d-2972-47dc-8f87-2a8d7daf8f93)
Done Remaining work from backend
