### ISSUE TITLE
Employer/ Post Job / Add City to location 

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1076]
Job location frame also soooooo BIG... please reduce it for a countries only and add cities.

<img width="960" alt="2023-10-09 (8)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/a80e8256-834a-4579-8f74-2e7b1b9301dc">

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/1b5ca3b7-2799-4556-80b4-63962d14a582)
Done remaining work from backend
