### ISSUE TITLE
Employer /Post Job

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1077]
Soft and Technical skills should be in frame and choose from available SKILLS by system or I can add new one.

<img width="960" alt="2023-10-09 (9)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/ba414631-ffea-4fa6-a949-ec4fa7369870">

**Comment by SaurabhattJi** [comment]
@Jamalatm can you provide me some reference for this ?

**Comment by Jamalatm** [comment]
@SaurabhattJi 

<img width="943" alt="2023-10-18" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/879f88f1-6d48-4bdc-9915-a04904f1bd9a">

**Comment by SaurabhattJi** [comment]
@Jamalatm From a job seeker's perspective, we have successfully implemented this feature in our job seeker module. However, in the employer module, we have recognized the need to categorize soft skills and technical skills separately.
