### ISSUE TITLE
Border of the modal

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1078]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/bacc5366-7bcd-40b6-856f-3e32e90aaed6)

**Comment by vinayak-vayuz** [comment]
<img width="848" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/bff447c3-f3f9-4aa8-83e8-dcdf12647c9b">
Done
