### ISSUE TITLE
Contact number placeholder is not visible

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1079]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/9bff663f-d9e4-4abc-bbed-5e16080fe444)

**Comment by vinayak-vayuz** [comment]
<img width="849" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/ff31caaa-6a10-4a78-b37b-ce29dc0454dd">
Done
