### ISSUE TITLE
Employer > Sign in page > issue with social icons

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1081]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/d2f456e1-d8bc-45a8-acf9-c93b8d78d90e)

**Comment by vinayak-vayuz** [comment]
<img width="113" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b5ef8a39-b387-4772-99bc-721ae8ebcd8b">
Done
