### ISSUE TITLE
left and right side space is not equal from top

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1082]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/220d6bf7-d4ce-4118-b579-e7b6c2ede754)

**Comment by vinayak-vayuz** [comment]
<img width="902" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/57460ba2-f317-4564-8a08-42ae3b158fc3">
Done
