### ISSUE TITLE
in dark mode >> drop down option is not visiblt

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1083]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/0f7d25cd-d30b-46a6-8b89-9e1f0aa32bb9)

**Comment by vinayak-vayuz** [comment]
<img width="162" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/738bb751-db88-4408-ad49-e6d2a6409718">
Done
