### ISSUE TITLE
please make the text equally visible as that of the dots on the side

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1084]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/83827419-617e-475f-b685-f1ede45a240c)

**Comment by vinayak-vayuz** [comment]
<img width="404" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/3a497dfe-9ca9-48bc-a8b8-2ede2099f864">
Done
