### ISSUE TITLE
After change language > enitre page items are not changed in other language

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1085]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/2cdc8033-258e-496b-8b07-01c053da47c4)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/1c2f9728-5dac-4f09-ace2-11332a03f802)
Done
