### ISSUE TITLE
Make sure once a link has been selected then it should not only change the color as well as the weight of the text. It should standout.

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1086]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/2c8b2807-ee41-4d77-93a4-403fb57d3fcc)

**Comment by vinayak-vayuz** [comment]
<img width="338" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/893eb8af-ccb2-408d-8038-0dabd0ccdbbe">
Done
