### ISSUE TITLE
Make sure the header goes all out and leaves no margins

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1088]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/acac2db5-3b27-480b-85b2-f7247324fc7d)

**Comment by vinayak-vayuz** [comment]
<img width="955" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/23f7b921-0faa-4e3c-a233-639c6eafffb3">
Done
