### ISSUE TITLE
fix the box shadow and focus box in header menu

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1089]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/40ae7f21-ef91-4371-a3a2-ff4a92e9b38c)

**Comment by vayuzpriya** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/d410a453-fc59-46dc-8d21-c0b67c004213)

**Comment by vinayak-vayuz** [comment]
<img width="268" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/c38e0a07-b58d-4989-a768-583481b1db88">
Fixed
