### ISSUE TITLE
Don't give borders randomly on the divisions if all are kept without it.

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1090]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/097bdd9e-f047-4f83-8fad-c85a1dcc22f1)

**Comment by vinayak-vayuz** [comment]
<img width="270" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b1d7a0f6-5ebf-41db-a569-f13aa0216d8d">
Removed
