### ISSUE TITLE
language option design looks change when we select dark mode

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1091]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/ec8bcf68-2450-4f12-871c-ddbe4f503b4b)
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/6c8f6ca1-270f-41dc-9748-9794e73d10fc)

**Comment by vinayak-vayuz** [comment]
<img width="237" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/82de9977-6e7c-4115-bea3-2ed62e7b1124">
Done
