### ISSUE TITLE
Why we show these 0 data , in place of this can we show a illustraion and post job option 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1092]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/55b19037-36b1-447a-8ff7-2cecf0f60e6f)

**Comment by SaurabhattJi** [comment]
Condition is applied so @vinayak-vayuz please add illustration

**Comment by vinayak-vayuz** [comment]
![Uploading image.png…]()
Done
