### ISSUE TITLE
After sign up header option is not visible 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1093]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/5582a1ea-9241-415e-8b84-71a1d76667a2)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/c4632744-69d4-40a2-acb9-5784ad70645a)
Its working fine.
