### ISSUE TITLE
fix the Notification box issues 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1094]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/ae2e2f1a-f6fe-428e-9b1d-7c252f9b9e35)
I have not any notification then why I have these option. 
Pls add welcome notification here.

**Comment by vinayak-vayuz** [comment]
<img width="387" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/e04e6fe4-b945-4fc2-831b-40245a683ae8">
Done
