### ISSUE TITLE
View Profile is not working 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1095]

**Comment by vayuzpriya** [comment]
Account creds : priyavayuz001@mailinator.com
Password : Priya@9290

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/6a46302d-5161-497c-955e-c20bdbbf6137)
Its working fine. The blank page occurred because of the onrender issue. Now its working fine
