### ISSUE TITLE
why sign out button is highlighted

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1096]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/133b2428-ca91-4115-9b17-764ab6729e2b)

**Comment by vinayak-vayuz** [comment]
<img width="323" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/08d228dc-bb3a-4183-94a2-2dffe0088970">
Done
