### ISSUE TITLE
If it is a first time user or when their is no data on the dashboard , It should be shown like this.

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1097]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/318bf4af-8982-4b3c-b640-94e7ffada187)

For example, Instead of total views on all jobs, it should be like no views on job (if only one is posted), but if multiple (i.e. more than 1) then it should be no views on all jobs with no 0 on it.

Also, if no job is posted then the dashboard shouldn't be shown rather there should be a CTA to post job first then dashboard should be visible.

**Comment by SaurabhattJi** [comment]
Done remaining work from UI

**Comment by vinayak-vayuz** [comment]
Done from my end too
