### ISSUE TITLE
why Illustration is too big 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1098]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/ac0578a8-e2fd-48a9-8de6-b265302f739c)

- [x] Make the illustration small 
- [x] Why both button have same color 
- [x] why overlay is not added here

**Comment by vinayak-vayuz** [comment]
<img width="956" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/c15779d0-728e-4023-9ba5-12535b6f3528">
Done
