### ISSUE TITLE
add dummy home page here with header

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1099]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/17c5b89f-5a9a-4d3e-8b91-c7a37d8dc12c)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a77dd43c-599a-450a-8bb4-412420e00a27">
Done
