### ISSUE TITLE
language> Readability issue in dark mode

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1101]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/73be034d-e4e7-4ac6-bd3a-74bca8fb332a)

**Comment by vinayak-vayuz** [comment]
<img width="230" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f338a302-2d61-4ec3-823d-2b83358851e2">
Done
