### ISSUE TITLE
No hover effect on cross

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1103]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/0ebb7a7a-0b65-4629-aae7-3014d41c85e2)

**Comment by vinayak-vayuz** [comment]
<img width="910" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/53a25dbb-418d-43b1-a9d1-fe6e50a9434a">
Done, made it look like a button and added a hover color effect
