### ISSUE TITLE
post is not highlighted 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1104]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/f85bbffc-d5c2-4719-b76c-62d3a2f918ef)

**Comment by vinayak-vayuz** [comment]
<img width="955" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/570e2ff1-8974-4b31-9cf2-04989cc13bbd">

Done
