### ISSUE TITLE
Create company page look empty

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1105]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/a466e27a-7ff3-4a18-9874-00113a8bc147)

**Comment by vinayak-vayuz** [comment]
Add illustrations

**Comment by vinayak-vayuz** [comment]
<img width="958" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/c3335b63-a8f5-4722-a11c-4aced994bfd4">
Done
