### ISSUE TITLE
Please decrease the size of gif, & put the content & CTA below the gif

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1106]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/38dafe5b-5c7b-4117-8a76-b63f9b3af4f1)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/90aa6b0d-3e22-4edc-8563-b4d71fa6fd25">
Done
