### ISSUE TITLE
Fix the designs 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1107]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/9cbbc76d-8dd5-48a9-bdd4-7b1a41740c27)

- [x] make seperation between menus and page
- [x] why ad's section is too big 
- [x] why user image showing in logo

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/91d2d7dd-9cee-45e6-a491-736d14554ff0">
Done
