### ISSUE TITLE
fix the create company page like linkeding take reference from linkedin

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1108]
![screencapture-linkedin-company-setup-new-2023-10-09-16_16_18](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/a386f2ec-f24e-40f0-a4ae-e43e0a0bb433)

**Comment by vinayak-vayuz** [comment]
<img width="951" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/032e1054-66f2-4ca6-8b66-9a85079e03e8">
Hope it's better, please review and give feedback
