### ISSUE TITLE
not identify heading and sun menus

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1110]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/d2782790-a3a9-43f8-9280-5804d2b485f7)

**Comment by vinayak-vayuz** [comment]
<img width="237" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b54dd26a-452a-4d2a-8ec7-241b43238060">
Done
