### ISSUE TITLE
create company page option is not showing when I come from post job page and after click on other option both option is selected 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1111]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/e3f24a2c-ccbe-482a-96ba-ee3d1278bb63)

**Comment by vinayak-vayuz** [comment]
Added difference on color on hover state, selected and dropdown open state

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/2ddcceae-0072-4979-a9fa-d6185cfc234d)
