### ISSUE TITLE
why image is not showing in middle

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1112]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/6e61db63-87ef-4399-8488-4c83fabb353d)

**Comment by vinayak-vayuz** [comment]
Now It should be in middle, I have fixed the height and made the overflow inside the modal.
<img width="538" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/d94ebed4-7b45-4d3e-af42-d4fa00601088">
