### ISSUE TITLE
Image cropper : why both btn are same color and scroll out of box

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1113]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/39bb2d2d-ab0d-41f0-8076-3f650fcab685)

**Comment by vinayak-vayuz** [comment]
<img width="545" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f7bb317b-2b39-4bc3-bae4-6a13ac164524">
Done
