### ISSUE TITLE
why this section is added 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1115]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/96d4ca57-296a-4644-a670-bffb00325633)

**Comment by vinayak-vayuz** [comment]
<img width="953" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/43b2681e-5c8e-4fd0-a311-bb3377e652d5">
I've changed its design.
