### ISSUE TITLE
Change illustration after submitting feedback

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1117]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/9ff33fe9-f149-4342-8302-ac7ea4205ad9)

**Comment by vinayak-vayuz** [comment]
<img width="933" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/5d5d6a5c-4c9c-4fdc-87c1-1ad97c3b3be8">
Changed
