### ISSUE TITLE
why i need to scroll this page to save

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1118]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/d23e5b84-e80f-412f-859e-a96f01e43e8c)

**Comment by vinayak-vayuz** [comment]
<img width="955" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/2ce12671-5306-41d7-b40e-2ae3cf090318">
No need to scroll the page
