### ISSUE TITLE
both option are looks selected at same time

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1119]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/9a658ec5-c632-4ade-b03b-fcdc705072d8)

**Comment by vinayak-vayuz** [comment]
<img width="234" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/277fb7d6-576f-4007-8423-08216106861a">
Done
