### ISSUE TITLE
Jobseeker/ Home page

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1120]
"Please add filters  to the search engine."

<img width="960" alt="2023-10-09 (10)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/da3ab582-0113-46de-bc48-0f0832722430">

**Comment by SaurabhattJi** [comment]
@Jamalatm We have implemented the filter on the view all jobs and job feed because in the header we have implemented the only search functionality but for the filters you have to check the job feed and view all jobs page
