### ISSUE TITLE
Web > Employer > Create company page

### ISSUE THREAD

**Issue by vinayak-vayuz** [Anupriyabanger/Bee-Recruiter#1123]
<img width="890" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/31b5c44c-269d-4110-ad6a-8ace29d47bd0">
After uploading the image, It's not showing after refreshing the page.

**Comment by vinayak-vayuz** [comment]
Also remove this user image as it's not about user profile but a company page..
<img width="880" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f07ffb05-e181-403e-8a13-d98373dc98c0">

**Comment by vinayak-vayuz** [comment]
This is showing blank.
<img width="604" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/c9baf82c-e8f5-409f-855b-7da0319ba5b7">

**Comment by vinayak-vayuz** [comment]
- [ ] Also add drag and drop feature
- [ ] Image not showing
- [ ] User dummy image should not be there

**Comment by pankajVayuz** [comment]
@manojnegi07  sir  please check this api when update image . response url is not working .

**Comment by rajasrivastava101** [comment]
Kindly check
