### ISSUE TITLE
Increase the size of bee

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1124]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/f40284de-ad93-4f77-8eeb-2a6d364f5965)

**Comment by SaurabhattJi** [comment]
@naveesha-vayuz need  favicon

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/59dc6515-6827-4cad-ad93-9b128fb9310f)
Done
