### ISSUE TITLE
Please make it a proper square instead of the streached oval

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1125]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/98643b52-7428-49ba-8ed6-24da75dde415)

**Comment by vinayak-vayuz** [comment]
<img width="777" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/47c2e2c8-1a1c-4a77-96f3-5b862b6ce4b7">
Removed
