### ISSUE TITLE
Make them white in dark mode

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1128]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/f747b3a8-74fe-44da-8716-04dc6855e3ff)

**Comment by vinayak-vayuz** [comment]
<img width="308" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b10c3cff-42bc-4a3a-ac7e-3119fce48aa9">
Done
