### ISSUE TITLE
Company page > roles offered> Make it in tag format

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1129]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/14801836-5fd0-4408-965f-4b2f07656294)

**Comment by vinayak-vayuz** [comment]
<img width="504" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/c1ebc771-53dc-486e-8a87-4ee4dfc375dd">
Done from my end

**Comment by vinayak-vayuz** [comment]
@pankajVayuz Validate and pass the data
