### ISSUE TITLE
after fill detail don't indicated what i fill in editor

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1135]

**Comment by vinayak-vayuz** [comment]
| Header | Header | Header | Header | Header |
|--------|--------|--------|--------|--------|
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |

**Comment by vayuzpriya** [comment]
![Screenshot_20231011-160511_Chrome](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/4f7df2d5-abe5-411d-b1e6-b225157834c3)

**Comment by vinayak-vayuz** [comment]
The editor is loading from API so every domain should be registered with it, also I'm unable to change its bg color.

**Comment by SaurabhattJi** [comment]
The editor we are using is not registered with tiny cloud. But in AWS deploy it is not showing any registration message
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/d942c639-f5f3-432c-8ccc-3f1bc43322aa)
