### ISSUE TITLE
I added 2 question still next btn is not enable in post job pre screening question

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1136]

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/620e1100-d879-4e10-85c6-0244abdcb987)
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/eab1ba3b-3ef4-4ee8-b86e-ac5bc9b5ddcd)
@vayuzpriya You can check its working fine.
