### ISSUE TITLE
Text cutting

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1139]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/97a921f0-9222-4d7b-ad60-f00138d04255)

**Comment by vinayak-vayuz** [comment]
<img width="485" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/16597502-6650-4d5f-9632-4a5671545610">

Fixed
