### ISSUE TITLE
Web | employer | create company page | 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1150]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/63e8db66-52f1-4949-96e3-ba6eb5a06b65)
fix this issue

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/ff7328c1-ca5e-4a88-99ac-a3bc39f9c6ef">
Done
