### ISSUE TITLE
if I enter the URL for Verify otp page in new window it's not redirect to sign in or sign up page

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1197]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/1d3d5e98-e22d-4332-afb0-3415f636d8aa)

**Comment by pankajVayuz** [comment]
@vayuzpriya  mam I would find it much easier to resolve this pointer if I had some references available. please share any references.
