### ISSUE TITLE
when you sign in first time no need to show these details and change the illustraion for post job

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1201]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/efe0d585-e56c-47e6-819f-54876a17439f)

**Comment by vinayak-vayuz** [comment]
I need a page for this @Mehulna

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/1d3f52ee-aad2-427c-b6e9-26bfe740acce">
I think it's better now.
