### ISSUE TITLE
Web | jobseeker | navbar

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1202]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/80c15fac-a3aa-46cf-8007-a0dd01925942)

name overlaps out of the navbar please fix this.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/764ee4b1-9003-49ce-87bf-1a24b6d22755)
Done
