### ISSUE TITLE
why white space is comimg in cropper 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1203]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/fb8e2df7-05f5-4b5a-9b9e-d8228422d164)

**Comment by vinayak-vayuz** [comment]
I have fixed the height of the cropping section so that images with any height can be shown inside this modal. If you have any other ways to show this please attach a reference or provide proper Figma design. @vayuzpriya @Mehulna

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a0352a99-bf65-4325-9dc6-a7cdc956e556">
