### ISSUE TITLE
why close button is in red color 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1204]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/e1c558f6-7d33-4120-a67c-a662d261f13d)

**Comment by vinayak-vayuz** [comment]
I don't have Figma design for these buttons so I have no idea of what color should I use!! @Mehulna

**Comment by vinayak-vayuz** [comment]
<img width="220" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/3ec44099-e403-4bc3-8d89-a336aaf1d727">
Done
