### ISSUE TITLE
option hide in editor option

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1206]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/69c4b6ff-c4fe-4bbb-ad27-5b31e7a309d7)

**Comment by vinayak-vayuz** [comment]
<img width="243" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/d4185c3a-932a-4a32-a60b-435a5a88c7f5">
Done
