### ISSUE TITLE
text is not in same line 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1208]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/177aaaa6-2f59-4414-9d3e-c6ab93af3ef8)

**Comment by vinayak-vayuz** [comment]
<img width="387" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/40a521e4-c1f7-4417-8a21-a042b37be61f">
Done
