### ISSUE TITLE
without entering question not able to add post job

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1209]
Without enter question 
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/e430f6b6-8bd8-4e96-bd7c-65cf32ddf825)
after enter question 
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/237f5287-68f8-4a42-a4b7-6f5e9d188781)
when I click on add more question
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/7a38f0c6-5487-4777-9366-49e5ee524220)
then Next option is enable

**Comment by SaurabhattJi** [comment]
@vayuzpriya  This is already discussed ma'am but this is flow to post a job. It is required to fill a question before posting a job. Minimum 1 question is required to post a job or maximum 10 questions are user can fill
