### ISSUE TITLE
if I not filled the add city field able to click on next 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1211]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/7d5c7cf5-6f64-42c3-894c-39a743c16f4b)

**Comment by SaurabhattJi** [comment]
@vayuzpriya  Ma'am we working with a specific requirement from the client so these fields are optional fields.
 
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/bbbe453a-2474-4e62-93e1-e11d4bbbdf8d)
