### ISSUE TITLE
Please make sure to show the page in just one theme not dark + light in one

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1216]
![Screenshot_2023-10-20-17-18-24-03_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/479ca1f5-244e-456d-a78a-40d0a8f4094f)

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/ed4602b9-4db0-4fcf-9318-7a3eaaa72bdb)
