### ISSUE TITLE
Why am I getting validation if I'm clicking on LinkedIn

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1217]
![Screenshot_2023-10-20-17-20-59-56_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/40dc1a70-4059-405a-8601-d9dcffafa350)

**Comment by vinayak-vayuz** [comment]
<img width="863" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/5a1c805d-3a0c-4eac-8d5f-f4592d548d44">
Done
