### ISSUE TITLE
Why am I getting unauthorised when it is a new account upon creating a new account via Gmail.

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1218]
![Screenshot_2023-10-20-17-27-06-97_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/0ce984e8-1f77-4e1f-b5b3-e27d6d322832)

**Comment by pankajVayuz** [comment]
To sign in with Google, you first need to sign up via google the signup page, and only then, when you go to the signin page, you can use Google login.
