### ISSUE TITLE
Error Message received when try to upload Image 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1220]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/1be3d19e-8c76-43d1-a956-151846e30fea)

**Comment by rajasrivastava101** [comment]
@vayuzpriya Kindly attach the referred screenshot, not able to understand the pointer.

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/95c043a3-7d2d-41d6-82c5-1e74f81ed247)

this bug fix .
