### ISSUE TITLE
Not getting the hi icon on Hey Naveesha 

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1221]
![Screenshot_2023-10-20-17-44-16-64_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/987b87c0-de3a-4e02-bc42-edf617a2454a)

**Comment by vinayak-vayuz** [comment]
<img width="655" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a20bdf37-b2de-4cf8-ba24-05d8da898195">

**Comment by vinayak-vayuz** [comment]
Which hi icon? I didn't find any icon in figma design.
