### ISSUE TITLE
profile image is not circle

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1222]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/cc879296-7549-4b98-b6ef-1c4b34cf3da6)

**Comment by vinayak-vayuz** [comment]
<img width="244" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b393a214-d9af-499c-96a6-3d79946fc0fe">
Done
