### ISSUE TITLE
If I'm clicking on the drop down button shouldn't I be getting just the drop down, why is my keyboard getting opened

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1224]
![Screenshot_2023-10-20-17-49-04-52_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/6e1991d7-9f78-4c26-b4e1-f5497371b1b6)

**Comment by pankajVayuz** [comment]
if you select any input field.  The keyboard is always open.
