### ISSUE TITLE
Shouldn't the cursor be blinking after the text? 

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#1225]
![Screenshot_2023-10-20-17-50-42-60_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/0c9e6dad-9cce-4633-9f62-f5e487800435)

**Comment by vinayak-vayuz** [comment]
It's a feature, you can change the selected option.
