### ISSUE TITLE
Employer/ My Jobs/Click View 

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1229]
add tooltip or hover-over information for icons to help users understand the functionality of each icon.

"Experience: 2" — Ensure clarity by specifying if this is years, months, or some other metric.

"No of job Opening: 10" — Minor grammar correction needed: "No of job Openings: 10".

"Accomodation: Yes" — There's a typo. It should be "Accommodation: Yes"

"Salary Range: 29000-80000 MADS p.m." — Consider adding spaces for better readability: "Salary Range: 29,000 - 80,000 MADS p.m."

"Type of Work: Part Time" — Ensure consistency in presentation. Some entries have a colon while others do not.

 Please use **MERN stack (MongoDB, Express.js, React.js, Node.js)**   

<img width="960" alt="2023-10-20 (4)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/a55135e3-4ff9-4f02-9736-14282bfe173d">

**Comment by Jamalatman** [comment]
@SaurabhattJi  check here as well
