### ISSUE TITLE
Employer /My Jobs /  Click View

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1230]
Ensure that the page is responsive, i.e., it should display correctly on various device sizes.

Consider using consistent font styles, sizes, and colors to improve readability.

Add a "Save" and "Submit" and Update  buttons if employers need to update or modify the job details.

Add "Edit", "Delete", and "View Applicants", buttons options to be visible and intuitive.

<img width="960" alt="2023-10-20 (4)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/7debf7ae-f322-4252-a119-1b3d9f805ea3">

**Comment by SaurabhattJi** [comment]
@Jamalatm Employers will only have the ability to edit a job posting while it is in the draft stage. This limitation is in place to prevent conflicts between job seekers and employers. To view the applicants for a specific job, we offer an Application Tracking System, which allows employers to see the total number of applicants who have applied for that particular job.

**Comment by Jamalatm** [comment]
@SaurabhattJi   Im a User (Employer) I deleted a job posting by errors, how can I return it ! do you think its good save my time to make a new one !

**Comment by SaurabhattJi** [comment]
@Jamalatm  Sir if you deleted a job by error so as per your requirement **Deleted jobs** are there under the **My Jobs** section 
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/41580998-cabc-442e-9b84-c5158f885282)


Or in this section you will find the all deleted Jobs.
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/8fba8883-3ad2-45bb-b95d-6b98a90d84fe)

And you can restore jobs from the dropdown menu
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/c5ede78d-0d2d-45c7-bd22-2ffa9e7dff06)

**Comment by Jamalatman** [comment]
close
