### ISSUE TITLE
Employer/ My Jobs/ 

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1232]
Each icon (view, applicant, saved) should have a tooltip for clarity when a user hovers over it.
Consider using more contrasting colors for numbers to make them stand out.

The "Inactive" label may cause confusion. moving it to a more prominent spot or using a different visual cue, such as a badge or color indicator, to show the job's status.

The "View applicants"  if there are zero applicants,  disable the button or changing its color to indicate that there's no action to be taken.

The "a month ago" timestamp  ensure it's accurate. add an exact date in a tooltip for clarity when a user hovers over the timestamp.

Job card change the cursor to a pointer when hovering over the card and maybe adding a hover effect.

The location Ensure it's clickable when users want to filter all jobs in same location or see more jobs in that area.

<img width="329" alt="2023-10-22 (2)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/2310adca-661f-46f2-9b70-fc9005750ab5">

**Comment by Jamalatman** [comment]
@SaurabhattJi  Check please
