### ISSUE TITLE
Employer / CV Management / Filter by...

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1244]
See attached image, as a user I'm confused what to do now, there is no back button again, should I click again on CV Management to start from the beginning ????of course should not be like that 

all Titles like CV Management, My Jobs..... we need try it in label with clear color

<img width="960" alt="2023-10-23 (1)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/4e6fc7cf-49e4-4d12-a27b-bf1be1bb8293">

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/60f33d84-5de2-4d6c-bb95-785485bc9c10)

you can check it  easy back button implement .
