### ISSUE TITLE
Employer Section/ Edit profile Information

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1251]
**Personal Information:**
Upload Image: Ensure that user can open his camera.
Address, City, Country, and PIN Code: Consider adding placeholders or examples to guide users on the expected input format.
Gender: Add an option like "Prefer not to say" or "Other" to be more inclusive.
Nationality: Change "Indian." to "Indian" (remove the period for consistency). and label its too big for nationality.
Alternative Phone No.: rename to "Alternative Phone Number" for consistency.

Add in company information : 
Company Name: Add a placeholder or example (e.g., "XYZ Pvt Ltd").
No of employees: Change to "Number of Employees" for clarity. Also, a dropdown with ranges like "1-10", "11-50", etc., for easier selection.
About: Rename from "Abouts" to "About Company"  Also, provide a longer text box or a textarea to accommodate more information.
Job License: Change with "Commercial License".  add a tooltip or info icon to provide more details. Also, the language in French .
Add also Telephone +Country+City+ Address+ Website + Official company email, Attach company profile.
UI Consistency: Maintain consistent spacing, font size, and font type across all input fields.
Tooltip: For fields that might not be self-explanatory, consider adding tooltips to guide users.
Validation: Implement real-time validation to provide instant feedback if a user enters information in the wrong format.
Save Button: Add a prominent "Save" for new creating or "Update Profile" button for already profile at the bottom after all fields.

<img width="960" alt="2023-10-23 (5)((((" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/fbdd8a75-2930-430d-b1de-daa16897cfa0">

**Comment by vinayak-vayuz** [comment]
Added camera and gallery option
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/73e8bc5c-b237-4042-a384-b505b6f18773">

**Comment by Jamalatm** [comment]
@vinayak-vayuz  What about other remarks !

**Comment by vinayak-vayuz** [comment]
This functionality is mostly used in apps and not in web.
