### ISSUE TITLE
Employer / Change phone number

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1252]
**Logo & Name Alignment:**
The "Bee Recruiter" logo and name appear to be slightly off-center. They should be aligned to the center for a more balanced look.
Use consistent icons for all items in the settings menu. Currently, only the "Settings" item has an icon.
**Change Phone Numbers Section:**
"Change Phone Numbers" could be more concise as "Change Phone Number".
"Previously added phone numbers." ends with a period, which is unnecessary for headers. It can be removed for a cleaner look.
The primary phone number field might benefit from a clearer label, such as "Current Primary Number".

**Add a New Phone Number Section:**
The graphic of the phone with an alert symbol is ambiguous. use a more descriptive graphic or adding a brief caption to clarify its purpose.
The placeholder "Phone No" could be written in full as "Phone Number" for clarity.
The input field for the phone number might benefit from a sample format hint (e.g., "Format: 123-456-7890").
Add country code , and format change Automatique as per the country choosed.

**Password Confirmation Section:**
The text "Confirm your Bee Recruiter password." might be clearer as "Enter your current password for verification.

**Aesthetics**:

The design uses a mix of rounded and sharp corners (e.g., the settings menu has sharp corners while the phone number fields have rounded corners). please use a consistent corner style for a more cohesive look.

Data Privacy:
Add a brief note or link about data privacy, especially since users are being asked to input personal phone numbers and passwords.

<img width="960" alt="2023-10-23 (8)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/d9d73650-d72f-4f9d-8831-45b4f94d61c9">

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/4869d52c-ad47-430c-a67b-835d94b123ab">

**Comment by vinayak-vayuz** [comment]
@Mehulna Need replacement of the illustration

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/25ec5019-0894-4ee8-ade5-0b06798c4530)

changed phone input.

**Comment by pankajVayuz** [comment]
@vinayak-vayuz, fix the phone input field style.

**Comment by vinayak-vayuz** [comment]
Ok @pankajVayuz

**Comment by vinayak-vayuz** [comment]
<img width="371" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/1a6d0207-dbd7-480a-9066-c568c102f8cf">
Done

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/249438eb-77b9-4119-b938-e5a936d2ed15">
Done
