### ISSUE TITLE
Employer / Edit profle/ Change password

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1253]
Note Section:
"please follow following set of rules to keep it absolutely secure." can be rephrased to "please follow the set of rules below to ensure utmost security."
Password Rules:
"Atleast" should be two separate words: "At least".
"At least 6 characters."
"At least 1 upper case (A-Z) & lower case (a-z) letter."
"At least 1 number (0-9)."

**Settings Menu:**
add icons next to each menu item for better visual representation and user experience.
A tooltip or help icon next to "Change Password" could be useful to provide users with more information or guidance about why and how often they should change their passwords.

add subtle hover effects on clickable items to improve user interaction.

add more spacing between the "Change Password" section and the animated characters on the right for better clarity and readability.

The X button is placed a bit far from the "Note" box. Consider moving it closer or providing a clearer design connection between the button and the box it's intended to close.

![Uploading 2023-10-23 (9).png…]()

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/8f6dcc02-76e5-46da-a942-721b0425997a">
@SaurabhattJi

**Comment by SaurabhattJi** [comment]
![Uploading image.png…]()
Done

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/2f46c4d9-2295-4ff1-925d-3f7dc9d92c02)
