### ISSUE TITLE
web | employer | cv management |schedule interview 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1261]
should be calender validiation fix .

**Comment by rajasrivastava101** [comment]
@pankajVayuz Kindly mention which validation are you talking about ?

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/a637fa82-bb69-4d75-b14a-7ec9b419f00f)

"Interview from date" should not be greater than the "interview to date," and in the date picker, the user should be able to type and select a date in the input field as well.
