### ISSUE TITLE
Web | Employer | edit profile 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1262]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/7acaea95-d2b7-4e93-976d-d140ec54699c)
when you click the save image button it shows this issue.

**Comment by vinayak-vayuz** [comment]
<img width="640" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/6e7af695-110c-40d2-b266-7d1e460d0014">
