### ISSUE TITLE
Web | employer | edit profile 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1263]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/fb752991-daaa-4a4d-93cc-beea4d6e2f8f)

fix the no of employees and pin code box.

**Comment by vinayak-vayuz** [comment]
<img width="903" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b9a41545-6c8d-4f9f-b973-64af926310c7">
Done

**Comment by rajasrivastava101** [comment]
Kindly check.

**Comment by vinayak-vayuz** [comment]
It has been fixed.
