### ISSUE TITLE
employer>jobdetail> alignment issue

### ISSUE THREAD

**Issue by atul-gautam-au6** [Anupriyabanger/Bee-Recruiter#1266]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/58418713/83de35a6-ca4d-4830-a50a-60cfd456b831)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f60ecf1b-377e-49f7-a895-3fd2cabb049f">
