### ISSUE TITLE
Empoyer > ATS > Schedule > "to" date should always be greater then "from" date. check in screenshot

### ISSUE THREAD

**Issue by atul-gautam-au6** [Anupriyabanger/Bee-Recruiter#1269]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/58418713/9d01655a-0ebf-40cf-8e26-b634f52eff70)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/a1515828-0be8-4978-8548-d632504ec504)
Done
