### ISSUE TITLE
employer>jobdetail> saved job

### ISSUE THREAD

**Issue by atul-gautam-au6** [Anupriyabanger/Bee-Recruiter#1270]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/58418713/e46d2f66-084f-45ca-80ca-89e99fc27473)
there are 9 saved  , when i go into that page showing empty,have a look into attached screenshot
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/58418713/8bb3f55e-eefd-4bd1-9831-bc3b2b51e2a4)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/afb6a97e-b15f-43bf-a36e-5ffaec091c47)
This is for how many users saved your job.
Currently their is no navigation required.
