### ISSUE TITLE
Employer / Post Job

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1272]
Add select both gender and    "Optional" 

<img width="960" alt="2023-10-28 (1)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/9888ec23-9ffd-4ee9-87b5-833f40d194dd">

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/5ab39c94-9496-44d9-a5e8-e6635c3a0138)
Done sir
