### ISSUE TITLE
Employer/ post job

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1273]
Can we do Age in one case ! 

<img width="396" alt="2023-10-28 (2)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/ac61dfa5-90f5-4ef8-8a32-842e6f418656">

**Comment by SaurabhattJi** [comment]
@Jamalatm  Yes sir if max age is not required than we can use only min age. If you want min and max age are required fields so we can implement this functionality also.

**Comment by Jamalatm** [comment]
@SaurabhattJi   I means use min and max age in one field ?

**Comment by SaurabhattJi** [comment]
@Jamalatm Sir we can do that but for more clarity we are separating the min age and max age and it is guiding user by its label.
