### ISSUE TITLE
Jobseeker/ Job listing

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1277]
**Job Listing:**

<img width="960" alt="2023-10-28 (6)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/f6899153-6171-4728-9d83-64e05139f0a1">

The job title "HR Manager" and company "by Moroccan Agency" consider increasing their font weight or size for better emphasis.

For the salary "30000 MADS p.a.," clarify what "MADS" stands for, especially  our platform is used internationally. Also, spell out "p.a." to "per annum" for better understanding.
The icons for "2" (potentially years of experience required), "0 Applicant", and "3 Viewed" are clear, but it would help if you could have tooltips or labels for better clarity. For example, not everyone might understand what the "2" stands for.
The word "Applicant" should be pluralized to "Applicants" for consistency.
The "Apply" button  add some hover effect (like a subtle change in color) for better interactivity.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/3a258c32-38da-4cf4-8316-70a0c1f989f6)
Done
