### ISSUE TITLE
Jobseeker/ Search+Job listing

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1278]
<img width="960" alt="2023-10-28 (6)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/88adf7be-6e5e-4663-b1ee-7ab5a6ce0a85">

Ensure that there is consistency in font size, weight, and style across different elements of the page for a more professional look.
+add a filter or sort option, allowing users to filter jobs based on salary, location, company, etc.
The space on the right side of the job listing looks unused. Consider utilizing this space for additional information, advertisements, or other relevant features.

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/9c93b7da-ecca-4e97-836c-a8816e746f93)

@vinayak-vayuz  please add a salary range filter in this screen.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/c38e9983-df13-4dd6-aa72-f0941d1cd7d4">
Please add company, location & salary range filter. I've created the UI @SaurabhattJi

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/f6183adf-6be2-4c11-9a10-e4a288a78773)
Done from my end now UI work remain. @vinayak-vayuz

**Comment by vinayak-vayuz** [comment]
<img width="262" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/83e47330-fe01-4e4d-be22-cd1cf0742e0c">
