### ISSUE TITLE
Jobseeker/ Click Job view more 

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1280]
Add LINKEDIN

<img width="960" alt="2023-10-28 (7)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/70c7fbe7-4190-4843-8eac-be54e664f34b">

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/dd4609a7-b8c4-42b5-93e6-046637b847d3)

@vinayak-vayuz  please fix this Linkedin logo position .

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/348bef1b-d1eb-4ba4-acc1-43e840e7be9b">
Done
