### ISSUE TITLE
Employer / Post Job /Nationality

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1283]
As a user I want to select more than one nationalty.... so please add that 

Job description desing need to change 
Resposabilities as well 
Benefits and skills as well 
Thechnical as well

attached images as a reference.
<img width="566" alt="2023-10-09 (1)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/16aa129b-fd4e-4b0a-b2a1-659f7411def0">
<img width="911" alt="2023-10-09 (4)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/bf463b11-ea94-4352-ab45-82b2f6ae034c">

<img width="960" alt="2023-10-30" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/b1e1f587-6707-4473-8f9e-c8d5ec9e56bc">

**Comment by vinayak-vayuz** [comment]
Fixed the UI
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/bd04490c-3f8e-4dfd-9eab-6a6b2ef77ea1">

**Comment by Jamalatm** [comment]
@vinayak-vayuz please Correct job location as well.  should be change by country
