### ISSUE TITLE
Employer/ View Job

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1287]
As a user I want to see the job information very organized; here it looks disorganized

<img width="960" alt="2023-10-30 (7)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/8efd1732-5241-429f-8931-cc1f6bf95e92">

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/5b4ec532-3200-499b-aa4d-4fd1984f4055)
Done
