### ISSUE TITLE
Employer/ View Job

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1288]
Attached Image please fix that.

Also I can't find how to Manage My Job...after click on Manage I can only see the job

<img width="960" alt="2023-10-30 (8)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/2bd3386b-d6ce-48e5-b8cf-86974f75f410">

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/60bb4cfb-2272-4cea-ae06-754904c98256)

**Comment by Jamalatm** [comment]
@vinayak-vayuz  see attacached image

[
<img width="960" alt="2023-11-02 (4)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/0ac56636-dbc9-465e-ad63-3d59850c9671">
