### ISSUE TITLE
Employer/ Edit Profile

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1289]
Camera/ File not working

<img width="960" alt="2023-10-31 (1)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/1b73df78-d980-454a-b946-0f1ffa5a6f2e">

**Comment by vinayak-vayuz** [comment]
As of now camera has been removed as It's not a common functionality in the web. Mostly it's an app feature.
