### ISSUE TITLE
Employer / Edit Profile

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1290]
See attached image.

<img width="960" alt="2023-11-01" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/f1bd07f7-edcd-4de9-b42e-c1ae13f8fe39">

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a9779aeb-6dc3-46a3-a5dd-e68eba80674a)
Done
