### ISSUE TITLE
Web | Employer | dashboard | 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1292]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/2e4d1ff3-9454-4103-b083-aaccbaf12f86)
when we first time visit to employer dashboard at signup .
logout popup overlap. please fix this issue.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/43808d4b-7ae0-46f1-9092-2bb664c0b39e)
