### ISSUE TITLE
Web | institute | edit profile 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1294]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/4f5fa5a9-b747-4b1d-84d9-17cb895588e3)

fix the input field add phone number input and fix the country data proper format. and fix maxlength

**Comment by rajasrivastava101** [comment]
In the country dropdown there are  only 2 countries are reflecting.

**Comment by rajasrivastava101** [comment]
still there are only two countries are reflecting in the dropdown.
