### ISSUE TITLE
web | institute | dashboard 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1295]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/d2daba93-126d-47e2-b91c-5ba00b7bd964)

fix the Selected Candidates and Shortlisted Candidates  user icon and user count.

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/ca4f1880-df3e-4b3f-a526-444bb5962e67)

@vinayak-vayuz  please fix the style  Selected Candidates and Shortlisted Candidates user icon and user count.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/071c3e47-692d-4111-99d3-36f53b5a9779)
