### ISSUE TITLE
Web | jobseeker | my resume

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1299]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/d155c772-50f9-49a0-a37d-81c2cc5b02e2)
this template is not looking good .
please change this template.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/54d0d0dd-41f9-43a1-a9a1-e43fbb6cfce7">
