### ISSUE TITLE
web | employer | profile-info  

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1306]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/e8eca6cd-bbd8-4eea-8d8b-8a34dec2d70c)
 fix this image preview scroll.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/ca7d3e22-75d5-42d5-acd7-638bd95b1f24)
Done
