### ISSUE TITLE
web | employer | edit-profile 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1309]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/6176df18-d6d9-4c63-8319-fdf59e4a9734)
choose file button not visible in the Safari browser in day mode.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0548d588-ac0d-466b-a758-56e9b8282bf9)
Fixed
