### ISSUE TITLE
web | employer | setting 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1310]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/eefc464a-3274-4e4e-be8b-4dcdc1bfacc6)
When we go from one setting option to another, our scroll bar always remains in the middle and does not start from the beginning. Please fix this.

**Comment by vinayak-vayuz** [comment]
I have added a code for the issue, now it should be fixed.
