### ISSUE TITLE
Web > Employer  > Loader

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1313]
The Loader is not coming in center.
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/effe4b70-a65d-4d4d-97ef-985580fc1ea2)

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/368dd269-62a4-45ad-ba01-f13304c56519)
