### ISSUE TITLE
Web  >  Institute > dashboard

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1316]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/129445d9-07bf-47a4-b9e5-b9638cb8abfb)
Filters done no UI work is remaining.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0fd5aba2-dced-45d7-925c-387c249b6a91)
