### ISSUE TITLE
web | employer | cv management 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1317]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/03b73b6f-3d7f-4dda-9bb4-452ac4ef7d11)
we should when click any filter and then close it.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/2f8cb338-3326-47fb-b57a-7153fa56eb3e)
Done
