### ISSUE TITLE
web/institute/Application Management

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1321]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/5610d0f0-76ad-497b-ac3b-17b5baf29fea)
fix state management in this page .

**Comment by rajasrivastava101** [comment]
Kindly check into this state management issue. I can see issues still.
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/f01c5e65-ef2d-4dd3-a199-62b75ca7db5f)
