### ISSUE TITLE
Web > employer > My Jobs >UI

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1323]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/24197b28-e19a-4952-94b5-6b4c67865c16)
make this page responsive .

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/1a35666e-d724-4669-8507-e7d8ca052b16)
