### ISSUE TITLE
web | institute | profil info 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1325]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/d24138c2-1ff3-4e4b-a531-f4df33c236e1)

fix this scroll bar.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/d7f30a6c-d1cf-4656-a25e-651b346bcf2e)
