### ISSUE TITLE
Web > Employer > Job Detail

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1327]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/39096d8a-acd2-4ff8-b720-1e76346a94bd)
Fix this UI

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/898675f3-e158-4d2b-9b24-37951196e041)
