### ISSUE TITLE
Employer > Post Job > Dropdown looks selected

### ISSUE THREAD

**Issue by vinayak-vayuz** [Anupriyabanger/Bee-Recruiter#1328]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/8f088e18-ddee-4b65-a5fc-b7a775931005)

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/ecda7000-a8cd-49f2-aa98-2335dd643e2d)

this problem is fixed.
