### ISSUE TITLE
Web > Employer > Manage Job

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1335]
Data is not coming correctly.
Data is showing the total rejected count (coming from dashboard). Instead to that the data is coming from the particular course API

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/6e5b3cce-f7c2-438b-8360-a3512f58b499)

this problem is fixed.
