### ISSUE TITLE
Web > Employer > My jobs 

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1339]
Show the total number of post jobs.

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/f1a2c1c1-e34b-4d6a-afa2-d0d2dcf1e0d7)

@vinayak-vayuz  fix this ui total jobs

**Comment by vinayak-vayuz** [comment]
<img width="251" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/fed9bd29-0031-4401-9dfe-f6d2ef285f5a">
