### ISSUE TITLE
Web > Employer > Deleted Jobs

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1341]
Show total number of deleted Jobs

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/d5afe67b-12ac-43c2-995e-72e9d5346e49)

fix this issue .

**Comment by rajasrivastava101** [comment]
@vinayak-vayuz The Number of deleted jobs looks very big, make it better and change UI of it.

**Comment by vinayak-vayuz** [comment]
<img width="460" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/3221ef78-326e-4021-8d98-ee7011f38934">
