### ISSUE TITLE
Web > Employer > My calendar  > Detail page

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1357]
Add Cancel and Re-Schedule interview option.

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/9f78c515-21ee-4988-8749-363a1b92c369)
@vinayak-vayuz  fix the style of rescheduling the interview and cancel the interview button.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f8596f1a-1b1e-4d90-b253-e40b62df6b8b">
