### ISSUE TITLE
Web > Employer > Draft Job > Detail page

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1371]
Add three dot button where employer can delete and edit the job

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/5902f4a9-5086-4888-bce8-d089c6d8bfef">
Please check these @SaurabhattJi

**Comment by SaurabhattJi** [comment]
As discussed only manage and edit buttons are there if employer redirects from the my jobs page which are already posted jobs so it will show the manage option but if is from draft jobs it will show edit option.
there is no need to delete the job from the detail page.
