### ISSUE TITLE
Web > Footer

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1379]
Add a footer

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a9b906fb-0f7c-4894-a09a-817d385a7e42">
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/6d8948f8-7f95-48b4-83c4-057d4f1c4c67">
