### ISSUE TITLE
Web > employer > Draft Job

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1392]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/f5d3ba40-46f1-4914-926f-9c4319d48b7a)
No data page not in center.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f2b76fc1-96ae-4380-a947-f40faf54b5ac)
