### ISSUE TITLE
web |jobseeker | navbar 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1393]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/d4c05c65-6917-4739-91eb-38cc1d69fc7b)

I am not able to click the cross button to fix it.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/34b44dcc-508b-4688-b8e5-5aefb1a39d16">
It's working now.
