### ISSUE TITLE
check box and text not align

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1395]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/fc4511cd-7903-4695-b8d4-9545fa7e3266)

**Comment by vinayak-vayuz** [comment]
<img width="340" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b7104a05-ff60-4204-b736-755bc96cc5e2">
Done
