### ISSUE TITLE
can't identify where need to be click to switch

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1396]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/ea98f579-f0e8-46c1-ad4d-fc2b8e6eedd8)

**Comment by vinayak-vayuz** [comment]
<img width="365" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/309a2735-b9d9-45e5-bcd7-160fd61681a9">
Added like an hint
