### ISSUE TITLE
Header is not same for course and job 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1397]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/a11e28e9-8a5e-4843-a190-8390e3c20a2a)
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/99cb5352-db45-4d3e-8480-657f6a89cb66)

- [ ] check space and alignment

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/40a9c116-f87a-42a0-a6ef-1864caca1ef4">
 DOne
