### ISSUE TITLE
this looks very bad and images are stratched. 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1398]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/fc2eb178-3f4d-4219-bbf6-5b037451a8fd)
Pls change the design or add proper logos here.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/9904fc67-0e82-4fcb-889a-331e4e3e0624">
Done

**Comment by rajasrivastava101** [comment]
ad banner is not of consistent in sizes.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/084e68d9-ea3d-4d33-ab80-f0a07ebb59a4)
