### ISSUE TITLE
View all position need to be change

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1399]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/807c98bc-daae-4fb2-adba-847b13bc860d)

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/af5da28a-5cd5-44b6-bd18-658e938d072b)
