### ISSUE TITLE
why we are not added illustration here if user not added data 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1400]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/e7a5bb89-384a-4692-8ea3-e3d07be9e7b2)

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/6fa1f59c-f1f8-45c7-b1ce-94b4b31f1292)
