### ISSUE TITLE
not able to scroll Professional Experience modal, how i fill details, modal looks bad. 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1401]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/182d7d37-b44f-4ff0-b9db-1175a2663711)

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b7ccfdc5-cb67-401a-b985-041f53000167)
