### ISSUE TITLE
why edit option is visible if data is not added

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1403]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/f47f8735-92bc-4986-abba-954def42e28e)

**Comment by vinayak-vayuz** [comment]
Done, It won't show like that.

**Comment by rajasrivastava101** [comment]
Still, the button is enabled when data is not there.

**Comment by vinayak-vayuz** [comment]
<img width="644" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/10be1a9a-ce2b-46a5-bdd5-6f982014e410">
I have removed from all the section, missed other section last time.
