### ISSUE TITLE
When I click icon look like this 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1404]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/67621747-17ff-4775-8da5-0ceb97b2e54f)

**Comment by vinayak-vayuz** [comment]
<img width="661" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a7cc5d57-28e0-4aa9-8117-6266ca722394">
Added outline none
