### ISSUE TITLE
not able to click on add hobby input box

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1407]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/879c389e-b8b9-42cd-a18e-2171dccc0212)

**Comment by vinayak-vayuz** [comment]
<img width="544" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/96804569-13e8-4f32-aab9-5229b7b84c34">
