### ISSUE TITLE
web | employer | draft job | 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1408]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/57ed51b2-46fc-42bd-b5d7-2b2ec24e043c)
fix this issue . read more overlap on month.

**Comment by vinayak-vayuz** [comment]
<img width="317" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/429568b4-2903-4c1d-8bf7-9c429769897a">
Done
