### ISSUE TITLE
Web > Employer > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1409]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/d0166f96-b80d-4f4c-87d7-0dd910b80c4c)
Text is going out of the card.

**Comment by vinayak-vayuz** [comment]
<img width="882" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/95b2c78c-6e6e-477d-82fd-5d044070a55c">
Salary range has been moved to end
