### ISSUE TITLE
Web > sign up > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1411]
Sign up screen is not scrollable.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0f03d684-e6f5-4802-8139-63d9ff9db208)

**Comment by vinayak-vayuz** [comment]
Issue in the build file, It has been fixed now.
