### ISSUE TITLE
Remove suggestion form input fields

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1414]
![Screenshot from 2023-11-16 17-17-49](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/fde54e20-cb0d-4288-b01b-2c3f6a953286)
![Screenshot from 2023-11-16 17-18-20](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/6cd6f4f6-b510-4954-a23b-eff194cbaf2c)

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/e81c25aa-adbf-4bc5-9cec-20a3b1b20993)
issue fixed.
