### ISSUE TITLE
Give space for error message in validation, because page is up-down when error message is coming 

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1415]
![Screenshot from 2023-11-16 17-26-27](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/8cb86fc8-df96-4637-b9fa-e3dcbd15a640)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/e0ba4f5c-e244-4631-ab26-72cbf654067b">
Done
