### ISSUE TITLE
There is no information with whom we are requesting call back(Like manager, CEO etc)

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1417]
![Screenshot from 2023-11-16 17-42-07](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/409af5a2-ff36-4170-aa81-4d352fa6bcff)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/8e128be6-7e48-4838-b705-3aab6a65fd04">
Added support team will call you at your chosen time.
