### ISSUE TITLE
View profile not redirecting while clicking/ no any link clickable

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1420]
![Screenshot from 2023-11-16 18-48-32](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/024f09c2-7879-43aa-9cbe-29f938269cca)

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/d720b3ae-1964-494e-ac82-68e8d1258c9f)

this  issued fix
