### ISSUE TITLE
web |employer | profile info 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1421]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/bebdce14-5560-4c82-8d29-6e75e0163ac8)

The first time visited this page it locked so badly.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/7cbb11e1-498d-45d4-8c38-c9ca5790fd1f">
Added different designs for both the cases

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/575bc562-1bfa-45eb-bcf0-62e436f447b4">
