### ISSUE TITLE
If there is no count show 0 instead of blank

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1423]
![Screenshot from 2023-11-17 18-26-45](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/e0335136-4249-4a54-875a-b1336e435815)

**Comment by SaurabhattJi** [comment]
Sir this is a UAT pointer from Team Arka. In this pointer they said instead of showing 0 value show No applicants or No jobs here.
