### ISSUE TITLE
web | employer | cv managements

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1426]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/2526a831-4f6c-45d4-93de-7110ba0b0aa5)
Fix settings icon inside search box.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/6fa34f27-70a2-428f-8862-ef8b418167e9">
Done
