### ISSUE TITLE
web | employer | draft job 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1429]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/9850c8d8-612b-4c4a-a582-6a05f1377a1b)
fixed this loader position

**Comment by vinayak-vayuz** [comment]
<img width="153" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b88f49e1-75f7-421e-b5fc-14fa253c46cb">
Done
