### ISSUE TITLE
Page blank on 2 step verification

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1433]
![Screenshot from 2023-11-23 12-03-03](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/d0f50a60-f8a4-4067-bc33-51db58c3972d)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/8e12acb4-d901-4d9d-a550-b77724a20df3)
