### ISSUE TITLE
Html coming in draft jab card

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1434]
![Screenshot from 2023-11-23 12-11-37](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/333afb72-bdee-43b8-ad12-6e28ce912d12)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/fc383478-f348-4c02-84da-0fdd5a5a3147)
Done
