### ISSUE TITLE
fix view job location fields UI not looking good

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1435]
![Screenshot from 2023-11-23 12-14-33](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/e832eb1b-ec98-4819-89bd-91db6cb92568)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b35d0f82-5c3c-4809-920c-ede1ff546b95">
Changed the location field out of the grid, now it can take full width of the card
