### ISSUE TITLE
remove hover from inactive because its not a button

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1436]
![Screenshot from 2023-11-23 12-15-55](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/cf2d4669-ce4a-46ad-82df-2540e5149060)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/6a24da57-ff83-4d24-aa11-8a83b3d0f435)
Done.
now there is no hover effect on current status.
