### ISSUE TITLE
After deleting draft job count should be decrease

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1437]

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/d0640b22-9c94-42b1-a6d2-6fdc07d89cf3)

fixed

**Comment by SaurabhattJi** [comment]
Now the count of draft Jobs is decreasing after deleting a job
