### ISSUE TITLE
After no data , two strips are coming

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1439]
![Screenshot from 2023-11-23 12-32-17](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/484d7cbf-8d9b-4fea-a67a-ed94418f1e3b)

**Comment by vinayak-vayuz** [comment]
<img width="803" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/21fd12a0-a574-4559-b669-b505b12ac432">
Removed when no data also
