### ISSUE TITLE
Add loader in scheduled interview button while click on save

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1440]
![Screenshot from 2023-11-23 12-55-07](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/3afcc8a9-7471-491a-bdfc-678d22b07224)

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/aafd6dca-d95e-4189-948e-80c0424f2172)

fixed

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/631f54ed-9fb1-4e33-9ade-1005202f66ee)
Not able to select the mode of interview.

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/0ccc96ad-a23f-48fc-99af-3c6860eba8ab)

fixed this issue .

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/f6e95de3-7f4b-4ac2-b0a2-14363aacc095)
Kindly align the loader with the text save, its not aligned in the same line.
