### ISSUE TITLE
Web > Employer > My calendar > Interview Details

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1443]
After clicking on reschedule interview the form is blank. Show the previous filled data.

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/fae1cb2f-34af-4ff9-aed4-88918931b503)
Data is prefilled but validations are not getting removed.
