### ISSUE TITLE
Employer/ My Jobs

### ISSUE THREAD

**Issue by Jamalatman** [Anupriyabanger/Bee-Recruiter#1449]
After click on Manage (first attached image) we see another page (second attached image)

<img width="960" alt="2023-11-28" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/151383090/72576769-9688-4fdb-9cd2-98a97b66edf8">

<img width="960" alt="2023-11-28 (1)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/151383090/f68fc602-e0cc-4759-8c15-6ed8f88430c7">

**Comment by SaurabhattJi** [comment]
@Jamalatman  Sir after clicking on the manage button you are redirecting to a particular page where you can see the all details of a Job. Like how many applications are in the job how many candidates are rejected and how many interviews are scheduled for this job.
