### ISSUE TITLE
Web | employer | edit profile | 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1451]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/c6bb1e04-d220-4fd7-8867-2627b1500d57)
@vinayak-vayuz  add label to phone field .

**Comment by vinayak-vayuz** [comment]
<img width="226" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0bcee0af-70d5-48ab-834b-7c2b8da246ab">
