### ISSUE TITLE
web | Employer | cv management | action View |

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1454]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/1b965cbf-642b-4ae8-9524-056b53ae95e1)
we should highlight  cv management in navbar  when we are in  user  view page .

**Comment by vinayak-vayuz** [comment]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/c80778da-b661-48c7-859e-e443edaad1da">
