### ISSUE TITLE
Web > Employer > Create company page > Functional > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1492]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/f2ca25a9-7d87-4bb5-91d7-5e11e03470d3)
In the drop-down only two options are visible but when we add multiple tags manually, UI gets torn.

**Comment by vinayak-vayuz** [comment]
<img width="526" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b60aa20d-da68-459e-ad6b-e2a80e14c9e4">

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/1290e9b8-c2af-4edc-931f-68ffc05202fc">

**Comment by milivayuz** [comment]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/8dda9855-676c-45f6-9ebc-01633bc03c00">

Issue is not fixed the UI is breaking if we add multiple roles
