### ISSUE TITLE
Web > Employer > Create company > Functional > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1494]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/9bc371e4-fd67-401a-9c0e-a8113cab024c)
The same is happening here in the country dropdown, only 2 countries are reflected in the dropdown.

**Comment by pankajVayuz** [comment]
@rajasrivastava101  if you want to add new country in this list . you can add the country to admin.
