### ISSUE TITLE
Web > Institute > Sign up > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1519]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/5ca6635a-6161-4abd-9806-af55a6fba19d)
Not able to sign up for the institute after filling up the complete details.

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/9ca3e821-d89b-4a10-8e1a-a7159a34ec7c)

this issue is fixed.
