### ISSUE TITLE
Web > Institute > Dashboard > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1520]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/b30923fb-424d-48ac-8730-34cba062bd7c)
Check with the background.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/6be5c96f-f3b2-4d8d-9081-8cc8da8a2b73">
