### ISSUE TITLE
Web > Institute > Notification > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1521]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/4d784420-04e3-432c-8b0e-6869e29afded)
Not able to click on mark as read, nor functional.

**Comment by rajasrivastava101** [comment]
Not working

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/ff1c9c47-cc50-4720-9dba-de680669bc2b)

**Comment by milivayuz** [comment]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/132be047-b1e9-4925-b24d-472c06642a5d">

View buttons are not working

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/ec02ba14-d84e-452c-bca2-751b559eb1fa)
