### ISSUE TITLE
Web > Dashboard > Institute > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1522]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/a52fecab-ad32-4b4d-a1a9-11fa3d3bd166)
Clicked on the logo of Bee Recruiter on the homepage and it redirected me to the employer module from the institute module.

**Comment by vinayak-vayuz** [comment]
It's working fine now.
