### ISSUE TITLE
Web > Institute > Course detail page > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1524]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/3c6f4aaf-609b-45e0-b25a-08461f66313a)
UI does not look good on the detail page, kindly improve the UI.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/dfc4443a-4444-4915-a9bb-efedee809134)
Now description is also there.
