### ISSUE TITLE
Web > Institute > Post course> UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1527]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/cea76bc6-c9d1-40a8-9eeb-55b995616d8f)
Text fields are black.

**Comment by vinayak-vayuz** [comment]
<img width="888" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0e954a91-c760-4da9-ae81-08dc070eb264">
