### ISSUE TITLE
Web > Employer > preview Job

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1539]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/814ae67c-a90d-452c-bb50-67946e2f27fc)

fix the salary range ui and nationality.

**Comment by vinayak-vayuz** [comment]
<img width="954" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0819b6a5-8bc1-4de1-b9ef-1cc093081bde">

**Comment by vinayak-vayuz** [comment]
check the values @SaurabhattJi

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/0dd54451-2ee4-4e36-9296-c759e1daea17)
Done
