### ISSUE TITLE
Web > Employer > Job detail

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1540]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/7d9a635c-b42c-4685-aaf6-1b35d458c74b)
Fix the UI of nationality

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/969894cc-0fa6-42d4-a09d-53e55e6896aa">
