### ISSUE TITLE
Web > Employer > Sign up

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1551]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/eda8be7b-644e-4d5a-8d17-051b947dd55a)
Show the error message on phone number.

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/d8ff7e29-1742-41b8-9870-2a0438da19c0)

this issue fixed.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/ae48263a-84c1-46bb-a0ae-de566870ad1e)
I have filled only limited data and error message is removed.

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/d040395e-bc0a-44a7-ae67-f4ee1ad56311)
