### ISSUE TITLE
Web >Homepage

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1552]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/c2c330bb-078f-4832-a4ac-d3eff0a388ef)
Dark mode issue

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/bb8d7e83-84e1-40e4-9c06-09532c53d121">
