### ISSUE TITLE
Web > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1555]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/e7d76a43-a91f-4ad0-b908-70ebf48c7e87)
Manage the gap in the landing page, decrease the gap .

**Comment by vinayak-vayuz** [comment]
It's in the redesigning process.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/6d12764c-683f-4975-97ac-5b1b676c0655)
