### ISSUE TITLE
Web > Institute > Signup > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1556]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/75c01c08-91c6-4d23-81b3-2993d12f75cb)
The terms and conditions checkbox is displayed in black, kindly change the color.

**Comment by vinayak-vayuz** [comment]
<img width="357" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/59ab6643-1447-43f8-9169-1cc9519e0e34">
Done

**Comment by rajasrivastava101** [comment]
Kindly align the checkbox with the statement.

**Comment by vinayak-vayuz** [comment]
<img width="442" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/29c2b726-a839-4909-a451-4310ad4eaef9">
