### ISSUE TITLE
Web > Institute > Sign up > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1557]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/1e789cb1-04c5-4c50-ad7e-20d7062eefb2)
Error messages are displayed when we are not writing anything, it should be displayed when start putting inside the input field.

**Comment by pankajVayuz** [comment]
this is required field if you are touched the field .
and not put value then show error.
