### ISSUE TITLE
Web > Institute > Sign in > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1558]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/324fd74c-e844-4753-8889-3930950c0a4f)
When we click on social media login icons, there is a shadow behind facebook and linkdin which is not consistent with Google icon.

**Comment by vinayak-vayuz** [comment]
<img width="462" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/59afc0f4-52a2-4dfd-99f6-6d2d66aa7a6e">
