### ISSUE TITLE
Web > Institute > Homepage > Functional  

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1559]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/f1779deb-b5b1-48ce-bf16-afdf3daecc57)
I logged in to an institute, but it's asking me to post a job instead of which should have asked me to post a course.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/a8f4ff70-2943-4782-b406-f4f9298d2061)
Done.
