### ISSUE TITLE
Web  > Institute > Courses/Programs >Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1561]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/c4f65036-da60-4b35-b2a8-f6db486711bf)
When I use the ascending order filter, it shows the courses posted 54 years ago. Is it in static form?

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/3ea50ab5-e49d-4ce1-a5a7-787baa365026)
Now old data is removed.
