### ISSUE TITLE
Web > Employer > Cropper

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1568]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/2a612202-71b1-4312-a7cf-9022cffef50c)
Fix the UI of the cropper

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/f78aa4da-4fc6-4c8d-8b29-d0b0a52161ee)

**Comment by vinayak-vayuz** [comment]
<img width="340" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/bf831a21-0500-4c03-8f6c-aa158d88324e">
Height has to be fixed for the images
