### ISSUE TITLE
Web > Institute > Post Course

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1572]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/b83110b2-f823-4ec2-a7aa-2649a40c79bc)
Dark mode Issue

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f828cc05-9fcd-4a23-af9a-c80a2c970271">
Done
