### ISSUE TITLE
Web > Institute > Courses/Program > UI

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1574]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/7b456975-3e26-4287-8771-61f286e7a69a)
UI of the course details page does not look good.

**Comment by vinayak-vayuz** [comment]
<img width="874" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/3e2f4292-907b-4c47-9209-6ceeb052a6e7">
Made it better

**Comment by rajasrivastava101** [comment]
These requirements should not be displayed in paragraphs, make it in points.

**Comment by vinayak-vayuz** [comment]
> These requirements should not be displayed in paragraphs, make it in points.

We don't have control over how someone write their job requirement as It's written with a text editor. Whoever write these has to write it like however they want.
