### ISSUE TITLE
Web > Institute > Courses/Programs > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1576]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/e6121eee-2bfc-4d1b-824e-8dc6c57f7691)
Three dots on cards are not visible in a few of the posted courses.

**Comment by vinayak-vayuz** [comment]
<img width="252" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/d2877449-7d66-49c5-a26c-bcf8b0cbdc09">
Done
