### ISSUE TITLE
Web > Institute > Courses/programs > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1577]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/6955c4e5-6233-4db9-85ee-ad4d9d1fac55)
In a few of the cards it is showing null, undefined, or only displaying the sign. Kindly give it a proper logic.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/153ca060-85b8-4b5f-b2ae-aa523a9b6e0f)
Done  and we are also removing the old data.
