### ISSUE TITLE
Interview count is coimng in cart but not coming in right side

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1583]
![Screenshot from 2023-12-07 11-30-05](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/93eab905-e873-4fc5-8023-8606414a5110)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/be433fb5-40e5-4ffe-b199-310ec292696c)
Sir its fixed. now
