### ISSUE TITLE
notification box too big, we can mak it little bit smaller  also i can't scroll inside the notification box 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1587]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/5b49e54f-784d-4624-a4e0-8254448860be)

**Comment by vinayak-vayuz** [comment]
<img width="356" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/1906e473-49ce-42b0-bcec-12ae07270f93">
Done

**Comment by vinayak-vayuz** [comment]
<img width="310" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/65f0756d-93b6-4d11-a7fd-dc9c4eab40c7">
