### ISSUE TITLE
when no course found both no data found and cta coming

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1595]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/ad407604-67e5-4293-812e-0fd6be342f61)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/a81b2ebc-cb1b-4669-8065-fd8ea9c7b74c)
Done.
