### ISSUE TITLE
All buttons are same. Pls change this 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1596]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/0537d351-81d8-471c-aeaf-4324c41fb299)

**Comment by vinayak-vayuz** [comment]
<img width="590" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/19997315-d73e-47cf-ae23-ffc79a88a23f">
