### ISSUE TITLE
No identification for when we apply filters on course page

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1597]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/5a7ce7dd-c76b-4289-b85a-17c2e64e49f3)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/c2a45ce9-2cf2-4107-900a-bb076593905a)
Added a clear button if filters are applied.
