### ISSUE TITLE
No filter for category 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1600]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/9534e48d-5f2c-403d-ac46-6076e3a86170)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/004b083d-f603-43dc-b242-d3ec9dc3c2c0)
Done.
