### ISSUE TITLE
left and right items are not properly aligned

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1603]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/2de1fb78-b90e-432b-8592-92288161705f)

**Comment by vinayak-vayuz** [comment]
<img width="908" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/da969e1d-6537-4a4d-9e4d-5d3cd92d0441">
