### ISSUE TITLE
alignment issue in back and heading 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1604]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/9fd2eef1-1011-4f42-beeb-a4c77174316f)

**Comment by vinayak-vayuz** [comment]
<img width="585" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/29d68d5f-1c2f-4f61-878a-0b2b12dfa96c">
