### ISSUE TITLE
 same deatils are not visible in course listing and detail page

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1606]
![screencapture-brecruiter-vayuz-institute-coursedetail-MTYx-2023-12-07-17_27_38](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/5e23d06c-bf64-43ff-90b1-50e4c6fe3b2e)
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/483448df-9b70-419f-a324-7ea98eb9cc25)

check both images 
details missing on course details page :
1) Category
2) active / inactive status
3) tag which are coming ib bottom 

Certifate image is blur and hover effect is not smooth.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/d10c9a2d-9b6a-4861-8863-d49464727bb2)
Done.
