### ISSUE TITLE
in tag field I can't see full box

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1608]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/283b2b76-3261-4328-ade2-77ca626e7e4f)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/6160a934-d31e-4c16-b7c5-709d1a16b688)
Fixed
