### ISSUE TITLE
unit missing in duration of course , add what we need to hr in min or in hr

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1609]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/4924030d-a748-4499-8ec7-3cd579bab493)

**Comment by vayuzpriya** [comment]
Also only able to add 2 digits here

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/d18af11c-06cc-4161-976c-827fd7731e69)
Units are there but not in min hr format only days month and year options are there.
