### ISSUE TITLE
preview page is not looks nice, no proper spacing no alignment nothing

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1612]
![screencapture-brecruiter-vayuz-institute-course-preview-2023-12-07-17_51_37](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/2a05097a-725e-4407-b9fe-ce1901e85368)

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/dc4991bf-e5a2-48fa-a9c0-0691dcd38490)

**Comment by rajasrivastava101** [comment]
Still could see the misalignment of fields.

**Comment by vinayak-vayuz** [comment]
<img width="364" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/1b56defa-736d-466d-be7a-8aa940bb23c6">

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/48eb5118-09a5-4af8-a2aa-e581207f2b06)
Kindly take references from other websites as it does not look how we are showing certificates.

**Comment by vinayak-vayuz** [comment]
> ![image](https://private-user-images.githubusercontent.com/129847373/296724707-48eb5118-09a5-4af8-a2aa-e581207f2b06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODcwMTUsIm5iZiI6MTcwNTM4NjcxNSwicGF0aCI6Ii8xMjk4NDczNzMvMjk2NzI0NzA3LTQ4ZWI1MTE4LTA5YTUtNGFmOC1hMmFhLWU1ODEyMDdmMmIwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwNjMxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzJmODM4NDk4MDljY2YxZmMyZGNlYzM3ZDNmNjI1YzE1Y2E4YTYxYmJkZmFjYjQ1MjY2MmM5OWYyZDQ1OTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LqTgYAIXGtLwRp0cPziLNcv85nOTxMe17CXqh_ztTB4) Kindly take references from other websites as it does not look how we are showing certificates.

This is not preview of post course instead its the course description page.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/3e067c35-3c0a-4911-8eec-c5ab1d5fa957">
Although I've fixed the issue
