### ISSUE TITLE
again all buttons are same colored why

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1613]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/9dd6849b-c6ad-4928-a552-a03f36b9a640)

**Comment by vinayak-vayuz** [comment]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/da2c5640-a009-4738-b130-9581228c9a72">
