### ISSUE TITLE
after clicking post button size increased

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1614]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/b520cf83-2b1a-4878-9b1e-bca31683d910)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/53844e7a-200e-44f5-974f-e0c8f6c538a7)
Fixed.
