### ISSUE TITLE
after clicking on draft course back option getting this page

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1616]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/4e311e89-082b-4a4a-b8bc-791b7cfa62d9)

**Comment by SaurabhattJi** [comment]
https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/27d176bb-a1f3-499c-bfd4-39ed7560aaf9

Done.
