### ISSUE TITLE
Web > Institute > Post course > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1617]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/c9efadb4-2db9-4bdd-a337-f72932db64a7)
Align the fields in a structured manner.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/10c6fb3a-58ac-46b2-a178-d780ef6efd05">
Aligned and made it look better.
