### ISSUE TITLE
Web > Institute > Post course >UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1619]
Check this, without image, it shows the shadow image of the mentioned text.
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/e5428116-844a-463c-9a79-6fdb382d73d0)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/8f379ff1-bae8-4a70-acee-8a9650ca4788)
Fixed.
now after coming from preview page the image data is remain same.
