### ISSUE TITLE
Employer |Get_All_My_Jobs | API |

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#162]
Get All Jobs and Get My Jobs
=> Add numberOfViews ,numberOfApplicants | numberOfSaved | active | inActive
=> Add filter Day wise,week wise and year wise

**Comment by manojnegi07** [comment]
@pankajVayuz numberofviews and number of savedjobs,number of applications are added. filters logic is not clear.i'll add it once its clear
