### ISSUE TITLE
Web > Institute > Post course > functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1622]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/8311d188-624f-4481-becb-7423d31c51ba)
Responsiveness of the draft course page is very slow, still its in a loading state not showing any data.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/f9736aa1-0af8-4d92-b29a-be9ba164a347)
Done
