### ISSUE TITLE
Web > Employer > Delete Jobs

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1625]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/86a56925-b543-4415-8523-65f5b5c1cb40)
Fix UI

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/9a43fcf7-a2df-4e29-b724-917d30be825a">
