### ISSUE TITLE
Sign up > Institute > the first screen's container section is not in vertically center, its down unnecessarily with top padding

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1626]
![1](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/195359e0-c404-43d1-b343-cd330b7c1f9f)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/83c18e6b-ce24-461f-a6e5-4a1f1e2bee5e">
Done
