### ISSUE TITLE
Sign up > Fields issues > field warning message are starting in small letters and one alert is in title/capitalize case instead of sentence case

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1627]
![2](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/ff697a48-f652-4bb7-8c42-01996b3bf3e2)

**Comment by vinayak-vayuz** [comment]
<img width="342" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/83e513fe-934d-4a94-b808-634e0edbddd4">
