### ISSUE TITLE
CV view option, user details, user card is static and also i cant by subscription, also no back button at usr info

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1628]
![Screenshot from 2023-12-08 12-16-05](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/7ab12b12-bc67-4bb5-87c5-c5ce87f4d316)

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/a29191e5-6194-4fd7-a7a7-9aa70b3ca29f)

back button implement.
