### ISSUE TITLE
web | institute | profile 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1645]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/5eb438aa-7fcc-4056-883f-c6a6b9f84635)
fix the profile ui

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/6c0822d7-7342-4758-8401-f7c5a9a47865">
