### ISSUE TITLE
Web > Institute > My calendar > Functional > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1648]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/e0473390-bf9d-42fd-bd4b-5fea5eef4fe6)
Why is this highlighted if there is no screening scheduled?

**Comment by vinayak-vayuz** [comment]
@rajasrivastava101 This is not highlighted; it's displayed in gray. These dates belong to the preceding month.
