### ISSUE TITLE
Employer | Post Job | Add the following fields in API 

### ISSUE THREAD

**Issue by gauravk-Vayuz** [Anupriyabanger/Bee-Recruiter#165]
Post Job
1)insurance,(Provided/NotProvided)
2) Salary Range ,
3)Pre screening questions
4)API is taking param as job_roles but in Design we are passing two different input on roles page=> you_will and you_need

**Comment by manojnegi07** [comment]
@gauravk-Vayuz  Added fields
Also job_roles is in discussion.
