### ISSUE TITLE
Web > Institute > profile

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1657]
Change the design of profile page according to employer.
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/f91bd006-ff29-4805-95dd-14b31b175f48)

**Comment by vinayak-vayuz** [comment]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/d5235dac-8cac-4209-87ae-6810b793b166">
