### ISSUE TITLE
All these API need some modification |

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#166]
Signup=>add Male and Female fields.
Signin=> Two Factor Authentication variable send in response 
Homepage=> Add month-wise filter
Post Job=> Add fields  1->Minimum Salary 2|->Maximum Salary 3|->Accommodation 4|->Other benefits
Profile Management=> update-details API  add fields |  1|->Company Industry name 2|->Email id 3|->LinkedIn id. 4|->country name 
                                   5|->user_image 6|->Job License

**Comment by manojnegi07** [comment]
1. Post Job=> Add fields 1->Minimum Salary 2|->Maximum Salary 3|->Accommodation 4|->Other benefits - **Done**
2. Signup=>add Male and Female fields. - **Done**
3. Signin=> Two Factor Authentication variable send in response - **Done**
4,Homepage=> Add month-wise filter - **Added  month and year in the response. please group by them at your end** also 
  changed the api please check post man
5- Profile Management=> update-details API add fields | 
            1|->Company Industry name **Not Done Need Discussion**
            2|->Email id  - **Not Done Need Discussion**
            3|->LinkedIn id. **Done**
            4|->country name **Done**
            5|->user_image  **Done**
            6|->Job License **Done**

**Comment by pankajVayuz** [comment]
Thankyou sir

On 2023-04-27 15:37, manojnegi07 wrote:

> * Post Job=> Add fields 1->Minimum Salary 2|->Maximum Salary 
> 3|->Accommodation 4|->Other benefits - Done
> * Signup=>add Male and Female fields. - Done
> 
> * Signin=> Two Factor Authentication variable send in response - Done
> 4,Homepage=> Add month-wise filter - Added month and year in the 
> response. please group by them at your end also
> changed the api please check post man
> 5- Profile Management=> update-details API add fields |
> 1|->Company Industry name Not Done Need Discussion
> 2|->Email id - Not Done Need Discussion
> 3|->LinkedIn id. Done
> 4|->country name Done
> 5|->user_image Done
> 6|->Job License Done
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>

---
Regards
Pankaj Kumar
Product Engineer (I), Web Technologies
Product Engineering Group, VAYUZ Technologies Pvt. Ltd.www.vayuz.com | 
***@***.*** | +91 7739616595

Links:
------
[1] 
https://github.com/Anupriyabanger/Bee-Recruiter/issues/166#issuecomment-1525355142
[2]
