### ISSUE TITLE
no error msg with invalid email i can navigate to otp screen

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1674]
![Screenshot from 2023-12-14 12-47-43](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/b9c60ae2-f397-4501-a05e-cbd3790c2ba5)

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/b2cc2dc2-1bfe-4cc7-9775-edbc600256f2)
this issue is fixed.
