### ISSUE TITLE
Web > Institute > Courses/Programs > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1681]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/7c1f66ea-81ba-424c-b62d-3437d05cb78d)
The search bar looks a bit lengthy. Make it a bit short.

**Comment by vinayak-vayuz** [comment]
<img width="529" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/4b6b902a-60db-4f1b-8cb7-2865b38d3bd9">
