### ISSUE TITLE
Web > Institute > Courses/ Programs > UI  

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1682]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/aafd8b61-cbb9-48c7-a416-398254ad1ff7)
All three buttons are different in size and shape, kindly align it accordingly.

**Comment by vinayak-vayuz** [comment]
The shape and size of the buttons depends upon the size of the text inside the button, It's a hug property.

**Comment by rajasrivastava101** [comment]
@SaurabhattJi Kindly look into this bug.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/ae28c356-1495-474f-a62f-a87765ce0b3f)
Done.
