### ISSUE TITLE
Web > Institute > Courses/Programs > Functional > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1683]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/8c7c0671-b96c-465b-9db1-eeece6f40f2e)
Only two categories are reflected in the background, as well as UI does not seems good as per the platform.

**Comment by vinayak-vayuz** [comment]
I've changed the design, now @SaurabhattJi please do the needful

**Comment by vinayak-vayuz** [comment]
<img width="588" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/92af61de-1d1b-49a7-874a-38545476a534">

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/906a4173-7538-4b62-b96b-867d37b50b36)
Done. I have bind the categories in your new UI component

**Comment by rajasrivastava101** [comment]
Still only two categories are displaying.

**Comment by PrakVayuz** [comment]
These categories are coming from API that are not updated from the frontend
