### ISSUE TITLE
Web > Institute > Schedule Screening > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1689]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/f1136233-0649-4484-af31-6aca04d809e6)
The error message is showing without submitting the form.

**Comment by pankajVayuz** [comment]
interview  location is required field . if you are not fill location value and info  then throw an error.

**Comment by rajasrivastava101** [comment]
Its a wrong approach, if we have not click on submit button why error message should be displayed.

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/8c79b322-2812-4e65-a492-2f4d647b54f8)
this issue is fixed.
