### ISSUE TITLE
Can't click check box of post course guideline and also can't open guid line link, too much space in footer

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1691]
![Screenshot from 2023-12-15 14-23-20](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/f4305c94-0e82-495c-adec-fa9f826d5cad)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/1f1a1f02-9729-44cc-b443-f8d77aca13fa)
Done
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/d320fddc-3eb8-44e3-ab93-d435130129b9)
Done

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/87697e0c-82b4-4f62-96e1-2eca042e9ae3)
Guidelines opening in the new page.
