### ISSUE TITLE
drag and drop not working in post course, either fix it or remove it

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1692]
![Screenshot from 2023-12-15 14-29-35](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/0efa11f7-88f9-44fb-9062-5c96ea032554)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/4d1cbfb2-39d7-41f9-9eef-fd7ed50e542a)
Done

**Comment by MaroofTech** [comment]
@SaurabhattJi write sample certificate instead of certificate
