### ISSUE TITLE
I can create null course

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1693]
![Screenshot from 2023-12-15 14-34-38](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/1c9efe7e-97ec-424a-8e23-be4796c05fd6)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/84af55c7-5609-4c0f-be98-d3ca96b79453)
Validation fixed.
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/b9ca8ce3-dd51-4637-b206-f613084bb6c5)
