### ISSUE TITLE
Once i delete course, no loader/toast coming also its not removed from course program page

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1695]
![Screenshot from 2023-12-15 14-34-38](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/35fc8db1-be4e-438b-802e-b26ca2e5492d)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/8d96c5b1-fe7b-4923-a954-5864f8af478e)
Loader added.
