### ISSUE TITLE
i can add end date less than start date in post course duration

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1697]
![Screenshot from 2023-12-15 14-42-06](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/48b5ba2f-6622-4691-b89b-2b65ba314050)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/55702f4a-5b21-4113-8356-836a9011cb6d)
Validation fixed.
