### ISSUE TITLE
course is active in listing but inactive in details

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1700]
![Screenshot from 2023-12-15 14-53-46](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/704c4f57-2b80-46e6-bd13-f8640ef6fedc)
![Screenshot from 2023-12-15 14-53-34](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/4ce19bae-fdda-477c-8ed5-4cd6621c3425)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/468947a3-43f9-4e09-9fdb-d09989dcd172)
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/1eb28a45-82d7-4612-b081-74deae27879f)
Fixed
