### ISSUE TITLE
I have one course but 2 coming in dashboard count

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1701]
![Screenshot from 2023-12-15 15-00-16](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/e4ea0863-b97c-41ab-a3aa-a3787afb66ce)
![Screenshot from 2023-12-15 15-00-10](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/6b6c9a9f-4ae6-49f8-99b5-e6d387eb13e7)

**Comment by SaurabhattJi** [comment]
In dashboard there is the counting for total courses posted by you. Incase you have deleted on course it will not shown on the course listing page but have posted a course so that's why the counting is there

**Comment by MaroofTech** [comment]
> In dashboard there is the counting for total courses posted by you. Incase you have deleted on course it will not shown on the course listing page but have posted a course so that's why the counting is there

@SaurabhattJi  As per me we need to show here excluding deleted one
