### ISSUE TITLE
Web > Institute > My calender > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1708]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/7df5951d-39b0-4b14-ae92-2eff38308a7e)
Cancel screening is functioning like a button. So if it is a make, kindly make it a button.

**Comment by vinayak-vayuz** [comment]
<img width="154" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/46c17493-e6bd-42d2-b51c-88505ca9bc48">
