### ISSUE TITLE
Web > Institute > My calender > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1709]
If we are cancelling the screening, don't cancel it directly. Instead of this adding a check that are you really want to cancel the screening.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/ea7ba265-ce53-4089-a41c-6a02755ecf6e)
Remaining UI Work.

**Comment by vinayak-vayuz** [comment]
<img width="725" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a7e6607b-665b-4294-82a4-b23d7fc07b78">
Done

**Comment by rajasrivastava101** [comment]
Kindly make it a screening instead of an interview.

**Comment by vinayak-vayuz** [comment]
<img width="370" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/276a6a30-6b00-4d71-aa6e-b98f44a2e0fb">
Made the buttons and inner title screening for institute and interview for employer
