### ISSUE TITLE
course title and NA both are coming

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1711]
![Screenshot from 2023-12-15 16-07-30](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/2b84657a-33f6-43bf-8a1c-c40cc4c444cf)

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/d90353cc-0b90-4613-a775-102cc59c8f16)
