### ISSUE TITLE
no data will come in center(draft and delete course)

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1712]
![Screenshot from 2023-12-15 16-11-34](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/53aafc53-8c1d-49c3-9680-b941d790d589)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/faf3d323-66b4-4495-b5b3-86fd685307a0">
