### ISSUE TITLE
night mode issue in notification page also no back btn

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1717]
![Screenshot from 2023-12-15 16-44-11](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/60e7d2fb-c11a-42a2-ac86-0e307f809941)

![Screenshot from 2023-12-15 18-26-44](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/2493e96c-3cb9-41b2-a698-0381705825c1)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f789fb38-3196-4b31-983c-fd78f9fd6d36">
Fixed for all the modules i.e. employer / institute / jobseeker

**Comment by vinayak-vayuz** [comment]
<img width="367" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/205192cf-4d9a-4bfa-b463-48e14f335620">

**Comment by MaroofTech** [comment]
Why 2 time date and time showcasing please remove 
![Screenshot from 2023-12-27 16-28-13](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/7ffbc865-8d4e-4c17-864e-57441ed99e54)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/92a032ea-7cce-4210-90d3-a4ffb24ef76e)
Done
