### ISSUE TITLE
add msg here you can view more details once buy premium  and add btn to redirect at payment gateway, also once a cancel premium state management issue   

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1719]
![Screenshot from 2023-12-15 17-24-46](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/22ec1da7-81b0-4416-b010-d7405b7a9fdf)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/8f4cc6d1-0182-4e65-98e8-3f6b84e2055e">
Done
