### ISSUE TITLE
institute fields can't update also fix phone number fields UI

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1720]
![Screenshot from 2023-12-15 18-30-01](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/79a7351e-98c6-4ea6-b7ba-3259e31f15c7)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/ddf53f11-32c6-4085-9503-1cec3722436e">
