### ISSUE TITLE
while creating course, not allow char

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1722]
![Screenshot from 2023-12-18 16-59-44](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/b1f01c26-d346-436a-985a-bdc42870a2d2)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/af4d3e9b-b849-426c-8fe5-f6021016cc62)
Done.
