### ISSUE TITLE
Need to correct duration of course, it may be one digit

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1724]
![Screenshot from 2023-12-18 16-46-31](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/73979648-0b46-4f23-8e90-7396be099249)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/d7ce4e9d-a86e-4077-9f25-b648bef8666c)

Done
