### ISSUE TITLE
Purchase history > functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#174]
To download invoice button is not working

**Comment by SaurabhattJi** [comment]
@naveesha-vayuz @vinayak-vayuz please provide the designs for invoice page. We have to download the invoice from frontend

**Comment by pankajVayuz** [comment]
@rajasrivastava101  this pointer is depend on 
https://github.com/Anupriyabanger/Bee-Recruiter/issues/2122 this pointer.

**Comment by vinayak-vayuz** [comment]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/c2afe2a1-46ea-4076-8389-3b0d3d4b8ebf">

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/dad0672c-e48d-4784-b160-478e3a37c890)
