### ISSUE TITLE
web | jobseeker | profile | Educations  Details

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1749]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/e4748c13-f4ae-4871-92ed-257e57ac2e5b)

fix the deleting education  details  loader.

**Comment by vinayak-vayuz** [comment]
<img width="665" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/ae6f6cfe-79ab-4104-8cb3-31b50de8205b">
