### ISSUE TITLE
Web > Job seeker > Job detail

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1751]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/456c8930-3c99-4b87-985d-3e365213d73f)
Alignment issue on job detail page.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/e6b296fd-fc30-4b4e-8c39-652136d18575">
