### ISSUE TITLE
Home screen > Header > Post job > Functional > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#177]
<img width="960" alt="2023-05-02" src="https://user-images.githubusercontent.com/129847373/235616305-c75c27d8-e651-41bf-a3f4-e1ffb56d3124.png">
Post job button is already available on the home screen in right top so could be removed from the header

**Comment by vinayak-vayuz** [comment]
Removed
