### ISSUE TITLE
Web > Job Seeker > Resume Builder

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1775]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/7711ac23-ed5d-4d97-be4f-468361d0b7e2)
Add a dummy image.

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/268b45bb-e6c3-48d8-ba3f-491f60e57262)
this issue is fixed.
