### ISSUE TITLE
Web > Job seeker > Resume builder

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1776]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/52ff4d0a-b319-4d51-b301-cc1c3b7882a7)
We are taking country in the form but not showing in the resume page.

**Comment by vinayak-vayuz** [comment]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/6cee4906-0d21-4824-8f03-ce9ad85e7db5">
