### ISSUE TITLE
Web > job seeker > Resume Builder

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1777]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/c98d3954-23c6-475e-aa13-25b6e2003a22)
Page title is wrong

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/510ad4ef-f43d-4f9a-a295-30a2234277a3)

fixed
