### ISSUE TITLE
i can't see any where saved application 

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1780]
![Screenshot from 2023-12-20 15-22-13](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/3de561e0-4b15-4766-9935-02811b0a417e)
![Screenshot from 2023-12-20 15-22-10](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/1063abf6-ec55-4a31-95d3-2c074796c436)

**Comment by PrakVayuz** [comment]
Removed the save application option as discussed
