### ISSUE TITLE
If i enter wrong email in forgot password nothing happen, please show relevant message. 

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1785]
![Screenshot from 2023-12-26 16-44-21](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/286d4f5a-8702-4a62-aed7-6d257cb7b47a)

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/fb60e079-2514-433c-ba59-65e04f966a9e)
this issue is fixed.
