### ISSUE TITLE
Make premium UI more interactive also there is no any animation/celebration once i purchased premium

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1787]
![Screenshot from 2023-12-26 16-56-35](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/60b31442-bc5a-4b6e-b292-2bcd9c449d00)

**Comment by vinayak-vayuz** [comment]
<img width="408" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/eb396a53-2b21-4e3b-b137-01dc74e70d5f">
This animation has been added when someone purchases the subscription.
