### ISSUE TITLE
Make same layout as in user have data, but show dash(--) that key dos't have data

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1788]
![Screenshot from 2023-12-26 17-07-32](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/98bd4d89-3bb4-466a-953f-466b90762cd4)

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/8d548cdc-74a6-43df-96d7-32f8634eaf76)

this issue is fixed
