### ISSUE TITLE
Web > Courses / Program > Issue with dropdown in dark mode

### ISSUE THREAD

**Issue by vinayak-vayuz** [Anupriyabanger/Bee-Recruiter#1792]
<img width="196" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/bcf624d4-7e35-432c-95a0-3a259c44f55d">
Fix the dropdown in dark mode

**Comment by vinayak-vayuz** [comment]
<img width="498" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/5cdffe9e-784e-41a5-a993-03277d87f314">
Done

**Comment by rajasrivastava101** [comment]
In dark mode black color doesn't suit it well, Kindly change it.

**Comment by vinayak-vayuz** [comment]
<img width="510" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/760ea908-14e2-44d5-8cc1-d00d69053357">
Changed its color
