### ISSUE TITLE
show job count like Job Feed(9)

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1794]
![Screenshot from 2023-12-27 17-03-02](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/1f67279a-dfe2-46df-813c-a5282e29b200)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/0f73e0b8-bff7-4c65-9ae4-386855a0c15c)
Done
