### ISSUE TITLE
no use of Interest button, why interest is look like button 

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1795]
![Screenshot from 2023-12-27 17-05-10](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/659de527-752a-48b0-bc74-ea2cd857710e)

**Comment by SaurabhattJi** [comment]
Interest is coming from the backend
The hover is removed now

**Comment by MaroofTech** [comment]
@SaurabhattJi what is the use of interest here? also no sense in adding it from backend

**Comment by SaurabhattJi** [comment]
@MaroofTech sir it is coming from backend according to user search preferences and user applied on jobs
