### ISSUE TITLE
sorting not working also active filter not highlighted(removed after refresh)

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1796]
![Screenshot from 2023-12-27 17-09-11](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/b9e73eae-6f1d-4fb2-a9e9-83fee5f31b29)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/4e3f3df2-1e97-46f5-a203-fe22a471e06f)
Done sir

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-29 11-11-43](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/a613db41-c39e-4173-be51-68e8ece813c6)

**Comment by MaroofTech** [comment]
sorting still not working
