### ISSUE TITLE
experience is NAN and popup not closed after reporting post

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1799]
![Screenshot from 2023-12-27 17-13-58](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/4dbf1093-7094-4a53-9ca6-a771ac238387)
![Screenshot from 2023-12-27 17-12-29](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/b70289da-7b57-4f63-a0cf-a75ff0b2fc0d)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/dca9b33f-0641-4dca-81cd-d1e6fcfbf5db)

**Comment by MaroofTech** [comment]
insted of post write job
![Screenshot from 2024-01-03 13-47-55](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/837c3839-7660-471a-85c2-f6cb72e3c7a4)

**Comment by MaroofTech** [comment]
I can report without selecting any option
![Screenshot from 2024-01-04 17-30-46](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/acec83ec-562b-40f2-a248-bb789f56d080)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/acf119c3-c2a5-4b40-8040-d940e6bda809)
Done.
