### ISSUE TITLE
This is the Final Logo from the Client-side and the points mentioned below:

### ISSUE THREAD

**Issue by psharma1907** [Anupriyabanger/Bee-Recruiter#18]
Points Mentioned Below:
Here are some remarkd regarding the logo to be modified : 
1- R for recruiter to be capital letter.
2- The wings for the bee, one should be a small design of CV and the other one should be written (job) in a designed way.
3- The curved arrow should be removed and replaced with a thin line taking from the start of the word bee till the bee itself.

![WhatsApp Image 2023-03-07 at 12 03 39 PM](https://user-images.githubusercontent.com/123075948/223340576-83380baf-84de-40bf-9a41-afa785ae35f9.jpeg)

**Comment by Mehulna** [comment]
Done
