### ISSUE TITLE
at header profile image is coming but not at right panel in details page also from Jobs from Top Companies view/details not opening 

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1800]
![Screenshot from 2023-12-27 17-22-05](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/1dd7b95a-e843-4f25-9d01-5c622d093bbb)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/60e79d92-beee-4348-b99d-b1877d73184d)
Done.

**Comment by MaroofTech** [comment]
Once i click Jobs from Top Companies view/details, IN API dota return but loader is spinning
![Screenshot from 2024-01-03 13-45-36](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/0066fd88-ca2e-41ab-9951-4b25ed980461)
