### ISSUE TITLE
sometime Personal Details not come in edit form also add char limit and proper validation in form

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1815]
![Screenshot from 2023-12-28 10-38-16](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/78e512d7-9a1b-43a4-8558-1c53cf0996c9)
![Screenshot from 2023-12-28 10-40-50](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/6638139c-1968-4c8f-9141-1b73ed604c5c)

**Comment by MaroofTech** [comment]
I have filled all details but button is disabled
![Screenshot from 2023-12-29 11-42-56](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/f78fea80-d059-4f6c-968c-17fb826d73fe)

**Comment by MaroofTech** [comment]
Still sometime Personal Details not come
![Screenshot from 2024-01-04 17-24-47](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/d52c2e40-d8ac-4a11-8de4-6496582a3993)

**Comment by MaroofTech** [comment]
@SaurabhattJi once i refresh the page and click edit professional , loader is spinning without submitting form
![Screenshot from 2024-01-08 17-04-36](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/f8150a79-73ad-4864-b669-48cadc7109b1)

**Comment by SaurabhattJi** [comment]
Its done.
