### ISSUE TITLE
alignment issue in skill and Interest

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1818]
![Screenshot from 2023-12-28 11-21-54](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/eb225a6c-8522-49d6-a737-9136932729fd)

**Comment by vinayak-vayuz** [comment]
<img width="244" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/8fba4cdb-7435-4bef-a962-3dc1c565bdc9">

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/91a6c68e-20c4-4ae7-baa1-e580d85f516d)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/51268986-8067-4d6e-9baf-ddb425f5ae2f">

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/3a0a7d41-0d86-47c0-8516-1524a6bd24e3">
