### ISSUE TITLE
convert all tooltip

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1820]
![Screenshot from 2023-12-28 12-40-14](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/f061adf6-aa3a-4dbd-849e-be2041c39c07)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/57b8899c-2f01-4509-8cb6-2c50f5804266)
Review Required
