### ISSUE TITLE
convert in language following screen

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1821]
![Screenshot from 2023-12-28 13-03-18](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/97386b92-772d-40d3-bb95-df4df804d3a0)
![Screenshot from 2023-12-28 13-03-13](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/abfea549-87e3-4c2a-b537-2d81c2260097)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-28 13-06-42](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/021dcb9d-84e0-43f2-9f89-96ff109218ef)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-28 13-08-19](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/cbfec86b-0fe5-46c2-b67c-c6302ff69322)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-28 13-14-02](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/d8b0dbf8-ceaf-48e4-a61e-f0be71e00517)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-28 13-17-47](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/ae5e79aa-a452-4389-967e-52af8e405c1f)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-28 13-19-16](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/67deaea1-e11f-4abb-898e-6d9e88ab7137)
![Screenshot from 2023-12-28 13-19-01](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/dcf91afc-8d94-418f-b73d-aa791d24f8f3)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-28 13-20-05](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/21b1d7d5-095b-4916-adcc-539e85aebfe7)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-28 13-21-02](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/36bd4f00-bd65-4962-8fa3-63dce73c9356)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-28 13-21-43](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/3200b177-0c41-4ae5-b613-a70af0b213aa)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-28 13-22-06](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/55c70303-5695-44eb-8bc4-e788c1ecbc2f)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-28 13-22-31](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/057f7cc4-cd60-4424-a996-18cc0c847ef4)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-28 13-25-51](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/00f0c25d-51df-4dc4-9d63-9e70e589cf1c)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-28 13-27-15](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/439b18ac-7212-4f0c-a82d-f14b32a6b05d)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-28 13-28-20](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/0a45a952-e4a4-4c59-afc8-6db177814ca9)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-28 13-31-46](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/5b28418f-f415-4130-97d6-b5bdc88cf3aa)

**Comment by MaroofTech** [comment]
Tooltip
![Screenshot from 2023-12-28 13-33-04](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/c3769ccb-daa1-4f7a-a72e-b76411d18661)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-12-28 13-34-55](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/50419e53-f048-4f93-be22-b92ab3a58392)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/630f8937-39a0-4936-981a-ef98bf5dafdd">

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/867a9106-3e13-454c-9f93-4c2cee8de997">
