### ISSUE TITLE
web | job seeker | profile 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1824]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/2e2929dc-00b6-49ac-b28a-6c87a9d4e75b)

fix the model scroll

**Comment by vinayak-vayuz** [comment]
<img width="565" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/7c600c9f-ed93-40da-8511-378cd73ac8a8">
