### ISSUE TITLE
jobseeker | my resume | 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1826]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/c03733d9-4635-43cc-966a-50c5f4f7f1ac)

fixed the phone input ui

**Comment by vinayak-vayuz** [comment]
<img width="396" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/75632c3e-1f68-4189-a5c5-9b78b091e580">
Done
