### ISSUE TITLE
Once i refresh page tab highlighted(applied filter) removed 

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1833]
![Screenshot from 2024-01-03 14-30-43](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/ae68995e-4705-4f6b-9b61-1cb3da99a658)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/1c8d5b40-a77e-4229-b9fb-d8fbd956b10d)
Done.
