### ISSUE TITLE
experience and salary coming NAN even it show in details, also once i click on saved its saved but on refresh save not heighlighted

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1834]
![Screenshot from 2024-01-03 14-34-14](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/9610f0e5-6e73-4f08-bbb8-cea867896397)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/aa16a7b4-ebf0-4420-9c56-c68b6e2f37dd)
Done

**Comment by MaroofTech** [comment]
@SaurabhattJi still once i click on saved its saved but on refresh save not heighlighted

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/2241e6f6-96a3-4799-8404-09f3d2a17e60)
Done.
