### ISSUE TITLE
show the count of saved and applied job

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1835]
![Screenshot from 2024-01-03 14-37-55](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/48345d2f-c12e-4bbb-be88-6cf6da2d120a)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/4557d8db-3ff8-4062-9253-447b7ad91da4)
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/67e16496-67ae-4840-9965-2018f6ecce74)
Done
