### ISSUE TITLE
apply job popup is different at saved job from job feed page

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1836]

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/ae2bca34-9462-4f83-a450-240b3bcaabd2)
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/897b286d-2aa5-464d-b982-c7f63b2e1a5e)
Its same
