### ISSUE TITLE
apply button not highlighted at save job even i selected resume 

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1837]
![Screenshot from 2024-01-03 14-43-01](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/a17481d8-52cf-427a-88d9-faa2fd8e68a3)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/4db7af7d-dc2a-4f1c-9c41-cf40a25c2698)
Questions are required to fill. This is a old job so there are no questions. But after the UAT of employer minimum 1 question is required.

**Comment by MaroofTech** [comment]
@SaurabhattJi Once i apply withdraw not come also modal not closed

**Comment by SaurabhattJi** [comment]
Done sir it is working fine in every field
