### ISSUE TITLE
at saved job experience is coming NAN but in details its coming also saved not highlighted at details page but its saved

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1838]
![Screenshot from 2024-01-03 14-47-16](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/66099506-28e2-45d5-8f02-8dadf619e54b)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/49ffaac5-6a05-4206-b92c-cee609e09e73)
done
