### ISSUE TITLE
There is filter at saved job but not working

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1839]
![Screenshot from 2024-01-03 14-53-11](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/a9eaec5e-bb03-45d7-ac4c-d75c9cd4d374)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/60ac0e68-282f-4ca6-9e90-2ccd750fdb07)
In the figma design there is no filters section for the saved jobs. So it is removed from the web also
