### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1841]
![Screenshot from 2024-01-03 15-03-38](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/78da49c8-67e6-4e7e-a08e-8547086a22b4)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/202c7eab-b6bc-4ea9-b29a-96ea5b88405c)
Done
