### ISSUE TITLE
correct the icon of duration and Scholarship

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1842]
![Screenshot from 2024-01-03 15-07-41](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/e47e9df7-dc2e-469a-bfae-0f3389e59e4a)

**Comment by vinayak-vayuz** [comment]
<img width="872" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a919f656-3906-4901-9d2e-d2a9a8d17fd5">
