### ISSUE TITLE
correct modal UI and btn alignment

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1843]
![Screenshot from 2024-01-03 15-10-02](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/923c479e-a087-453e-beca-3d296e86b1a1)

**Comment by vinayak-vayuz** [comment]
<img width="561" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/bdb2465a-6b87-4bb0-8774-ad71cc3abf3c">
