### ISSUE TITLE
star and text overlapping

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1844]
![Screenshot from 2024-01-03 15-11-09](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/4984d2c1-8f4d-465d-929f-d7e578711152)

**Comment by vinayak-vayuz** [comment]
<img width="428" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/d17cae50-f9bd-458d-87af-6d18fb0ab2f1">
Added a function in the name, now It'll split it after the first white space
