### ISSUE TITLE
Check is notification page is static ?

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1846]
![Screenshot from 2024-01-03 15-16-44](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/83add704-11d7-415d-b56c-e58136580c3a)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/67da1e66-3403-4a09-b54c-af6eb92dda5e)
Its dynamic sir
