### ISSUE TITLE
web | jobseeker | profile 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1859]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/dbeafb2b-1711-4093-9e8e-4864f47bae96)

fix this ui

**Comment by vinayak-vayuz** [comment]
<img width="342" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f2b7c342-0951-4a01-995f-bf144b72cdd3">
