### ISSUE TITLE
Hobby , language and technical skill not auto fill when i click autofill checkbox, also when i fill details not autofill these details  

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1860]
![Screenshot from 2024-01-05 11-33-20](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/da5f4d20-462f-4f38-a0e4-0dc7184a3b0f)

**Comment by MaroofTech** [comment]
![Screenshot from 2024-01-05 12-14-12](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/a633e90b-17e2-4669-8cf8-cf82483b1bd7)

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/d3e09e29-7b61-46c1-a301-752022bc944c)
this issue is fixed.
