### ISSUE TITLE
Facebook url shows invalid even it valid also linkedin and fb url not updated in template

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1863]
![Screenshot from 2024-01-05 12-37-30](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/9b755401-8eca-4e8d-9eae-329c0a656c1b)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/df7fa582-dba9-4784-9f98-79d83a556490)
Done
