### ISSUE TITLE
Web > Institute > Draft Course > Course Detail

### ISSUE THREAD

**Issue by vinayak-vayuz** [Anupriyabanger/Bee-Recruiter#1864]
<img width="954" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0ac6e9d6-8455-4cc6-8053-9f2119f63e31">

Some of the fields are missing

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/37587d10-e3d2-4499-a4f3-c1369c1060e7)
Done
