### ISSUE TITLE
Course details language issue

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1865]
![Screenshot from 2024-01-08 17-39-44](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/92bd07d9-72d8-409e-9159-fcac068e7bb4)

**Comment by MaroofTech** [comment]
![Screenshot from 2024-01-08 17-41-10](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/9cd1c137-56a1-469f-8e05-09ec6b6e9893)

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/29a67355-d7e3-4b10-8422-9052cb9d714b)
 this is done

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/8ca36170-cf9d-4d59-bf5e-ba1e79e4d2d8)

**Comment by MaroofTech** [comment]
![Screenshot from 2024-01-10 14-40-30](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/a8fdc5d3-c9b4-4ab1-9bcd-da42fa9d5504)

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/b79509f7-52a3-407c-889d-a730dd150450)
