### ISSUE TITLE
jobseekers language issues

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1866]
![Screenshot from 2024-01-08 17-42-49](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/62c005b4-d354-4146-ae8b-d85a9628f3d2)

**Comment by MaroofTech** [comment]
![Screenshot from 2024-01-08 17-44-58](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/7db9f7d1-f5d2-4a73-942d-1cb1f83d4950)

**Comment by MaroofTech** [comment]
![Screenshot from 2024-01-08 18-08-46](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/545809ec-c670-4945-8285-5ccb34abc2b6)

**Comment by MaroofTech** [comment]
![Screenshot from 2024-01-08 18-12-27](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/844c8d69-0a30-455e-89d3-386c17c4ece1)

**Comment by MaroofTech** [comment]
All tooltip of this page
![Screenshot from 2024-01-08 18-13-40](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/a04b83ee-2245-4c72-b43c-a615752b5786)

**Comment by MaroofTech** [comment]
![Screenshot from 2024-01-08 18-14-41](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/8aa181dc-6305-4aec-b514-d871dba855fa)

**Comment by MaroofTech** [comment]
![Screenshot from 2024-01-08 18-15-02](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/38351900-7189-4a16-8331-00e1776b83ff)

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/f11dc52d-7ee2-4793-85b3-219418a40cfd)
job feed done

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/46ba5daa-9312-4568-8b57-d2d26a425900)
profile section done

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/39c67a70-ee09-4b98-ba0c-5b9c2e88e07b)
saved jobs languages done

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/f395fcd9-18cb-4b68-82d5-185ad04300ba)
applied jobs language done

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/686865da-6394-4d1f-bb6f-e363dbccb5a3)

card language is done

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/f2c9f5d1-d124-42d6-8745-1b2ee9478e3f)

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/eb743c10-77ce-4a84-b8cd-379e31507fe9)
Under the courses section language isn't implemented properly, kindly check.

**Comment by pankajVayuz** [comment]
Whatever language is not changing is user input, it will be shown in whatever language the user enters.
