### ISSUE TITLE
no validation in email fields

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1867]
![Screenshot from 2024-01-09 11-16-24](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/7b9f4718-f18e-40e4-981f-eab4cf102f8d)

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/69f6f9b8-9fcc-444c-b6b0-4d914e452cc8)
this issue is fixed
