### ISSUE TITLE
Application rate not changed even i have two application on my job

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1870]
![Screenshot from 2024-01-09 13-00-35](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/fbc73426-a8f6-4b49-9fdd-f899c12917f1)
![Screenshot from 2024-01-09 13-00-40](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/2f4b0db9-dade-4d7c-b83d-9b8ac47015be)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/b2bbe466-a72f-48ac-ae53-24377e7aabe8)
Done
