### ISSUE TITLE
Daily application not coming, even today we have two application received

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1871]
![Screenshot from 2024-01-09 13-05-16](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/543513f4-f19e-49a9-a5a1-ad9677c34412)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/af5960a7-fc95-4d3e-80be-fbd65bf0a1c6)
Done
