### ISSUE TITLE
web | jobseeker | appliedjobs

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1874]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/e88992c6-9996-467e-9ad4-5c2995ecaa8d)
fix the card save button . when title is too long overlap in the save button in RTL.

**Comment by vinayak-vayuz** [comment]
<img width="939" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/22c3f033-6259-4835-91a9-2636a690a799">
Done

**Comment by vinayak-vayuz** [comment]
Done
