### ISSUE TITLE
web | jobseeker | saved job |

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#1876]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/f4653321-e54d-422a-b930-34cdaf0c7713)
add no data page .

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/d7c6c94e-18a0-45df-b2f8-c1be6152fcd3)
Done
