### ISSUE TITLE
App > Dashboard

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1894]
If there are no interview scheduled than add a new button to schedule an interview like web
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/a8f15043-2fe8-4b91-8a55-91371c1c5f50)
Or instead of showing 0 show No interview scheduled.
like this
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/5af8402d-7857-48a7-b739-a8a27a393d36)

**Comment by kaviraj-thakurr** [comment]
done
