### ISSUE TITLE
App > Employer > Sidebar

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#1897]
not able to redirect after clicking on the Buy button.

**Comment by kaviraj-thakurr** [comment]
its not Buy button now its Upgrade Button now its working on Dashboard

**Comment by milivayuz** [comment]
<img width="127" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/3577d84a-c113-4704-8d93-c01b1b505fe4">

On clicking continue with free package i should be redirected to the dashboard
