### ISSUE TITLE
Admin> Job seeker> Apply for job> Save and cancel options should be sticky

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/Bee-Recruiter#190]
![image](https://user-images.githubusercontent.com/109590553/236137641-4e32d34d-595a-4381-9eda-f9f38b60931c.png)
![image](https://user-images.githubusercontent.com/109590553/236137789-7c38fd83-e703-477a-9aec-0f2c6a49205c.png)

**Comment by vinayak-vayuz** [comment]
<img width="377" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/db0ab011-5be3-4c96-899c-8dca1e15e866">

**Comment by rajasrivastava101** [comment]
Please fix it.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a1ec3e66-240a-4eda-a0ef-97ecd60628ae)

**Comment by vinayak-vayuz** [comment]
It's sticky.
