### ISSUE TITLE
App > Employer > Functional > Buy Premium 

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#1907]
![WhatsApp Image 2024-01-15 at 2 16 14 PM](https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/7f86ffa9-f35a-4f2f-b5b8-c84c3c9e68ae)

In buy premium section slider is mentioned but it is not working

**Comment by kaviraj-thakurr** [comment]
Need Clarity...You see the dots over the image that is static
