### ISSUE TITLE
App > Employer > Functional > My Job

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#1908]
![WhatsApp Image 2024-01-15 at 2 23 12 PM](https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/e0f7ede7-4756-42ab-854f-67586538b96d)

List in my job >> Filter >> Ascending and Descending button and doing the opposite function

**Comment by milivayuz** [comment]
Ascending : Oldest first Newest Last
Descending: Newest First Oldest Last

**Comment by kaviraj-thakurr** [comment]
<img width="948" alt="Ascending" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/8c5a17cf-d9fe-41c5-b581-e073ce088a52">
<img width="917" alt="Descending" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/76ffad87-2492-4911-95e4-bc4586cc7151">

https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/21454367-20d3-4574-bc30-974da5445b6a
