### ISSUE TITLE
App > Employer > Functional > Dashboard > Daily Application

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#1911]
![WhatsApp Image 2024-01-15 at 3 13 31 PM](https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/10df0a79-582c-4879-9d4a-0ae3dcc89b3d)

Daily Application Graph error

**Comment by kaviraj-thakurr** [comment]
<img width="925" alt="daily apploication" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/482b7130-853f-4e5c-b8ff-eab619179889">
![1000384142](https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/97ce060b-8e66-4780-9724-3fe021ec0f35)
