### ISSUE TITLE
App > Employer > UI > Dashboard > Graph

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#1913]
![WhatsApp Image 2024-01-15 at 3 32 39 PM](https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/e40973c5-eada-4c99-b17f-812f069cf602)

Today's view on all jobs and Daily Applications 's count on graph are not visibile clearly

**Comment by kaviraj-thakurr** [comment]
![1000384033](https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/515b1404-5db3-4d29-8973-2df4135a29db)
