### ISSUE TITLE
App >  Employer > UI > Functional > My Jobs

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#1918]
<img width="959" alt="1" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/62b6d6bd-0b73-48b1-9125-47ff8cf1c421">
![WhatsApp Image 2024-01-15 at 3 59 29 PM](https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/3146a800-9d54-4e31-b972-76fc85da81c7)

My Jobs List > Vertical Ellipsis > Manage Jobs 
Total Interview count ( title inside the card) and the analytics: incorrect

**Comment by kaviraj-thakurr** [comment]
check with web @milivayuz count is perfect according to web..,.. but i changed graph buttons applications to Application Received and Interviews Schedule

**Comment by milivayuz** [comment]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/8961eba6-0bfc-4dfe-baed-b9d06e0b3682">

<img width="125" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/4abbae92-9b5e-4f36-beb3-50e71c6d1a2c">

Analytics are different

**Comment by kaviraj-thakurr** [comment]
it just because interview scheduled by user soo thats why it showing

**Comment by milivayuz** [comment]
Issue remains the same analytics is different

**Comment by kaviraj-thakurr** [comment]
<img width="959" alt="web bee" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/29d2fc22-0fcb-4707-beaf-1a8a231196ef">
<img width="952" alt="web beee ana" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/f3438c0f-f59b-42d9-b47f-882615b0ae5c">
![1000384028](https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/00d75029-11e7-441d-baad-377a84a6a061)
![1000384029](https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/9fc44357-e2e1-469d-b202-30f3ee4515f2)

**Comment by kaviraj-thakurr** [comment]
![1000384028](https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/5f4639d6-0bba-463d-9dd1-3b88cf04afe0)
![1000384029](https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/e59a066c-9d13-4e93-8822-a24712ba00dc)

**Comment by kaviraj-thakurr** [comment]
Please check
