### ISSUE TITLE
App >  Functional > Employer >  My Jobs

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#1919]
![WhatsApp Image 2024-01-15 at 3 59 29 PM](https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/2e2639b9-753d-4b4d-aced-3486f0106b4c)

My Jobs Card >  Manage Jobs : Graph not visible

**Comment by milivayuz** [comment]
Still, no graph is visible on today's filter. Do take reference from the website

**Comment by kaviraj-thakurr** [comment]
![Uploading 1000384359.jpg…]()

**Comment by kaviraj-thakurr** [comment]
![1000384359](https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/c0af14fd-4078-4f4d-8927-737346e8f238)
