### ISSUE TITLE
Admin> Action icon not visible

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/Bee-Recruiter#192]
![image](https://user-images.githubusercontent.com/109590553/236138270-4a02a761-940d-4bd4-808b-4307b1c3c058.png)

**Comment by vinayak-vayuz** [comment]
<img width="120" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/81f7050d-ef73-4988-a958-51df684c52ed">
Done
