### ISSUE TITLE
Web > Job Seeker > Setting > URL

### ISSUE THREAD

**Issue by vinayak-vayuz** [Anupriyabanger/Bee-Recruiter#1934]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/adeb67c3-aba6-4e4c-9433-cc2d02079731">

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/889e0282-f855-40c7-919c-205d856da0f2)

**Comment by vinayak-vayuz** [comment]
- [ ] FIx the highlights not working sometime
- [ ] Change the url to - based naming instead of camelCase

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/33705c73-db7b-4722-95e9-8f6bb0d3d13c)
