### ISSUE TITLE
Web > Jobseeker > Homepage > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1938]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/84576aa3-2b95-4393-9796-25a8682fbe2a)
These two different text should visible as separated.

**Comment by vinayak-vayuz** [comment]
<img width="306" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/2e38046d-0baa-4e82-ae7c-f5005f1e1656">
I've increased the gaps between these two sections.
