### ISSUE TITLE
App >Employer > UI > CV Management 

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#1947]
![WhatsApp Image 2024-01-22 at 4 04 37 PM](https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/ab81c681-d9ca-4093-a7a9-ce51989a9c39)

In resume view, skills are not showing in correct way.

**Comment by milivayuz** [comment]
Add skills in a tag format

**Comment by kaviraj-thakurr** [comment]
I have check with web skills already in tags
