### ISSUE TITLE
App > Employer > UI > CV Management

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#1954]
<img width="958" alt="Screenshot 2024-01-23 103756" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/b0e95f3c-3508-4c77-ac12-399177bcbd39">
![WhatsApp Image 2024-01-23 at 10 38 25 AM](https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/a1412a5d-6846-4cb6-a704-70ecef768baa)

Filters are different.

**Comment by milivayuz** [comment]
Add custom range as well

**Comment by milivayuz** [comment]
Custom Range is not working
Also remove the check box in front of custom range

**Comment by milivayuz** [comment]
custom range and count after CV management is not synced
<img width="130" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/9b675002-a958-4428-bbdc-775cb0d8e668">

**Comment by kaviraj-thakurr** [comment]
check now working @milivayuz

**Comment by milivayuz** [comment]
<img width="122" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/347ada33-9409-4890-87cf-909a25207282">
issue is still not resolved

**Comment by kaviraj-thakurr** [comment]
API issue
