### ISSUE TITLE
App > Employer > Functionality > CV Management

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#1955]
![WhatsApp Image 2024-01-23 at 10 58 23 AM](https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/d9e746fe-5d09-4f59-8ec1-273a7a6291e4)

Buy Premium button is not working

**Comment by ujjwalsharma2** [comment]
was removed in a previous GitHub issue
