### ISSUE TITLE
App> UI > Sign Up

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#1966]
![WhatsApp Image 2024-01-24 at 2 05 46 PM](https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/1eb710b9-f7bd-47a3-bb73-f2a4f782b9ae)
Instead of candidate, show it as job seeker

**Comment by kaviraj-thakurr** [comment]
fixed
