### ISSUE TITLE
Web > Jobseeker > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1967]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/9e12086c-0dea-48c8-8d29-42d4a478e629)
[](URL)
Kindly check the difference in the toggle UI.
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/d8197653-a1db-4701-9f69-e63c0b83dd0f)

**Comment by vinayak-vayuz** [comment]
<img width="275" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0983f8c3-9758-4c50-89e3-b03275dfeb1a">
<img width="272" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/17025cd3-3606-4006-949c-7d27218f0412">
