### ISSUE TITLE
Web > Jobseeker > Job feed

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1968]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/ed6f0f89-1c1b-417a-8c7d-b91925daacff)
I searched the keyword developer, but different results came out of another tran keyword developer.

**Comment by SaurabhattJi** [comment]
because in the job's name the developer is there but for better UI it is not showing. In some job's job description developer keyword it there so that's why these jobs are reflecting.
