### ISSUE TITLE
Web > Jobseeker > Job feed > UI

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1969]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/b00fdcba-6521-4858-a118-b5a456511d1b)
Kindly change the UI of the clear all filter.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/747968ab-c42c-4fea-aff4-97153ce9aed2">
