### ISSUE TITLE
Web > Jobseeker > Job feed > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#1974]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/abcf37f1-57e6-44ff-ba58-10358d540738)
Saved functionality is overlapping.

**Comment by vinayak-vayuz** [comment]
<img width="766" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/1fe16008-caee-4440-8bee-050f650517dc">
It shouldn't overlap now
