### ISSUE TITLE
App > Employer > UI > Post Job

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#1982]
![WhatsApp Image 2024-01-29 at 11 45 52 AM](https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/14d0c306-ea60-4633-af2a-1ab2252377a6)

Add drop-down icons to select country, select nationality and select religion

**Comment by kaviraj-thakurr** [comment]
fixed
