### ISSUE TITLE
App > Employer > Functional > My Job

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#1995]
<img width="124" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/35da4b20-08a6-4c48-8d2b-62e316268036">

Applied filter is not visible in search bar neither somewhere else it is mentioned that a filter is applied

**Comment by kaviraj-thakurr** [comment]
give some clarity in this @milivayuz  check with web for this pointer and lemme know what should i do in this...

**Comment by kaviraj-thakurr** [comment]
in search bar hint is search applicant.. Is it necessary
