### ISSUE TITLE
Admin> Package> Package description input box should not be so small

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/Bee-Recruiter#200]
![image](https://user-images.githubusercontent.com/109590553/236763593-88850307-4b7e-4af9-b721-2a795621056f.png)

**Comment by rajasrivastava101** [comment]
Issue not resolved

**Comment by vinayak-vayuz** [comment]
<img width="338" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/5017ee3f-4205-4433-81e6-37119915afbc">
Issue was already resolved but I think the code was not live.
