### ISSUE TITLE
App > Functional > Jobseeker > Profile

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2002]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/ba15dca3-e3ee-45a8-a661-a6c4d9464637">
<img width="128" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/42dedeb0-f62c-41ed-a20d-340e6936afe4">

Add pending action option

**Comment by Sujayvayuz07** [comment]
@milivayuz  there is no figma design for this

**Comment by milivayuz** [comment]
@naveesha-vayuz Kindly check
