### ISSUE TITLE
App > JobSeeker > Functional > Profile

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2004]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/0623dc27-1b05-4175-8192-ffab6a673387">

Add the hobby section in the app as well

**Comment by Sujayvayuz07** [comment]
@milivayuz  there is no design in figma for Hobby .

**Comment by milivayuz** [comment]
@naveesha-vayuz
