### ISSUE TITLE
Web > Job Seeker > Functional > Profile

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2006]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/cc814315-c66c-4710-92cb-ea535fedae71">

Add projects section in the profile

**Comment by pankajVayuz** [comment]
@vinayak-vayuz   i need this

**Comment by vinayak-vayuz** [comment]
<img width="654" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/9b0f4e73-b3e0-44ad-8b99-4e9824240cb3">
<img width="553" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/531eac72-6b35-47e8-a2f9-33aec9275450">
<img width="492" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/36c3599a-e377-48a8-a510-86c696c72b8c">

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/c142011f-d851-4388-a86e-f8efadc30309)
done

**Comment by milivayuz** [comment]
<img width="936" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/593a8cfc-43f2-4470-950a-edf8efaee051">

Shift the edit button on right like it is in other section like certificate

**Comment by vinayak-vayuz** [comment]
<img width="586" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/fdecce79-7912-43b9-8059-6ac20a286673">
