### ISSUE TITLE
Web > Job Seeker > UI > Profile

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2017]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/388cf087-83f8-42e9-8f20-4136625173fd">

Change Text in Add Media from: 'Add external documents and photo' to 'Add external documents, photos, videos and presentation'

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/aa908e7d-89ba-42c7-a5e5-7ddd11767b1f)
done
