### ISSUE TITLE
Web > Employer > UI

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2026]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/7c1127cb-1324-469b-b1eb-74921966c427">

Texts are overlapping in the salary range

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/705942bf-d0f3-4c72-8a9b-091be3b7eb45)
