### ISSUE TITLE
Web > Employer > Functional > Profile

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2064]
<img width="955" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/64775667-00ca-4465-932f-9e1fe3bae6fe">
Changed Profile photo is not showing up after refreshing the page

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/f2849e48-d43b-4d55-8d48-e5c91e1182d8)
done
