### ISSUE TITLE
App > Employer > UI > Profile

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2069]
<img width="130" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/5ee233c9-b9db-4c13-8e6a-7bbc99d9ebb2">

Remove 1 banking option

**Comment by ujjwalsharma2** [comment]
This list is coming from an api response. Hence it is an API issue (Same issue on web)
