### ISSUE TITLE
Web > Employer > UI > Profile

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2070]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/735f9a40-0ffc-4f3f-a90c-07d84cfc9155">

Remove 1 option for banking

**Comment by milivayuz** [comment]
@pankajVayuz Kindly check the issue with the api

**Comment by PrakVayuz** [comment]
the data is coming from backend and that that can not be handled on frontend
