### ISSUE TITLE
Web > Employer > UI > Profile

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2075]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/af162d5a-f912-4067-a810-1fe3f40393a5">

Remove the drop-down icon from company-name

**Comment by vinayak-vayuz** [comment]
Company Name is coming from API, the dropdown cannot be changed.
