### ISSUE TITLE
Web > Employer > UI > Subscription & Payment

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2077]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/9ac247ba-4c0f-4245-ae18-9d7e2aebcce8">

Add padding-bottom after view purchase history for text and icon both

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b6c90bac-e0cd-41d0-b01f-e8967e9bd9f5">
