### ISSUE TITLE
Web > Employer > UI > Dashboard

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2078]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/e29f5181-f290-4de8-9562-5b1bc2fedfd2">

Reduce gap between illustration and text

**Comment by vinayak-vayuz** [comment]
<img width="815" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/160d1517-717d-496e-af9f-ec667f623b7f">
