### ISSUE TITLE
Web > Employer > UI > My Job

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2079]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/a9c529fe-4125-4807-aae5-06b7cab541f4">

Change the job description color. Text is not visible in dark mode.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/978d426a-9d22-4a54-b2ed-97153a3b04af">
