### ISSUE TITLE
Sign In > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#208]
<img width="960" alt="2023-05-08 (7)" src="https://user-images.githubusercontent.com/129847373/236775961-20f0c8de-d2fd-47c6-9e0f-261705f18870.png">
OTP should be visible at a same place rather changing.

**Comment by vinayak-vayuz** [comment]
OTP will not show to the end user. OTP will be sent by email/SMS. The integration is not done yet.
