### ISSUE TITLE
Web > Employer > UI > ATS

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2080]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/606559ff-3e81-46ef-956e-f2d5965cbd6a">

Add another tag All, where all the applications will be visible and in the applied tag only those applications will be visible whose status is applied

**Comment by vinayak-vayuz** [comment]
This design has been changed to a new one
