### ISSUE TITLE
Web > Employer > UI > Scheduled Interview

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2084]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/d1006041-acb0-48f2-ab3f-36b8ee9dd9bb">

Mode of interview: Text overflowing

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/dfc23e46-bd08-4b4f-92e1-fd33b703c9f7">
