### ISSUE TITLE
Web > Employer > UI > Calendar

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2085]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/f6c75410-13e7-4c51-8466-6ca5dec869fa">

Increase left margin in calendar box on left body

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/c4fb98eb-de27-467c-aa18-5554b51cef54">
