### ISSUE TITLE
Web > Employer > UI > Scheduled Interview

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2086]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/2b63a8cc-71b2-4cf5-b929-e194ee49f19d">

Add a back button whenever i am landing on the calendar from the scheduled interview button

**Comment by vinayak-vayuz** [comment]
After scheduling an interview from ATS, the redirection is not working please fix it @PrakVayuz

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/48f5e395-17a7-4d42-9e79-e5c740352ba0)
