### ISSUE TITLE
Web > Employer > UI > My Calendar

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2087]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/c2c2f568-32d9-4f2d-8c7f-8654ac211344">

Change text color/ hover effect color. Texts are not visible on hover in dark mode

**Comment by vinayak-vayuz** [comment]
added the primary color of the project on hover

<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/32ff3d38-00b1-4bb2-9328-598003a9792b">
