### ISSUE TITLE
Web > Employer > UI > My Calendar

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2088]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/7da61791-d2f3-42e2-a9b5-02df3cdae7ea">

Add navigation bar

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/7a0e1282-18da-45e0-8ee8-a2656261258a">
It's there
