### ISSUE TITLE
Web > Employer > Functional > My Calendar

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2089]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/c8007c5a-90a0-4bdb-b685-cab9e7f2ea41">

Reschedule Interview is not working. Updated details are not saving

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/dd8618f4-ee42-4aaa-a53f-aef4556e9e0b)

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/cca0ffa3-72c3-461e-af19-34bdf84dc772)

**Comment by milivayuz** [comment]
Issue is not resolved
