### ISSUE TITLE
Home screen > My jobs > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#209]
<img width="960" alt="2023-05-08 (8)" src="https://user-images.githubusercontent.com/129847373/236776752-f2cb3515-2329-4ef3-b432-f7ee69b8cc49.png">
Add job illustrations if data is not there.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0379ff0f-4091-44cc-87cc-01fcd0bd9be1)
Done
