### ISSUE TITLE
Web > Employer > UI > Functional > ATS

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2091]
<img width="957" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/635d39fd-76ae-4894-9d23-be59379a0ff0">

<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/7f210426-531e-4a7e-8c94-9b9a68d84289">

CV Management and ATS should have the same UI. Follow CV Management Drop- down UI

**Comment by pankajVayuz** [comment]
@milivayuz  both are not same please check figma.
