### ISSUE TITLE
Web > Employer > Functional > Profile

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2093]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/32166fbc-65ee-4586-a10b-51288ac24024">

Drop down of the offered role is not working

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/7708b5e7-3843-4a7b-a6ee-274ffb210379)
done
