### ISSUE TITLE
Web > Employer > Functional > Dashboard

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2095]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/44e84eac-41c2-44d9-b295-b4928128f5e4">

Scheduled Interview is not visible under upcoming interview

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/5cec0e6e-6478-479f-afa3-cf4e41a186ad)
