### ISSUE TITLE
App > Institute > Functional > My Courses

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2110]
<img width="127" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/1de2468d-13ee-412f-8d6e-a3aa9faf39f4">

Add a filter in the search bar. The filter will have the following down drop:
<img width="185" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/01366f01-07bf-4afe-99da-d42af3f1d415">

**Comment by kaviraj-thakurr** [comment]
![1000388785](https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/46990c98-e8aa-472a-98db-600cefe4d40a)
