### ISSUE TITLE
App > Institute > UI > My Courses

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2111]
<img width="131" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/87d0b0b2-a48a-4473-8480-f3ecbbb0b879">

Change the filter font size( view, delete, change status manage course)

**Comment by kaviraj-thakurr** [comment]
![1000388786](https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/2f3ac366-7944-462a-9206-9d7fb9f1b306)
