### ISSUE TITLE
Web | Employer | my job | ats 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#2121]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/f31c6907-65c0-4827-b0c6-ea4d911f3b5d)

@vinayak-vayuz  fix this load more button  ui and card ui

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/4e9a3861-bebf-4890-8634-bb35a0c6851f">
