### ISSUE TITLE
Admin> Job management> Remove Arrows 

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/Bee-Recruiter#214]
![image](https://user-images.githubusercontent.com/109590553/236803570-b997ebbd-e1b3-4c81-b32c-6150dc31cc7d.png)

**Comment by vinayak-vayuz** [comment]
Removed

**Comment by rajasrivastava101** [comment]
Its not resolved yet.

**Comment by vinayak-vayuz** [comment]
<img width="718" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/2cf755bb-00d5-4e95-8b91-47abfe5b5f3b">
It has been removed a long time ago.
