### ISSUE TITLE
App > Employer >UI> My Jobs

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2169]
<img width="113" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/6bee36fd-c77f-44ca-8a50-141812c4b24a">
Remove deleted jobs from the list

**Comment by ujjwalsharma2** [comment]
added this filter.

**Comment by milivayuz** [comment]
remove it add it to the menu

**Comment by kaviraj-thakurr** [comment]
fixed

**Comment by milivayuz** [comment]
it is still not fixed

**Comment by kaviraj-thakurr** [comment]
check properly @milivayuz 
![1000378640](https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/dbac99dc-4459-4e62-9c56-dd37774776ee)

**Comment by milivayuz** [comment]
Add deleted jobs  to side menu as well
