### ISSUE TITLE
App > Employer > Functional> My Jobs

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2170]
<img width="115" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/a7225ee3-c1a3-468f-848b-28eeffa6bb7e">
Add deleted jobs in the list

**Comment by ujjwalsharma2** [comment]
This can be found in Employer model -> My Jobs -> filter(in the search bar) -> deleted jobs @milivayuz

**Comment by milivayuz** [comment]
Add it in the side bar
