### ISSUE TITLE
App > Employer > Fuctional > Resume

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2173]
<img width="114" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/116e2f1a-8d28-484b-8316-63b00fdc71d5">
Profile photo is not visible while it is visible on website

**Comment by ujjwalsharma2** [comment]
Looks like the image on mark is the default user image. For other resumes the profile photo is visible.
