### ISSUE TITLE
Web > Employer > Functional > My Jobs

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2204]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/4dad22ac-3d8e-47d1-8b1e-8994417807dc">
Add a schedule an interview button when no interview is scheduled.

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/b926da89-9630-4006-a7ee-a548ddc97473)
