### ISSUE TITLE
Web > Employer > Functional > My Calendar

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2208]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/84a45e69-9cd1-488b-ae9c-34a288f976eb">

Add a schedule an interview button when no interview is scheduled

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/821f20d3-42ad-442d-a4be-ed8bc3d68129)

**Comment by milivayuz** [comment]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/ede6f5c1-5270-4394-96ee-2187ef130f75">

Button is still not showing up

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/35a35c36-789d-44dc-8780-d65646c14ae8)
