### ISSUE TITLE
Employer list>Name >

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#222]
here need name of representative and his delegation in the company

**Comment by rajasrivastava101** [comment]
In the employer listing view , need to add the name of representative and his delegation of the company.

**Comment by vinayak-vayuz** [comment]
<img width="196" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0485307b-6152-4e2d-aaa3-a1f6b54c5f3b">
Added
