### ISSUE TITLE
Web > Institute >Functional> Course/Program 

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2221]
<img width="958" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/dfa98850-8717-4536-9cbb-a695047081d5">

The back button should navigate to all instead of tracing every action

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/a91348fa-b062-41e8-98f9-0ba7e2fc94e4)
