### ISSUE TITLE
Web> institute > UI > Course

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2225]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/42a30da1-641c-4956-b922-e049b2965c4d">

The drafted job should not have any active/inactive tag

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/dc38bf4f-d042-456a-89d0-5a071eed3874">
