### ISSUE TITLE
Employer list>see details>

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#223]
When we click to see details there is no Easy button to back

**Comment by rajasrivastava101** [comment]
Need to add the back button as the previous comment.

**Comment by vinayak-vayuz** [comment]
<img width="73" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/ddde432c-b1f9-434e-aca5-89bf6a4e3222">
Added

**Comment by vinayak-vayuz** [comment]
Added back button on header
