### ISSUE TITLE
Web | homepage | job section

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#2239]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/4397c624-6eac-4833-86c1-4ede9b53ed81)
fix this issue .

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/82f3c7d9-5bee-4e22-9bae-d93d3272d050">
