### ISSUE TITLE
web | jobseeker | course feed | 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#2243]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/dc28b7ce-3515-44f1-8fdf-090f4dbe4eeb)
this category fix under in dropdown.

**Comment by vinayak-vayuz** [comment]
<img width="306" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/bb1a3939-1c90-4d53-bb57-fc62a2535244">

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/e9a5070b-d002-46b0-b1d0-b2362f5f523c)
