### ISSUE TITLE
web | jobseeker | course feed 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#2244]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/1637e54c-58aa-44d4-b8b2-c5850252352f)
 we should under course card category button is clickable.

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/811c354f-b7ec-43d7-9345-cf9bbc0076e8)
