### ISSUE TITLE
web | employer | dashboard | 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#2245]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/3e7c2368-99a3-48d0-b447-dc9ac7a4e260)
when first time visit this page and not post any job then not show the side bar  card. and add post job illustration.

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/3f23b76e-f32d-42e1-a43b-34dd0d415893)
