### ISSUE TITLE
web | employer | ats 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#2246]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/2fb9f2cf-7d41-49c8-89b2-965bc2ed6dfa)
add the  schedule interview button in under ats card when show in interview card section .

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/401a8188-b1c6-4c53-aeb3-d8a70e8758b2)
