### ISSUE TITLE
web | employer | ats

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#2247]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/07807d1b-c3b3-442a-a2fc-c8e7b7392651)
fix the ui when any section card is no available.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f6ece9b5-6b91-419a-9153-fe77b9a2c257">
