### ISSUE TITLE
Web | employer | job details page 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#2248]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/349cc189-0883-4844-ae1f-ab02ec7c920d)
fix the font width in this page .

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/90f213e3-e7e7-4ce7-bbda-f473ff2fdb83)
