### ISSUE TITLE
Web > Institute > UI> Application Management

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2253]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/f658f282-0e86-4421-9f29-1dbad8bf69da">

Status and filter should have the same options

**Comment by vinayak-vayuz** [comment]
<img width="355" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/fc9071d2-5736-4dc2-84db-9f2819e47628">

**Comment by milivayuz** [comment]
Screening is not in the filter

**Comment by vinayak-vayuz** [comment]
<img width="353" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/c4813b64-48da-4dea-aee4-6975b9cf2585">
