### ISSUE TITLE
Web > Institute > UI> Application Management

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2254]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/cbd7a225-3237-477e-8dee-530effcf1a49">

Align skills and hobbies

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/25c28b47-3cb7-4d8c-8767-ee67e1a44b80)
