### ISSUE TITLE
Web > Employer > Post Job > Form UI 

### ISSUE THREAD

**Issue by PrakVayuz** [Anupriyabanger/Bee-Recruiter#2258]
Change the Form UI
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/977c7c91-a167-4c14-a763-0b32263e9971)

**Comment by vinayak-vayuz** [comment]
It can not be changed as the fields have space according to the data inside that input field. i.e. Nationality require more space than other fields in the row.
