### ISSUE TITLE
Web > Employer > Post Job > UI

### ISSUE THREAD

**Issue by PrakVayuz** [Anupriyabanger/Bee-Recruiter#2260]
remove the Tx icon 
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/632e7ba5-578b-41c9-bc4d-d77b85cd17a4)

**Comment by vinayak-vayuz** [comment]
The icon is used to remove all the styles from the text, which is useful if someone pastes data from chatgpt or similar AI.
