### ISSUE TITLE
Web > Employer > UI > Post Job

### ISSUE THREAD

**Issue by PrakVayuz** [Anupriyabanger/Bee-Recruiter#2265]
Fix the Nationality Field UI 
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/0d5bb580-c08e-4811-95c6-f3d351d9c588)

**Comment by vinayak-vayuz** [comment]
<img width="464" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/2be40107-e4c7-4193-acd7-cdd58e4478b8">
