### ISSUE TITLE
Web > employer > UI > Job Details 

### ISSUE THREAD

**Issue by PrakVayuz** [Anupriyabanger/Bee-Recruiter#2267]
salary and nationality fields are overlapping 
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/4ed3d054-d558-4da3-96b7-92388c6430f6)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/c293d66b-51a1-4e3a-81e5-9b77ee24fb3e">
