### ISSUE TITLE
Web > Employer > UI >My Job

### ISSUE THREAD

**Issue by PrakVayuz** [Anupriyabanger/Bee-Recruiter#2269]
Change the Job Tags Color 
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/c6b356aa-2010-4af1-97d5-2060fee05c51)

**Comment by vinayak-vayuz** [comment]
@naveesha-vayuz

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/2d0d6899-8da2-4b79-b176-8bcf50e54459">
