### ISSUE TITLE
Web > Employer > UI > ATS > My Jobs

### ISSUE THREAD

**Issue by PrakVayuz** [Anupriyabanger/Bee-Recruiter#2271]
Change the UI 
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/e71e93f5-4d72-42d0-b8e0-8b72eb0cd98f)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/77900675-c4d0-4ede-aef2-104e827b6558">
