### ISSUE TITLE
Web > Institute > UI > Course/Program

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2276]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/1c0c7cc1-14ba-4638-b274-1cba195d4f25">

Add top and bottom padding to Illustract and no data found text

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/be8acf24-2bae-41ae-b39c-17a5c6b5645e">
