### ISSUE TITLE
Web > Institute > UI > Calendar

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2280]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/baacf41b-4c62-4776-afa9-a765e0705d27">

Highlight the date in the small calendar on which an interview is scheduled

**Comment by vinayak-vayuz** [comment]
This is not an UI issues, We'll need value for this in the small calendar first, then I can highlight the dates.

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/5918c385-6d03-4c40-ad7e-24cbd1208451)

**Comment by milivayuz** [comment]
![Uploading image.png…]()

Not showing

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/29d23406-e0ee-4e8f-a737-53c55c885327)
