### ISSUE TITLE
Web > Institute > Functional > Courses

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2284]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/c7548211-6a68-46a4-94ae-afcd9da6afbe">

Deleted courses are showing up on refresh

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/564d4564-1859-4482-8666-d743cc6aec0f)
