### ISSUE TITLE
Web > Employer > UI > CV Management

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2290]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/77f74aba-4bd6-4533-a1c8-b8741b2a2b3f">

Remove the mentioned box

**Comment by vinayak-vayuz** [comment]
Data is available so the border is visible but It's not mapped correctly, please check @PrakVayuz 

<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f45e3c53-d220-42de-ae46-fe0cb2271d65">

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/5d823efc-7595-4254-adef-91f51fcbaf41)
