### ISSUE TITLE
Web > Employer > Functional > Dashboard

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2291]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/f196b8bc-5213-43d4-b41c-4f05ad59116f">

Selected candidates are 2 but on dashboard it is showing up 3
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/96df29e6-0633-4645-b8bd-5bbc2f91b2d4">

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/808b507b-34a7-4c6b-9557-852e212f9c78)
Selected candidates are changed to Hired Candidates

**Comment by milivayuz** [comment]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/d4a30129-2832-4ea3-b927-e33bd0e6258e">
@PrakVayuz Onboarded Candidate card is not showing up
