### ISSUE TITLE
Web > Job Seeker > Functioanl> Homepage

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2293]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/a363cdeb-ae19-4da5-ad3d-b6f4ef0c1af3">

On applying successfully, an Alert should pop up Applied successfully

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/35f45c89-8692-4458-bc62-02d25a57b2e4)

**Comment by milivayuz** [comment]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/c89e0d51-8931-4b9a-9e71-58c8bae640ea">

change the button to withdraw once applied

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/4acb5b48-f11c-4a12-b3ce-adf06984d51d)
