### ISSUE TITLE
Web > Job Seeker > Functional> Homepage 

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2342]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/6d64222b-7895-42c1-b0ff-381930977936">
Hot Job section is missing

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/0a041e6a-9c0a-43d8-9261-feac2a28b1b3)
