### ISSUE TITLE
Web > Job Seeker > UI > Job Feed

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2345]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/1265de2e-416b-4b73-8bf8-9eb78b5c58be">

Fliter, Search icons are not aligned in search bar

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/342b7910-b7e9-4d32-9c70-8b59a2cdf417">
