### ISSUE TITLE
Web > Institute > Function>  Course

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2359]
<img width="872" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/1dba77ca-adca-4922-b75b-946e72e15604">

Delete button is taking to long and still no action is done

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/a69e253a-b968-4323-8946-f9fd56a3e1a8)
