### ISSUE TITLE
post job > UI > needs to fix the UI of the check box of guidelines 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#236]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/02b215f6-6973-436d-bcc3-e124eaa4914d)

**Comment by vinayak-vayuz** [comment]
<img width="474" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/d733584c-8a33-4f41-b2da-693933141c5b">
Done
