### ISSUE TITLE
Web > Institute > Functional> Course

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2362]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/b3c91d96-cccc-439d-ac48-745d00ccbf93">
Count is not correct

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/be474612-c66b-4ba1-a7b9-33744a982ec8)
