### ISSUE TITLE
Web > Institute > Functional > Profile

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2369]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/4335be4c-0038-4966-98e3-51a10fe187eb">

After uploading the profile photo page is navigated to view the profile screen instead of remaining on the editing page

**Comment by PrakVayuz** [comment]
Following the same flow as discussed with previous pointer
