### ISSUE TITLE
post job > UI > as per the figma design , other benifits should be in the last left corner not on the right side 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#237]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/7d1456b4-6a14-4871-8958-c27524a87cb9)

**Comment by vinayak-vayuz** [comment]
<img width="902" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/342f64d6-6fa2-4a1f-ad05-f3c49ceaaf6d">
Done
