### ISSUE TITLE
Web > Institute > Functional > Profile

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2370]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/5a40f682-4a5a-410b-b62f-dc10d8e523d3">

Country is a required field but still profile is updating without filling it up.

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/7e1edc58-2ebf-47f1-8247-dbafdfa6a3e1)
