### ISSUE TITLE
Web > Institute  > Dashboard

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2377]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/11eb5f95-ccf4-40d4-918a-760f7f04c42f">

Some graphs start with 1 and some with 0. Kindly follow uniformity and start all graphs with a 0

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/94e59e96-bd0d-4a81-bff5-456eb647a12c)
