### ISSUE TITLE
Post job > UI > mention the maximize and minimize in the salary part with light buttons , take reference from figma

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#238]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/9fbbceb6-a070-4568-ad07-715e01ef6d0d)

**Comment by vinayak-vayuz** [comment]
<img width="902" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/fda826f1-4ab1-47f9-b362-675043df8288">
Done
