### ISSUE TITLE
Web > Institute > Course

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2380]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/20394be4-fd4d-4a10-ba3f-dc1362fb0e64">

Course Location should have link only if the course is online otherwise mention the place name

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/8d74ce28-2065-4528-9f0d-8f44c18d0345)
