### ISSUE TITLE
Web > Institute > functional > Course

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2382]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/7392d636-5ed4-4a2c-b17a-86270e85b21a">

All the field should be mandatory

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/2e6d4970-fe12-4c7c-8103-a0a2b9feddf8)
