### ISSUE TITLE
Post job > UI > Insurance and accommodation are missing from the tabs 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#239]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/d3c166c6-26d0-4a40-b1fa-7eb3e8f22a28)

**Comment by vinayak-vayuz** [comment]
<img width="891" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/07af9e95-7881-4f7c-bb2a-fd0b2fd77784">
Done
