### ISSUE TITLE
Web > Course Seeker > UI > Course

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2392]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/4a70a7d2-6b7f-41e4-a94e-ce11df4f625f">

Summary in the card should end above the posted date it should not exceeds that

**Comment by vinayak-vayuz** [comment]
<img width="780" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/e6d18569-9a0b-4c22-98be-919a2801a859">
