### ISSUE TITLE
Web > Institute >Funtional >ATS

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2397]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/93b5e806-a265-46b1-94d7-57f3dd5beb09">

send email is not working

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/26699166-bef1-4459-aeb6-d85df2d1a671)
