### ISSUE TITLE
Web > Institute >UI > Calendar

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2399]
<img width="354" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/471378c1-5459-495e-81f8-8799b52a1e28">

Change month text to white on hover

**Comment by vinayak-vayuz** [comment]
<img width="327" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a14cf734-b24e-4b3c-b2a5-23bed3c738f5">
