### ISSUE TITLE
Post jobs > UI > Header is displayed twice 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#240]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/4efdbf24-7410-41fd-8896-64dd92d078ab)

**Comment by vinayak-vayuz** [comment]
<img width="879" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/54ad0419-cd36-4b27-bbff-29b5ae66c4f6">
Done
