### ISSUE TITLE
My calender > UI > Check with figma design of calender 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#241]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/c0bc4afb-7da6-467c-9daf-bcd8fd5b4d85)

**Comment by vinayak-vayuz** [comment]
To make it functional we've to use packages in react, they're customizable to some extent. Replicating figma isn't always an option.
