### ISSUE TITLE
Profile management > UI > Add option to edit as per figma 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#242]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/2a64f54b-d440-4776-9692-840544ccc59d)

**Comment by vinayak-vayuz** [comment]
Added

**Comment by vinayak-vayuz** [comment]
<img width="878" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a1c50764-b772-4b92-80c6-56d9c444e12b">
Done
