### ISSUE TITLE
Web > Job Seeker > Functional > Resume

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2428]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/16270c77-d92a-40df-bf69-cbb3713c4116">

Add option to upload resume

**Comment by milivayuz** [comment]
Instead of doing above mentioned word go with changing name to generate resume instead of my resume

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/91ab6c57-0ec8-4dce-9f03-0216c49f1f19)
