### ISSUE TITLE
Web > Job Seeker > Functional > Resume

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2429]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/ac718415-302c-4959-9e6e-f71ec7b31eba">

Show the list of resumes once you click on resume in navigation bar

**Comment by milivayuz** [comment]
Instead of showing it in the navigation bar add a button in the profile under resume section of view all

**Comment by PrakVayuz** [comment]
In Profile Section We have to only show the single resume as if the employer sees a particular job seeker profile it has only one resume to view
