### ISSUE TITLE
App > Job Seeker > Functional > Resume

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2438]
<img width="115" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/6c4c63db-eace-447a-9f55-6a14ad24884c">
Add addition button that allow user to upload resume

**Comment by Sujayvayuz07** [comment]
@milivayuz 
 user can able to upload resume from Profile.
