### ISSUE TITLE
CV management > resume listing > UI > Dropdowns are missing as per figma 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#244]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/f81cc29d-eb9b-4397-af1a-e65ee38b4142)

**Comment by vinayak-vayuz** [comment]
Added

**Comment by vinayak-vayuz** [comment]
<img width="884" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f2fd4f43-f808-4ca5-ac9f-769775b8be92">
