### ISSUE TITLE
CV management > View profile > UI > Project details are missing 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#245]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/fd7d1314-21ab-425f-ae4e-ccd0145d7a67)

**Comment by vinayak-vayuz** [comment]
Added project details section

**Comment by vinayak-vayuz** [comment]
<img width="867" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0ceffa26-a3d6-49a9-9d03-abab40a8401a">
Done
