### ISSUE TITLE
CV management > schedule interview > UI > Check figma design for schedule interview attached below 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#246]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/b9a81c2f-a192-4996-9938-15135ff3b3ea)

**Comment by vinayak-vayuz** [comment]
<img width="671" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/705dd8c7-28f4-4580-81f9-bd3494105c08">
Done
