### ISSUE TITLE
Web > courseseeker > Functional > My Application

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2462]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/47b5b054-1f3a-4172-bb6f-20a99bbc6595">

Convert the resume to full screen like in job seeker

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/6e3db655-9822-44b8-9474-9d7eca1e7a7d)
