### ISSUE TITLE
Web > courseseeker > Functional > interview

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2465]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/d1594b72-87f0-4019-8804-76f3b63b31d8">

Interview details are not opening on click

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/51353701-98a3-451c-9e87-e2fed7cfc0d9)

**Comment by milivayuz** [comment]
in the course seeker

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/dc0c7e59-8733-4756-b9f9-ea240211dc30)
