### ISSUE TITLE
App > institute> Functional > Dashboard

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2476]
<img width="117" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/f144f3ee-7ff1-47c5-b493-9e974fea6fda">
Add users profile as shown in web in shortlist candidates. Selected candidate total avg application

**Comment by rajasrivastava101** [comment]
Can see the same issue happening.
