### ISSUE TITLE
Admin > Package > UI > Align the buttons properly in the right corner 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#248]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/af1cf424-8854-473f-b0b6-de19e3a0eeab)

**Comment by vinayak-vayuz** [comment]
Which buttons? @rajasrivastava101

**Comment by vinayak-vayuz** [comment]
Done
<img width="165" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/85a20841-4c75-4578-b98a-95f54706c12e">
