### ISSUE TITLE
App > institute>UI > ATS

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2514]
<img width="116" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/5c7474d6-2b31-4079-92dd-5df4f38d7f83">
Change filter as per the web

**Comment by aman-vayuz** [comment]
Filter is not working properly in web , made changes according to issue. But will have to check once its done in web or backend side.
