### ISSUE TITLE
App > institute>Functional > Post Job

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2518]
<img width="118" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/df11b3ae-adec-438d-840c-76b38f24033b">
Post Course is not working my screening is freezing after visiting Post Course

**Comment by rajasrivastava101** [comment]
Still same issue is there on post course screen.

**Comment by rajasrivastava101** [comment]
Still happening the same issue , kindly attach the screenshot or video of posting course.

**Comment by aman-vayuz** [comment]
https://github.com/Anupriyabanger/Bee-Recruiter/assets/167163103/249e5f32-bf7f-4853-a2dc-697ed4019815
