### ISSUE TITLE
Admin>Jobseeker list> please add import with Excel as well

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#253]

**Comment by rajasrivastava101** [comment]
Please add the feature to upload bulk data from excel sheet to the listing view.

**Comment by vinayak-vayuz** [comment]
Added 
<img width="752" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/5cb6ed06-2db5-4b51-a526-5cec24b0b777">

**Comment by rajasrivastava101** [comment]
please check once It should be functional . @vinayak-vayuz
