### ISSUE TITLE
Web > Consultant > Functional > Drafted Jobs

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2537]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/5840360d-7f8a-4c40-9f8b-76ebc2feeb18">

Back button should navigate to all instead of edit page

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/f81b859c-3728-437f-b8b2-c5c073916c36)

**Comment by milivayuz** [comment]
it is still following the edit page path

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/3bfcc555-375d-49a5-9c68-9793509c392f)
