### ISSUE TITLE
Web > Consultant > UI > My Jobs > Drafted Job

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2538]
<img width="952" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/fbf49c26-d607-40c6-b20c-4992500505ba">
The navigation bar should not highlighted

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/69b2ee82-27cd-46ce-a494-cdb5b1848bae">
