### ISSUE TITLE
Web > Consultant > Functional > My Jobs > Drafted Jobs

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2539]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/014a7c0c-61fc-4d15-acba-f87fd9d2d361">
The deleted job is not showing up in the deleted job

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/6e82a0bb-eae5-4d89-9c27-effe69b6a10e)
