### ISSUE TITLE
Web > Consultant > Functional > My Jobs > Drafted Jobs

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2540]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/a1dd7c53-3315-4ab1-9b2c-31e2538f87a8">
Post Job automatically showing up pre-filled data

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/2152c936-de03-405d-8112-c72ad91045d4)

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/04b649f0-c4fe-431d-9175-839a5b6000f6)
