### ISSUE TITLE
Web > Consultant > Functional > My Jobs > Draft Jobs > Post Job

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2541]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/20aaab22-8960-4cb4-9460-30254c4565bb">
drafted job showing post button showing up multiple cross buttons in skills

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/cdcfc666-d195-4a15-888a-a003edad3383)
