### ISSUE TITLE
Web > Consultant > Functional > My Jobs > Draft Jobs > Post Job 

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2542]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/5dd89468-d112-4106-96df-15f98a96d6c6">
Deleted jobs are not reposted by posting them again

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/06d0d757-c721-477c-9f73-e1a65343dc3b)
