### ISSUE TITLE
Web > Consultant > UI> My Jobs >Delete JObs

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2543]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/601fb5ac-9666-4912-9f5c-0061e6a05b4e">

the illustration should be in center

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/57b8ccae-94c0-4a22-bd6a-5e22f00d31dc">
