### ISSUE TITLE
Web > Consultant > Functional > My Jobs >Drafted jobs

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2544]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/f37452f9-e3f9-4907-b9e4-d93964106505">

Filter is removed when no jobs are there. Do not remove it

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/0d26e778-917f-4f42-b21c-5169050f2078)
