### ISSUE TITLE
Web > Consultant > Functional > My Jobs >Drafted jobs

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2545]
<img width="958" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/98b0c671-2ddb-4835-94d3-81207ba64988">
Filter is missing in case of no data on any particular filter

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/9577add4-02b7-4010-9b28-246dd515b64c)
