### ISSUE TITLE
Admin>Back button please in all process

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#255]

**Comment by rajasrivastava101** [comment]
Its a general comment , need to add the back button in every page on the left top corner.

**Comment by vinayak-vayuz** [comment]
<img width="50" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f04e104a-7943-4ace-9ffb-9f0bd55ddc4b">
Added
