### ISSUE TITLE
Web > Consultant > Functional > My Jobs > Manage

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2594]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/b2c256a3-6d49-4d8b-8d93-467045b5ce21">

Instead of today's interview schedule count  show total interview scheduled count

**Comment by PrakVayuz** [comment]
Data is showing here is for a particular job
