### ISSUE TITLE
Web > Consultant > Functional > My Jobs > Manage 

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2596]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/0f3c5b90-3d6e-410f-942b-080e8a4585d7">

integrate new ATS Module

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/4fb5bf0f-7694-4ae8-ba44-3b198ed02d48)
