### ISSUE TITLE
Web > Consultant > UI > Calendar

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2597]
<img width="950" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/06bc1512-2875-4ebf-ad6b-e5a6823fbc80">
Add padding and margin in the schedule button so that it look presentable

**Comment by vinayak-vayuz** [comment]
<img width="627" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/9c2ede7a-8967-40ce-b758-792912b3662e">
