### ISSUE TITLE
Web > Consultant > Functional > Schedule Interview

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2600]
<img width="958" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/743c0f28-2715-43b3-ab1b-921febc2936b">

Interview in so scheduling. Save Button not workinghttps://github.com/Anupriyabanger/Bee-Recruiter/issues/2598

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/32616bdc-ac97-4ef0-9b42-aae6027e97c0)
