### ISSUE TITLE
Web > Consultant > Functional > Calendar

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2603]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/cc07611d-78aa-4ad2-b50c-5f3cd56ad564">

From Calendar's Schedule an interview button I am navigated to the institute module

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/22c5875c-0b33-467c-a052-8e54508190f9)
