### ISSUE TITLE
Web > Consultant > Functional > My Jobs > Deleted Jobs

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2606]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/191485fc-efc2-42e5-8a1a-5555bf511372">

Job is not posted from the delete jobs list

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/79bb0045-d82f-44ba-b1b4-3f899abe3a2e)
