### ISSUE TITLE
Web > Consultant > UI > Menu 

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2614]
<img width="211" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/5af8b747-701b-465e-8d2a-69a5dda81b46">

Option of try premium is missing

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/e7648e57-0d23-4a40-9bf9-6331afd7f213">
when you are already a premium member, you wont get the option

**Comment by milivayuz** [comment]
in the premium they have the option to upgrade so have to add it for the upgrade purpose of existing premium users.

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/553c4ed1-e194-41b6-89e9-54364694a638)
