### ISSUE TITLE
Web > Consultant > UI > Functional > ATS

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2626]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/9b7f943c-8239-412b-86ee-bd7041f7f8a4">

add new design in the consultant ATS

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/a428948c-5a44-47c9-90bc-15fc6b111671)
