### ISSUE TITLE
Post job > Job posting guidelines > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#263]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/640c6d87-b90e-477b-ae0c-38c380ef5db0)
Kindly remove the title just above the Job posting guidelines heading.

**Comment by vinayak-vayuz** [comment]
<img width="556" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/79d2b8de-1426-483d-8a0b-e2784f519cb2">
Done
