### ISSUE TITLE
Web > Consultant > UI > CV management

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2633]
<img width="950" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/9fdefadc-852b-4c0e-8115-d8de527c2d0c">
remove resume column

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/beb771f7-dcd4-4552-9b29-73add1a946b7">

**Comment by milivayuz** [comment]
still there

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/ad4484ed-28c4-4587-9c18-3bb4a9dc1e73">
