### ISSUE TITLE
Web > Consultant > Functional > Calendar

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2636]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/02c63c35-858e-4a6f-8d8f-dd48bedd79e3">

view job should be here instead of view course

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/16e13f6a-b704-40e9-98ec-c1ffb8e42f57)
