### ISSUE TITLE
Web > Consultant > Functional > CV Management

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2639]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/fd964937-4cd0-486e-9f42-7c8fc448b02a)

once the interview is canceled on calendar it should be removed from the cv management as well

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/a82261d3-1663-4cc2-a6dd-f90f331ebea8)

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/a82261d3-1663-4cc2-a6dd-f90f331ebea8)
