### ISSUE TITLE
App > Employer > Functional > Deleted Jobs

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2658]
<img width="116" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/bbf632b6-e859-44e9-a7e0-afb11b706201">
Filter is not working

**Comment by aman-vayuz** [comment]
Done

**Comment by milivayuz** [comment]
sort and posted on are not working together

**Comment by rajasrivastava101** [comment]
Custom range filter does not working in deleted jobs
