### ISSUE TITLE
General > Need to make an error page and no data page 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#272]

**Comment by vinayak-vayuz** [comment]
Done from my side

**Comment by naveesha-vayuz** [comment]
Done

**Comment by vinayak-vayuz** [comment]
<img width="924" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/aa5ab3b7-0f11-4648-80c4-8064db523a2c">
<img width="885" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/84f04135-766c-4489-9949-f92705bb9193">
Done
