### ISSUE TITLE
Draft Job >>Please remove , manage from modal, statics of draft job and correct date filter

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#274]
![Screenshot from 2023-05-25 17-50-10](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/5648e26a-42da-4c85-b6c3-21edcacc572e)

**Comment by vinayak-vayuz** [comment]
<img width="288" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/13074254-46a4-4a49-bbb8-119a785ea4b7">

**Comment by vinayak-vayuz** [comment]
<img width="286" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/fd931ecc-6900-4cf3-9c3c-8babffbccf74">

**Comment by vinayak-vayuz** [comment]
<img width="878" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/1446cc6c-b73f-4895-96b0-db4d40682639">
Done
