### ISSUE TITLE
My job >> Remove edit job from modal and correct date filter

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#275]
![Screenshot from 2023-05-25 17-52-21](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/7b1a4b09-944f-4c41-adeb-376da27b42f5)

**Comment by vinayak-vayuz** [comment]
<img width="289" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/9f335b0a-afc5-4e89-b7e4-6078b8232294">
