### ISSUE TITLE
App > Consultant > Functional > Draft Jobs

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2771]
<img width="115" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/fae6774c-dad7-4c58-9031-31c17f1c99c6">
Draft job will have the option of edit not manage

**Comment by milivayuz** [comment]
<img width="155" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/8d16fe49-cad0-4701-ba3e-a75c61d2adeb">

This coming up on edit

**Comment by kaviraj-thakurr** [comment]
https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/50ee9705-2450-4d11-966e-a36586a9793a
