### ISSUE TITLE
Change status is not working

### ISSUE THREAD

**Issue by aman-vayuz** [Anupriyabanger/Bee-Recruiter#2789]
![employer issue](https://github.com/Anupriyabanger/Bee-Recruiter/assets/167163103/5f654652-172d-44ef-8200-cc522cc85bf5)

**Comment by rajasrivastava101** [comment]
Status is getting changed but it is taking time to reflect the changes. Make it smooth.

**Comment by aman-vayuz** [comment]
added a loading icon
