### ISSUE TITLE
Web > Home screen > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#280]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/2bfed4d8-993d-4d5d-b044-7dab3621771c)
On header click on any option , selected option is displayed as my jobs.

**Comment by vinayak-vayuz** [comment]
<img width="935" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a1f10ee5-b86d-48b9-873b-ffd9cd8d32f5">
The issue has been fixed.
