### ISSUE TITLE
Web > Dashboard > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#281]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/1e11552c-446f-4918-8aaa-701b3f90950b)
Remove this banking here , this page is for the all combined job applications.

**Comment by naveesha-vayuz** [comment]
@rajasrivastava101 The banking is not on Figma

**Comment by vinayak-vayuz** [comment]
It's coming from backend. @manojnegi07 sir Please send some realistic data
