### ISSUE TITLE
Web > Homescreen > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#282]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/09c9105b-ebfb-4e13-9b99-c387db8ab226)
Not able to access the notification panel , and neither cross for cancelling button is working.

**Comment by vinayak-vayuz** [comment]
It has not been implemented. Now the cross icon is working.
