### ISSUE TITLE
Web > Edit jobs > UI > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#284]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/f462b0c0-9c57-4b8b-a1f5-df6c09e703ad)
Not able to edit job , page is not ready.

**Comment by vinayak-vayuz** [comment]
Page was ready but It was an issue with linking. Fixed it.
