### ISSUE TITLE
Preview job >> Please fix UI of preview job

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#305]
![Uploading Screenshot from 2023-06-05 18-08-15.png…]()

**Comment by vinayak-vayuz** [comment]
<img width="899" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/fb911c6a-2906-4110-9e16-0f96cdfc7e99">
http://localhost:3000/employer/myjob/jobdetail
Done
