### ISSUE TITLE
Web > Homepage > Functional > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#307]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/4ef65506-173b-48f0-9c58-99d815457cbe)
Need to put the Sign Up button on the landing page.

**Comment by vinayak-vayuz** [comment]
<img width="205" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/ce3ec145-01da-448b-a89d-8ebf97d6abd0">
Done
