### ISSUE TITLE
Web > SignIn > UI

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#308]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/8d77ff75-3fd4-4f82-a9e0-40c8920b48b5)
Need to align the error messages properly.

**Comment by vinayak-vayuz** [comment]
<img width="336" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/c71998d5-e387-4fb8-a6d6-94a0d2cd0f9d">
Done
