### ISSUE TITLE
Web > Select User > UI

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#312]
Cross button is not visible

**Comment by naveesha-vayuz** [comment]
Done form my side @vinayak-vayuz please check

**Comment by vinayak-vayuz** [comment]
It's visible on my system.
<img width="750" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/45a7d908-4dbf-4f78-97e0-7ac0e4ed69f6">
