### ISSUE TITLE
Web > Select User > UI 

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#313]
Remove the continue as guest

**Comment by naveesha-vayuz** [comment]
Done from my side

**Comment by vinayak-vayuz** [comment]
Removed 
![Uploading image.png…]()

**Comment by vinayak-vayuz** [comment]
Removed 
<img width="730" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/72c6baec-c558-44f1-97d3-fa31bf1aeff6">
