### ISSUE TITLE
Web > Sign Up > UI > Functional

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#314]
Implement Back Functionality that user can go back to previous page

**Comment by naveesha-vayuz** [comment]
Done from my side

**Comment by vinayak-vayuz** [comment]
Done 
<img width="356" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/73d73d3b-3c25-487a-85e7-7b33b9843b79">
