### ISSUE TITLE
Web > Employer > My Calendar > Functional

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#364]
Make the day highlighted if some data is there

**Comment by MaroofTech** [comment]
![Screenshot from 2023-06-08 15-57-26](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/7b4edb43-4301-4dde-a454-8f90cc5e52dd)
Its already coming if data prsent
