### ISSUE TITLE
Web > Employer > My Calendar > Interview Details >UI

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#368]
Add a back option in the interview details page.

**Comment by naveesha-vayuz** [comment]
done from my side

**Comment by vinayak-vayuz** [comment]
<img width="323" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b56dbfca-40db-410a-9f2c-f717074daea6">
Done
