### ISSUE TITLE
Web > Employer > Profile > Edit >Two Step Verification > Functional

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#400]
Add Toaster on Two step verification

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/5fe8ac93-8706-45f8-a8f0-32dfa57f11b4)
Its coming again and again whenever go to the page , it should only come when we switch on or off from the toggle.

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/3d38ec3b-6b42-4e4b-8bf3-f839e21a2ad4)
Toaster is not there , kindly add it.

**Comment by rajasrivastava101** [comment]
Kindly implement it.
