### ISSUE TITLE
Web > Employer > Functional

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#403]
All the tags which contains the email and phone number , the tag change with the link tag or anchor tag for redirecting the user to send a mail or number to dial-pad.

**Comment by vinayak-vayuz** [comment]
<img width="345" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/59ef8655-a5c6-43ad-8a7a-b82e24b148f8">
Added
