### ISSUE TITLE
Need api's for manage job dashboard

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#407]
![Screenshot from 2023-06-09 16-52-12](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/7dbb98d9-4f16-4aad-a9cf-790f6c3421ec)

**Comment by manojnegi07** [comment]
@MaroofTech  here are the apis for dashboard
https://beerecruiter.vayuz.com/api/job_graphData?start_date=2023-04-02 00:00:00&end_date=2023-05-19 00:00:00
https://beerecruiter.vayuz.com/api/getJobDashbaordData/MQ==

**Comment by manojnegi07** [comment]
Last two graphs are not clear. @rajasrivastava101  please share the logic for these graphs

**Comment by MaroofTech** [comment]
> @MaroofTech here are the apis for dashboard https://beerecruiter.vayuz.com/api/job_graphData?start_date=2023-04-02 00:00:00&end_date=2023-05-19 00:00:00 https://beerecruiter.vayuz.com/api/getJobDashbaordData/MQ==

@manojn egi07 need data in this end point(job_graphData) on the basis of job id    

![Screenshot from 2023-06-13 15-07-30](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/b71a6a9e-4aac-4c65-9032-b6f437c6c8ee)

![Screenshot from 2023-06-13 15-07-16](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/1653cc70-6666-4247-8e38-0183a846f80d)

**Comment by MaroofTech** [comment]
Also needed today interview scheduled API for particular job, showcasing at right side in above SS @manojnegi07

**Comment by rgnarok** [comment]
@MaroofTech @manojnegi07 
In the first graph , we need to show percentage of hired people out of total applications received.
In the second graph , kindly make it average daily application out of the weekly total applications received.

**Comment by MaroofTech** [comment]
@manojnegi07 please take it forward

**Comment by manojnegi07** [comment]
Done @MaroofTech
