### ISSUE TITLE
Employer | web | CV Management | dropdown not hide when click to other 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#422]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/f8c1053b-1546-4bd8-981f-48622b93ef17)
### dropdown not hide when click to other  place

**Comment by vinayak-vayuz** [comment]
Done

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/75beba93-efca-499b-9d2f-efe39c595747)
On click three dots , dropdown is coming very far from the three dots even on the other columns , kindly fix it.

**Comment by vinayak-vayuz** [comment]
<img width="215" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/c49d6e49-c6c7-4ff2-aad4-4987dd659a5f">
Made it close
