### ISSUE TITLE
Employer | Profile | call back request | 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#425]
I need a screen for call-back request success.

**Comment by vinayak-vayuz** [comment]
<img width="366" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/5d426fb8-27c1-4bf0-a9d5-24bea5598b08">
Done

**Comment by vinayak-vayuz** [comment]
@pankajVayuz UI is done.. Pass the data to backend
