### ISSUE TITLE
Sign Up > Size of the social media icon is going wrong as well as there is too much space in between them

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#433]

**Comment by rajasrivastava101** [comment]
Still there is a gap between the social media icons.

**Comment by vinayak-vayuz** [comment]
<img width="196" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/ac11ffa5-012d-47e9-b2b4-dc423b3caa9f">
Decreased
