### ISSUE TITLE
Sign Up > Verify number>make the size of resent similar to the text with it

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#434]

**Comment by vinayak-vayuz** [comment]
![Uploading image.png…]()
Done

**Comment by naveesha-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/1388712a-5aa3-4b51-b48f-c881680b0591)
Not Same

**Comment by vinayak-vayuz** [comment]
<img width="376" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/ef4d00d8-8efd-49b0-ac89-14df5979290d">
Done
