### ISSUE TITLE
Settings > Change password > keep the size of the text in note section same as the 'enter your current password heading

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#438]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/3571f5e5-1cb4-4543-97ad-4e2e86822d73)

**Comment by vinayak-vayuz** [comment]
<img width="692" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/85e6e9a1-5588-4304-845d-cf7b8562bc0e">
Done
