### ISSUE TITLE
Settings> change phone number> please align the elements properly as well as decrease the size of the illustration

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#440]
Please refer figma design while you are working on this page
1) Color of the field
2) why is the password already entered
3) Size of the button
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/19f8bffb-7d4c-472b-a889-23f6c84bfc17)

**Comment by vinayak-vayuz** [comment]
<img width="683" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/bd90542c-c824-4b74-ae3a-f98c7c31f3a8">
Done

**Comment by vinayak-vayuz** [comment]
![Uploading image.png…]()

**Comment by vinayak-vayuz** [comment]
<img width="462" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/da644a16-8cc0-4526-8e97-ddf7a8452879">
