### ISSUE TITLE
Settings > change theme > please give proper spacing in between the list as well as check the weight of the text 

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#442]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/5d1c8d4c-aa57-4610-8e6e-6b0f6ba36e6f)

**Comment by vinayak-vayuz** [comment]
<img width="149" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/741ae6be-6102-4f33-9dda-d76a9698601d">
Done
