### ISSUE TITLE
settings > language preference > on hover please change the color of the icon as well. Also please lighten the shade of grey when not on hover, refer figma for better clearity

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#444]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/55154838-5662-4e5a-b65d-79f4900d871f)

**Comment by vinayak-vayuz** [comment]
<img width="470" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/3749ba57-128f-44c1-ba3f-b7c8518145e9">
Done
