### ISSUE TITLE
settings> sync data > togle is not going right, refer to figma for clearity

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#445]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/a335991f-e6a7-4491-b28a-ea44928881e1)

**Comment by vinayak-vayuz** [comment]
<img width="76" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b0feeb92-cc99-4547-a7c0-5393dab6925c">
Done
