### ISSUE TITLE
Setting > edit profile > size of update button is not noticeble, please make it noticeble

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#448]

**Comment by naveesha-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/d2f50301-a473-43a8-8cec-79b2b5a82138)

**Comment by vinayak-vayuz** [comment]
<img width="861" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/341f7d71-43db-4a7d-81fc-fd58e05b6edd">
Done
