### ISSUE TITLE
Employer | web | Cv management | 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#474]
change the shimmer in cv management and fix the ui.

**Comment by vinayak-vayuz** [comment]
Done

**Comment by rajasrivastava101** [comment]
Shimmer is done , But needs to cover the gap after Serial number in listing view

**Comment by vinayak-vayuz** [comment]
<img width="877" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/05d14e46-9117-4427-810b-e415571bffe1">
Done
