### ISSUE TITLE
Settings > dark mode > remove the light black box throughout the module

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#504]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/bd35e49a-02a2-4399-9f4b-c56de1f83fe4)

**Comment by vinayak-vayuz** [comment]
<img width="906" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f9beab09-3d30-495d-8487-ff1cfca2e9ca">
Done
