### ISSUE TITLE
Settings> Change theme > the radio button is wrong

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#506]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/1821cb75-dd49-4c49-a771-8a1bbe976493)
Have a look once the radio is selected how the colored circle is not aligned properly.

**Comment by vinayak-vayuz** [comment]
<img width="148" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/9ffc84eb-b450-455c-a98d-f60e270d4a56">
Fixed
