### ISSUE TITLE
Settings > Dark mode > Other Options > On selection color of text is not black as the others

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#510]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/2d506130-938f-4497-af0c-ac9caaf5bdd2)

**Comment by vinayak-vayuz** [comment]
<img width="199" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/c811abf5-ccf3-4f65-94f4-6cf586387d82">

Done
