### ISSUE TITLE
Settings > Change theme > the color of radio button is going different on click

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#512]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/6614d4bd-9343-4094-945a-36dc0aa702c2)

![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/b3199223-86a1-48f7-8358-e59da9f47391)

![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/0f6fd32b-c211-4fe6-8994-0f13ecc20f83)

**Comment by vinayak-vayuz** [comment]
<img width="152" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/4b9734df-d279-4d0d-b96b-2e5710ae6bad">
Done

**Comment by naveesha-vayuz** [comment]
The Buttons are going wrong again @vinayak-vayuz

**Comment by vinayak-vayuz** [comment]
<img width="323" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/01d93a40-c7ed-4949-822d-638dafa9dd0f">
I don't understand the issue.

**Comment by vinayak-vayuz** [comment]
It's working fine at my end.

**Comment by naveesha-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/8b366f32-48ea-4faf-8aef-93f0ebdee8a3)
 
 Then What are we going to do here?

**Comment by vinayak-vayuz** [comment]
<img width="115" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/7f048edf-947f-478f-bd7b-74a8d6170333">
Done
