### ISSUE TITLE
Settings > Edit profile Information > How to upload picture? where do I have to click to upload ? 

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#513]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/ed8d3b61-2909-4ae3-a6f2-3e8578c6aa83)

**Comment by vinayak-vayuz** [comment]
<img width="270" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/80ac3af2-c40a-4da4-b0b0-ca407dc6ec69">
On the camera icon
