### ISSUE TITLE
Settings > Edit profile information > Why is there a dropdown in company name when it could be anything!

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#516]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/efe518d0-d785-43fc-b8b1-a89409b04cc1)

**Comment by vinayak-vayuz** [comment]
It'll be created first in Create Company Page. The whole flow is like this only.

**Comment by naveesha-vayuz** [comment]
Okay
