### ISSUE TITLE
Settings > edit profile >  please put the mobile number in a format

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#517]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/f03bbb4a-7f1b-4e3f-aa27-8053aab0e586)

![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/f2258bb5-62cc-480d-b1ae-db07e1bf4b74)

**Comment by vinayak-vayuz** [comment]
@pankajVayuz If we're taking phone number in International format, It should also look the same in edit profile as well as profile info.
