### ISSUE TITLE
View Profile > Size of user icon is not right

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#521]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/7f0ced27-5220-4ab4-99b5-32cdee0d0474)

**Comment by vinayak-vayuz** [comment]
<img width="895" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/64575de5-f789-4be8-8e7c-efe837c6f5c0">
Done
