### ISSUE TITLE
view profile > text is not readable beside Icon for eg. Company Name

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#522]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/0e8cbffd-ef02-4767-8a97-a89c0dcff86c)

**Comment by vinayak-vayuz** [comment]
<img width="895" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/967d9ef1-e594-4545-9242-f47d6f836d8b">
Done
