### ISSUE TITLE
view profile > Space in between profile information section & advertisement section is less

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#523]
![github](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/25b89ff4-f003-4cce-8856-3d5ebfba2e48)

**Comment by vinayak-vayuz** [comment]
<img width="70" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/cf0ba80c-549a-49e5-9681-baa9a4f66473">
Increased

**Comment by naveesha-vayuz** [comment]
Please shift linkedin to left a little.
