### ISSUE TITLE
CV Management > job title should go in one line rather two 

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#524]
![github1](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/52acdcd2-9434-4c57-843a-bf8d3e1291b6)

**Comment by vinayak-vayuz** [comment]
If we do it in 2 lines, It'll make table data row width thick which will eventually increase the table size. So, I don't think it's necessory.

**Comment by naveesha-vayuz** [comment]
Then Can we slice it?
