### ISSUE TITLE
CV Management > text in dropdown is not visible

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#526]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/75b7424e-976f-4b72-8de1-4a2d44f6b8e4)

**Comment by vinayak-vayuz** [comment]
<img width="318" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/26addcf5-81c3-4611-8083-ff97275872ce">
Done
