### ISSUE TITLE
CV Management > please align the content inside the dropdown to left

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#527]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/885adbe5-da44-4eb5-b021-4bfce026dffc)

**Comment by vinayak-vayuz** [comment]
<img width="141" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/256a0e61-9d55-4e6c-bba1-0d22ef8a423d">

Done
