### ISSUE TITLE
Institute | profile setting | hamburger 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#531]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/5cdf3887-907f-49e8-9a69-96b84eb4f71b)

**Comment by vinayak-vayuz** [comment]
<img width="883" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/43604ab3-5faf-4feb-9d14-fecf0d16b13c">
Done
