### ISSUE TITLE
My calendar > Month > please reduce the text size in the tags as well as keep the color tag a little dark

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#533]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/1612f435-ec6c-4e03-a5da-7e66dd9b8efb)

**Comment by vinayak-vayuz** [comment]
<img width="89" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/80fba3c2-4f68-4744-87db-d0a8e810c189">
Done
