### ISSUE TITLE
Post job > please get the size of fields in shape 

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#534]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/6ee5ee2c-a7c5-416c-bd3c-ff1fdaa80032)

**Comment by vinayak-vayuz** [comment]
<img width="443" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/353ecdc0-5224-4d88-8802-f521fc380d44">
Done
