### ISSUE TITLE
Web | Employer | CV Management

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#557]
The Job title's first letter should be capital.

**Comment by naveesha-vayuz** [comment]
The issue has been literally resolved yet job title like UI/UX are still going wrong so please check how a particular job title is written & goes.

**Comment by naveesha-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/d33c4720-df22-4f70-be20-b4635821014a)

![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/53528283-673b-41fe-a989-c6b030e69286)
.net sujay? really?
