### ISSUE TITLE
Sign In > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#561]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/e80d7cbf-d0bb-49f3-9540-88c100cfb374)
Change the color of forgot password from red to blue like we use in the sign up below in the same page.

**Comment by vinayak-vayuz** [comment]
<img width="732" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a98b42f7-0d60-4981-b6b7-8b50f2d51f3f">
Done
