### ISSUE TITLE
Employer > View Profile > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#566]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/d6ac261a-e979-4998-8c8b-bff1338022c8)
Remove these images from the right.

**Comment by vinayak-vayuz** [comment]
<img width="899" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/4eb424df-548f-4291-b48a-b41a6cb98345">

**Comment by vinayak-vayuz** [comment]
Done
