### ISSUE TITLE
Web | Employer / Institute | Post Job / Course | placeholder

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#567]
Add placeholder in post job and post course.

**Comment by vinayak-vayuz** [comment]
<img width="902" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/3f2a0789-e36a-4e56-95ea-a9e04ce2e53b">
It's showing now!!!
