### ISSUE TITLE
dropdown is not properly placed here

### ISSUE THREAD

**Issue by Mehulna** [Anupriyabanger/Bee-Recruiter#57]
![MicrosoftTeams-image - 2023-03-29T172347 690](https://user-images.githubusercontent.com/93506258/228527567-c60cc5a2-7975-4301-ab02-420a1bda2eb1.png)

**Comment by gauravk-Vayuz** [comment]
Ui Change required

**Comment by gauravk-Vayuz** [comment]
Dropdown replaced with bottomsheet
