### ISSUE TITLE
when loader is on button expanded in both draft and post job

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#570]
![Screenshot from 2023-07-06 17-07-05](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/2479709f-6336-492d-81af-f5278e0e4fd7)

**Comment by vinayak-vayuz** [comment]
<img width="144" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/70462d66-7589-4ff8-a74c-5e109f773214">
Done
