### ISSUE TITLE
Fix delete popup UI

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#571]
![Screenshot from 2023-07-06 17-05-55](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/3e39aa43-4e15-43b9-8d0f-4a69b3538e98)

**Comment by vinayak-vayuz** [comment]
<img width="947" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f39f7df9-8a58-420c-bad8-1f5cd80b9f01">
Done
