### ISSUE TITLE
Load more should come in middle

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#572]
![Screenshot from 2023-07-06 17-05-47](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/ef17d642-d371-4fa5-946f-78c0877d4e68)

**Comment by vinayak-vayuz** [comment]
<img width="896" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/222d1d97-2923-4eaa-a8cc-8a03c6b7244b">
Done
