### ISSUE TITLE
Question input not visible

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#573]
![Screenshot from 2023-07-06 17-03-27](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/f8d8ca4f-64d3-40b5-aba6-e3264944d600)

**Comment by vinayak-vayuz** [comment]
<img width="902" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/8c222282-901b-40a3-9bc8-93017689e8ea">
Done
