### ISSUE TITLE
Place holder not visisble

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#574]
![Screenshot from 2023-07-06 17-02-47](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/3f39aec3-2407-4eb7-8114-2acf419af8bd)

**Comment by vinayak-vayuz** [comment]
<img width="885" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/e5c66502-105d-4352-b862-82ee1ba22cb9">
Done
