### ISSUE TITLE
Employer | web | fix create compony page default image logo and fix validation

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#578]

**Comment by rajasrivastava101** [comment]
Not fixed yet , kindly check once again.

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/b9aa7eff-83ab-4813-9787-4ff2abc7c2c1)
UI is torned for camera in the profile pic.
Please fix it.
