### ISSUE TITLE
Safari > NO Shadow, No outline for the box

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#590]
![WhatsApp Image 2023-07-12 at 15 04 50](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/6763b81c-f8bf-4e8d-ba15-349d3672a28d)

**Comment by vinayak-vayuz** [comment]
In mobile phone It's looking ugly, also in app there's no shadow and outline.
