### ISSUE TITLE
Safari > Select User > I can scroll the screens up

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#592]
![WhatsApp Image 2023-07-12 at 15 07 51](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/45a122b0-32ed-464b-b519-5a7d1017e85a)

**Comment by vinayak-vayuz** [comment]
![Screenshot_2023-08-07-16-42-34-07_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/6a8fd787-fbfb-4f9e-9ecb-feb7765317ea)
Working fine

**Comment by rgnarok** [comment]
There is a little scroll but it looks fine no major issue we can close it @rajasrivastava101
