### ISSUE TITLE
Edge >Sign Up > Drop down list >Dark mode is not applied

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#593]
![image (10)](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/6adaba88-19d0-448c-8727-91dadd27d78c)

**Comment by vinayak-vayuz** [comment]
<img width="268" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b2e86a45-ab0f-49c9-bbd6-6294e6dda069">
Done
