### ISSUE TITLE
Edge > Verify Screen > Numbers are not visible, also its line not squares

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#594]
![image (11)](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/b4abcafd-4d25-44ee-8446-1fff3d791c18)

**Comment by vinayak-vayuz** [comment]
<img width="760" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/4ca5c89f-bedd-47ba-b803-466c551f2c19">
Done
