### ISSUE TITLE
Safari > Sign up > user icons are different family - looks thin

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#597]
![WhatsApp Image 2023-07-12 at 15 15 25](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/892e85e2-5302-4a75-b21f-83e3a77ed625)

**Comment by vinayak-vayuz** [comment]
<img width="248" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a4099ea3-b4e0-4e91-8668-95ac58ac934f">
Changed the user icon, please specifically mention which icons need to be changed.
