### ISSUE TITLE
Safari > Sign up > give proper padding over the screen.

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#599]
![WhatsApp Image 2023-07-12 at 15 15 25](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/3141c757-2eaa-4c0b-b874-f21a30d46d59)

**Comment by vinayak-vayuz** [comment]
<img width="218" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f262dbe9-840f-4294-8e80-65fe25f17dda">
Padding is there
