### ISSUE TITLE
Safari > Sign up > Country code drop down listing UI doesn't looks like on Figma

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#600]
![WhatsApp Image 2023-07-12 at 15 17 10](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/f1645fe4-4cd8-4dd2-88de-6d8ccc188c75)

**Comment by vinayak-vayuz** [comment]
Country field has been removed.
