### ISSUE TITLE
Safari > Sign up > when i click on placeholder it automatically zooms in and out.

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#601]
![WhatsApp Image 2023-07-12 at 15 22 05](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/cb4609b5-e5ad-4f9c-bbc2-de607effb261)

**Comment by vinayak-vayuz** [comment]
It's a feature of iOS, verified with product team
