### ISSUE TITLE
Safari > Sign up > Country> keyboard is overlapping over the drop down.

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#602]
![WhatsApp Image 2023-07-12 at 15 36 32](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/8a4129ad-b439-437e-b7d2-63d7d52544e9)

**Comment by vinayak-vayuz** [comment]
Keyboard is a top label UI of any smartphone, we can't move our UI at the top of keyboard. Also keyboard can't be hidden as It's country dropdown with so many option.
