### ISSUE TITLE
Safari > Sign up > Country name > while scrolling up , full screen goes up.

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#603]
![WhatsApp Image 2023-07-12 at 15 36 32](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/a5c384fd-3562-4d09-bfdc-7c0f1bb828ab)

**Comment by vinayak-vayuz** [comment]
It's working fine at my end. Please recheck and explain if the issue is still there.
