### ISSUE TITLE
Dashboard > Add Hover Effect on cards

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#606]

**Comment by vinayak-vayuz** [comment]
Need clarity on which card? @naveesha-vayuz

**Comment by vinayak-vayuz** [comment]
<img width="223" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/78f43678-f4e2-4bc9-9aba-bd3103d636c3">
Done
