### ISSUE TITLE
Sign Up > please apply dark mode properly

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#619]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/ebbe44ce-ad1b-407d-a36d-d72ad24465a6)

**Comment by vinayak-vayuz** [comment]
<img width="324" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/7dcb5fa8-157a-437d-b8b5-61ee8a12efe6">
Done
