### ISSUE TITLE
Employer > CV management > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#625]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/4781810a-fe7d-45ae-983a-7e9b49931648)
On the lower listing , Dropdown is hiding.

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/edd35842-b04e-488b-a4d6-770ccf0d5e6b)
Still its hiding from the three dots , check

**Comment by vinayak-vayuz** [comment]
<img width="177" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/5d467513-fb59-43bf-a6d7-6bfe4aec8514">
Done
