### ISSUE TITLE
Web > Employer > Post job > No. of openings 

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#626]
validation on number of openings (Only integer value should be displayed)

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/5866c83a-ed8c-4323-a3ce-9bf54b36019f)
Characters are also taken , kindly check only integers should be displayed
