### ISSUE TITLE
Web > Employer > Post job > Pre screening Questions  

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#629]
Set the previous & next button at the bottom of the page
![post course](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/3a3bf7b9-72e0-4cd6-9d0d-d1f40c2829d8)

**Comment by vinayak-vayuz** [comment]
<img width="903" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/fb4ad400-6fed-480a-b5bf-0273bdbb9960">
Done
