### ISSUE TITLE
Employer > My jobs > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#634]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/52d4c311-6c66-4c7c-bcf8-224bf5a51d0c)
Option is hiding from the page

**Comment by vinayak-vayuz** [comment]
<img width="158" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a19041c6-ad6f-403e-9b8d-a892f6ecfe81">
Done
