### ISSUE TITLE
Employer > My jobs > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#640]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/2394d91e-e6e7-4235-bd8f-312f0547fa51)
I have posted a job today 2 hours back but when i put the filter for today . Posted job is not displayed.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/c7332651-8ab8-4457-90c4-72914b2a04d9)

Done

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/9f8a3608-5a7b-4c94-8dc8-8dcf9a9b67c3)
