### ISSUE TITLE
Final Review > post job > Salary range 

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#649]
make salary range editable and add validation the min salary not greater than max salary

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/d9649b96-3409-42dd-ab11-63a8c0109e4f)
Not able to adjust the salary range .

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/12a9a926-5bd0-46f3-8977-19874cd31bc9)
Done
