### ISSUE TITLE
Final Review > my jobs 

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#653]
add validation on search box minimum string should be 3

**Comment by rajasrivastava101** [comment]
How a user would know that it will take minimum 3 characters.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/359aef6d-c19a-4001-8813-31faea9edfcf)
Done

**Comment by rajasrivastava101** [comment]
Not implemented yet , kindly implement it.
