### ISSUE TITLE
Final review > ATS 

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#655]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/5c701508-90dd-4a32-920c-a972c8153f5b)

buttons should be same as figma

**Comment by vinayak-vayuz** [comment]
<img width="895" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/8856bbfc-0461-4059-87f0-469522716cce">
Done
