### ISSUE TITLE
Employer | cv management | action | fix dropdown | 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#657]

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/ff13129e-da0f-4a32-92a5-6182d6344355)
KIndly check , it is getting torned in the bottom of the page.

**Comment by vinayak-vayuz** [comment]
Duplicate issue of #625
