### ISSUE TITLE
Employer | cv management | 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#660]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/cf44feb5-306e-4144-92da-d5c65d5e8ff1)
all dropdown hide. please fix it

**Comment by vinayak-vayuz** [comment]
<img width="856" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/7391139c-6889-4b16-ad7c-0aee078a9261">
Done
