### ISSUE TITLE
Web > Institute > My courses > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#662]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/9af653d6-e6de-455e-8eb6-1d1c4dced389)
I have made up a new account and all the data is already presented here , this should rather ask me to create a institute to post the first course. Or if institute is created then it should ask to post the first course.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/7f40b473-1f4b-4f2c-b47f-66f7918dc09e)
Done
