### ISSUE TITLE
Web > Institute > My courses > Functional > UI

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#663]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/87891350-a203-407d-bb3e-52644ba61791)
Name of the title should be same as the title on header. So kindly make it My courses in both places.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/e75f9f9f-130d-40d7-b1fa-90badfc98c5f)
Done
