### ISSUE TITLE
Web > Institute > My courses > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#664]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/2c2a0549-48f0-4643-9f13-7c9201508b16)
Fix the no data found page.

**Comment by vinayak-vayuz** [comment]
<img width="919" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/2b2c5470-8a6f-4421-a6ed-62f68abfec72">
Done
