### ISSUE TITLE
Web > Institute > My calendar > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#670]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/2da241c1-cc37-447c-84fc-7c3ca96e8ec2)
Here it is showing upcoming interviews rather upcoming screenings. Kindly make it screenings rather interviews.

**Comment by vinayak-vayuz** [comment]
<img width="273" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/2390f733-0bbc-44fa-9d7a-42361faf4f5a">
Done
