### ISSUE TITLE
Web > Institute > Notification > Functional > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#673]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/36e4ddae-9e90-4e2f-af57-c33f8a36d046)
Need to have a page to see all notifications and should direct to a notification icon on the header.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/e47462ec-a237-4eeb-8cb2-399f88278845)
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/8cd5f3ae-2e44-4744-9b11-a110f6b0b9ef)
Already created for all modules
