### ISSUE TITLE
Web > Institute > My courses > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#674]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/8b32da99-4f3e-4a8b-8fef-ae9b0b50934a)
UI is torned in action buttons. Kindly fix it.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/403608d8-1648-471a-b166-c8af9ccd652e)
Done
