### ISSUE TITLE
Web > Institute > Draft courses > Functional > UI

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#676]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/0211bed9-408b-42f8-a082-181f8f7a1d5a)
In draft courses , after clicking on view detail page of the course , page is completely blank. Kindly fix it.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/e9327710-6d58-45e5-ab57-1d1348bd3e74)
Done
