### ISSUE TITLE
Web > Employer > Post Job > Added a new field

### ISSUE THREAD

**Issue by vinayak-vayuz** [Anupriyabanger/Bee-Recruiter#679]
<img width="884" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0511e891-6416-46de-a8d9-a68dc85700ff">
I've added a new field Mode of Work in post job form. Please change it to type of work and forward this data to the database.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/d3616f17-8b60-4234-9d5c-280ed6150564)
Done
