### ISSUE TITLE
Institute /web/application management /

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#680]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/880f3f26-e29a-4297-9bc0-04bb8110ee4b)
fix this issue.

**Comment by vinayak-vayuz** [comment]
<img width="903" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/9f100e63-22b6-4e76-8406-c669e5d0e8b2">
Done
