### ISSUE TITLE
Web > Institute > Application management >Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#684]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/898ae092-62df-4d5a-8100-979d9932f69c)
In the scholarship section if I am making it yes then other one is automatically changing to no. Kindly check this use case.

**Comment by pankajVayuz** [comment]
not update data in the backend.

**Comment by pankajVayuz** [comment]
@manojnegi07  sir please check this API

**Comment by rajasrivastava101** [comment]
Its resolved now but working very slow , kindly look into this.
