### ISSUE TITLE
Web > Institute > Job posting guidelines > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#695]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/1473be45-0644-4d3d-8612-3cd0b1773065)
Kindly look out on the UI of the job posting guidelines.

**Comment by SaurabhattJi** [comment]
@manojnegi07  sir please check this job guidelines data. It is coming backend in html form.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/5f8a861c-8caf-4671-9ce9-aebcc760e970)
Done

**Comment by rajasrivastava101** [comment]
In the post-course module, it shows job posting guidelines.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/033dfa2f-6932-41c0-883a-86f9770b641a)
Done
Now client will provide the guidelines
