### ISSUE TITLE
Web > Employer > ATS > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#703]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/8586ff0f-2967-44c7-8302-6b4c94ac6d6c)
 Kindly align all the elements in the table properly.

**Comment by vinayak-vayuz** [comment]
<img width="883" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/476860d4-66e1-4204-9762-c7ebbc441c3f">
Done
