### ISSUE TITLE
Institute> Sign up> Add details 

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/Bee-Recruiter#705]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/109590553/e56dc0dc-110b-497e-8d87-1ee176391d40)

**Comment by rajasrivastava101** [comment]
still field is accepting more than 10 digits.

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/68f3b284-bfa9-4246-94e3-17d78d233168)
Check properly it should be 10 digits but its only accpeting till 9.

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/55fd76b7-9934-44c7-9f37-f08a66eaed9c)
The countries which have 3 digit code , then it should accept 11 digits in total but the countries which have 2 digit code then it should accept 10 digits only.
