### ISSUE TITLE
Institute | Aplication | get_all_institute_resume | Api 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#710]
get_all_institute_resume .. not update scholarship status

**Comment by rajasrivastava101** [comment]
@pankajVayuz Kindly check API related pointers , if your requirement is fulfilled then please close the pointer by yourself.

**Comment by rajasrivastava101** [comment]
@pankajVayuz Close this if your requirement is fulfilled.
