### ISSUE TITLE
Web > Employer > Draft jobs > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#714]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/b8e0d264-edac-4e5e-8b89-63191beb8a68)
Not able to add more questions , kindly fix it.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/3c320315-4168-4610-9308-2e0b33bd5120)
Done
