### ISSUE TITLE
Web > Employer > Settings > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#716]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/fd7ce7f8-9ae1-4ad4-b7b0-75a8efbb1ed2)
In edit profile under settings , need to add toaster with successfull update message. Because its not clear that profile is updated or not.

**Comment by technicalbirdVayuz** [comment]
https://github.com/Anupriyabanger/Bee-Recruiter/issues/718

**Comment by rajasrivastava101** [comment]
Toaster is not added here. Kindly add

**Comment by rajasrivastava101** [comment]
kindly look at this once again
