### ISSUE TITLE
Institute | web | Application management | 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#717]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/e6613f25-3549-4e6b-b07d-218eaab3491d)
please fix the  ui  and Sr no space

**Comment by vinayak-vayuz** [comment]
<img width="884" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/edc1727e-09c9-4f28-a583-beaf6532a649">
Done
