### ISSUE TITLE
Web > Institute > Post Course > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#725]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/b9851ba2-3306-4e2c-b754-12f4cc7839df)
Fix no image screen , looks ugly.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/dbc6486f-2d3a-4f7f-a7a5-23e66a57310c)
Done
