### ISSUE TITLE
Web > Institute > My Courses / Draft Course > Course Detail

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#726]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/175bb0cc-a329-4308-a027-9e6abfc7e495)
The image which we are uploading while posting course , should also reflect in view course detail page.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/31617cce-c3c0-4cf6-896f-0dc32412ea0c)
Done

**Comment by rajasrivastava101** [comment]
Kindly make it as a banner image in the detail page.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/b933806c-72de-45bd-927e-53c717e4f570)
Done

**Comment by vinayak-vayuz** [comment]
<img width="836" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/275e9e2e-9bef-42ea-8cab-7d11b6c080e3">
Done
