### ISSUE TITLE
Web > Institute > Application Management

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#727]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/b86927d3-b6c4-466d-af3c-ce9ac462270e)
Dropdown is hidden.

**Comment by vinayak-vayuz** [comment]
<img width="883" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f762eb84-c242-4f03-862e-499d40f77629">
Done
