### ISSUE TITLE
Web > Institute > My calendar > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#729]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/f1a9fb5c-5f5e-4884-900c-099d6b880a66)
Kindly make it a screening schedule.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/8347b3a8-7f8d-4b65-8508-c722bd9e2b81)
Done
