### ISSUE TITLE
Web > Institute > My calendar > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#730]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/c44f33e5-dbe1-48df-8014-9216852b2691)
This should be clickable and redirected to the detail page in calendar view.

**Comment by SaurabhattJi** [comment]
![Uploading image.png…]()
Done

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/7baefa19-df9e-40e4-a186-db150838a13e)
