### ISSUE TITLE
Web > Institute > Draft Courses > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#731]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/0a82cdc8-6b8c-485b-bd4f-0d58087a123f)
 Need to fix the banner image.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/7cd7ccdd-d079-41fc-8d7c-e722008250c4)
Done
