### ISSUE TITLE
institute | social media | signup

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#751]

**Comment by rajasrivastava101** [comment]
kindly recheck once , its not working.

**Comment by rajasrivastava101** [comment]
Kindly check its not working.

**Comment by pankajVayuz** [comment]
google and facebook signup is working please check it

**Comment by rajasrivastava101** [comment]
kindly don't tag it in the review required till the time its not completely resolved.

**Comment by pankajVayuz** [comment]
i create a new issue so i close this issue
