### ISSUE TITLE
web > Institute > profile >

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#759]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/b9af99e7-efae-4492-bf55-b00c09db7074)
Fix this profile page

**Comment by vinayak-vayuz** [comment]
<img width="847" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/abcc016e-6f39-41e3-af70-e0f3836d1453">
Done
