### ISSUE TITLE
Web > Institute > Dashboard > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#760]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/4baec5c1-1997-4394-8327-fd9ba405c36e)
Kindly align the numeric data in the card in a straight line.

**Comment by vinayak-vayuz** [comment]
<img width="214" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/f0cb670c-5f37-4248-84f6-7ded51e871a6">
Done
