### ISSUE TITLE
institute | upload image | Ui 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#764]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/af8a3ecf-ca29-4870-baad-46ad61aea192)
fix the upload image ui

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/5275faba-86a9-406a-9dfc-e4eca94e9c41)

**Comment by vinayak-vayuz** [comment]
<img width="229" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/4219d850-c8f8-4aed-bd80-4c82ed16f37c">
Done

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/88286819-eaf7-4efe-8f0d-46a9978f47dc)
Fix this UI

**Comment by vinayak-vayuz** [comment]
<img width="495" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/ae04d8c4-b257-43ca-a256-e620806b1536">
Done, made the buttons sticky
