### ISSUE TITLE
institute | web | application management| 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#765]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/0f04d45c-bd3f-41a5-898d-2ed1ce0be201)
Search bar overlap. please fix it

**Comment by vinayak-vayuz** [comment]
<img width="204" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/002ac192-383a-4c96-8caa-6d0f913be5fb">
Done
