### ISSUE TITLE
Inastitute | application management | action | aplication view 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#766]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/95750969-3bd9-464e-afa3-9350199d8627)
fix this screen

**Comment by vinayak-vayuz** [comment]
<img width="928" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/d4c57c01-a1b3-4697-8137-146c049d0b96">
Done
