### ISSUE TITLE
Web > Navbar > language

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#767]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/8af0ab09-a6b7-408b-a4c9-b75e3f4d8d9f)

add a dropdown on language preferences

**Comment by vinayak-vayuz** [comment]
Adding a dropdown to change language in all the Navbars of Employer, JobSeeker, Institute, CourseSeeker

**Comment by vinayak-vayuz** [comment]
<img width="339" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/6e1dd5f3-403e-421b-b6d6-e0b444fae9fa">
Fixed it for all module
