### ISSUE TITLE
Institute/Click Cousres,Program/ Click on post Course,please check uploading logo 

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#771]

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/8ba98537-f2cf-4d1e-bf5b-1e22a1dc6458)
Sir actually this field for banner image. 
First user have to select the banner image after selecting the banner image user will crop the image accordingly than click on save changes the banner image will shown on the page.
