### ISSUE TITLE
Institute/Post course/ Add English Exam Type/Attached reference

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#779]
<img width="960" alt="2023-08-08" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/4a100b4e-81dc-43c2-adb5-2687a5850a54">

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/8057b93a-b01c-490d-a5c3-1f0754bd0a8c)
Done from frontend remaining work from backend

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/9e517e74-05cc-4640-bbc0-2ff78fda5aec)
Done remaining work from backend
