### ISSUE TITLE
Institute/Post course/Please correct attached reference (111)

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#780]
<img width="960" alt="2023-08-08 (2)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/d43a8716-ab83-4ee8-b7af-a8b42090f06f">

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/192e0437-38ec-4bb0-a49e-c9b756ac8826)
Done
