### ISSUE TITLE
Employer/Create Company Profile/Add image/ Please make space between close and save(attached)

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#782]
<img width="960" alt="2023-08-08 (3)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/f486d452-691b-4937-83db-9522f266f522">

**Comment by vinayak-vayuz** [comment]
Done
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/a35e2c5e-d950-4373-9447-c09d20b83971">
