### ISSUE TITLE
Employer/Edit profile/ Please differentiate between personal information and company information

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#784]

**Comment by vinayak-vayuz** [comment]
I have made the changes.
<img width="915" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/ac198ded-015c-410a-b82b-073585fa00cc">

**Comment by vinayak-vayuz** [comment]
<img width="681" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/444350ee-bb01-4d15-a9d8-c82fb9f71477">
Done
