### ISSUE TITLE
Employer/Edit profile/ Correct country code (attached picture)

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#785]
<img width="960" alt="2023-08-08 (5)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/8cd14702-c491-45dc-8c62-c284755ce306">

**Comment by pankajVayuz** [comment]
Vinayak remove the white background .

**Comment by vinayak-vayuz** [comment]
<img width="933" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/8ce32d53-8416-4f05-9ce8-fe0bd2d719aa">
Done
