### ISSUE TITLE
Employer/Institute/Candidate/Consultant/ Please let us know what will be in the blank  (attached picture)

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#787]
![Inked2023-08-08 (7)](https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/4996ef15-2416-496d-a05c-afa518cf189e)

**Comment by vinayak-vayuz** [comment]
It will be blank. @Jamalatm

**Comment by vinayak-vayuz** [comment]
In future we can place ADs here. @Jamalatm

**Comment by vinayak-vayuz** [comment]
<img width="958" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/00d6186a-8d15-48b8-9da6-f1feb4e14fe3">
@Jamalatm Done
