### ISSUE TITLE
Employer/After click on post job the system should ask me to update profile and logo FIRST

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#790]

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/2ef7f7c9-eb1e-4ccb-abc9-fbfec8fcb6ea)
Sir It's already there. 
If a new user sign in / sign up and without creating a company user can't post a job. So before posting a job user should create company first.
