### ISSUE TITLE
Employer/ Dashbord comes blue like Logo

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#793]
Attached for reference
<img width="960" alt="2023-08-11 (1)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/f397be60-070c-467f-8f76-774b516b52c7">

**Comment by SaurabhattJi** [comment]
@rajasrivastava101 Not able to understand this pointer please discuss with @Jamalatm
