### ISSUE TITLE
Employer/Dashbord

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#795]

**Comment by Jamalatm** [comment]
Add CANDIDATES ON HOLD /AND+/Add CANDIDATES HIRED/ Add CANDIDATES REJECTED/+/ Add CANDIDATES OFFERED

**Comment by pankajVayuz** [comment]
The Hold candidates are being shown in the total Hold Candidates card.
The Hired candidates are shown in the total selected Candidates' cards.
The rejected candidates are shown in the total rejected Candidates' card.
The offered candidates are shown in the total Shortlisted Candidates card.

**Comment by rajasrivastava101** [comment]
@pankajVayuz Change the name as follows on the dashboard
The Hired candidates are shown in the total selected Candidates' cards.
The rejected candidates are shown in the total rejected Candidates' card.
The offered candidates are shown in the total Shortlisted Candidates card.
