### ISSUE TITLE
Institute | web | create new password | 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#796]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/e6bf3ee4-f8be-431a-bca1-0ba321d8c3fe)
please fix the input box

**Comment by vinayak-vayuz** [comment]
<img width="835" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/abdb239b-b598-4136-906c-8c9c2d6e5a23">

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/76a5990e-f111-49d0-ac0c-789a5c3e8623)
Fix it.

**Comment by vinayak-vayuz** [comment]
<img width="813" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/08678cf2-4119-4bf3-b81c-7800135f7a96">
Done
