### ISSUE TITLE
App > Employer > Sign up > Functional > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#800]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/7a7e10a7-377c-449a-bd29-214c8050b132)
Sign up process is incomplete as per figma. Fields are missing kindly check.

**Comment by gauravk-Vayuz** [comment]
![photo_2023-10-18_18-20-56](https://github.com/Anupriyabanger/Bee-Recruiter/assets/127388748/43997240-28e7-4a50-ab14-213d521400ec)
