### ISSUE TITLE
App > Employer > Sign up > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#801]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/2c18640b-d5b2-4865-a9ae-bf528f5426ce)
Make it email rather than personal email id.

**Comment by gauravk-Vayuz** [comment]
![Uploading photo_2023-10-18_18-20-56.jpg…]()
