### ISSUE TITLE
App > Employer > Sign up > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#802]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/1f6eb99e-312d-48ff-9da6-41848d69fb3d)
Social sign up is not working , kindly make it functional,

**Comment by milivayuz** [comment]
Still not working

**Comment by aman-vayuz** [comment]
If one id is connected with institute and you try to sign up for employer profile , i'tt won't work. 
So use one id for 1 log in , in google  sign up
