### ISSUE TITLE
Web > Jobseeker > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#812]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/4b6f6166-a153-4225-8b87-aacfb66bcc9d)
Why these to search panel is required at a same page, if the header one is working then we should remove the body filter.

**Comment by rgnarok** [comment]
<img width="876" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/85341053/6f87d428-dfc6-4144-9c3f-6e559033da1a">

Not fixed

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/2e744994-81b8-43b9-ab72-9d1ffad03f76)
This search panel for job feed in the above navbar search panel we are showing all jobs available in the job seeker module. But if user wants to search jobs only in job feed section then user can search the job from this search panel
