### ISSUE TITLE
Web > Institute > post course > functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#813]
We are keeping the meeting url at student end but it is not mentioned on institute post course page so kindly add it.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/195a8ee9-6136-44a4-a896-e3dfc4d8065d)
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/e78e0e93-2427-4842-88f5-9cb7e349ecdf)
Done
