### ISSUE TITLE
Add star over popup for rating and remove select rating from right panel only show Average rating at right side

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#817]
![Screenshot from 2023-08-31 17-36-12](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/a0eb2a2f-b2ea-485c-b121-e5957a12e29f)

**Comment by vinayak-vayuz** [comment]
<img width="516" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/629b0136-e61f-41c8-9903-20901d5fb1f9">
Done
