### ISSUE TITLE
Issue while uploading pdf

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#818]
![Screenshot from 2023-08-31 18-26-56](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/5149195a-467f-43e0-b44c-8a86d8d98bfc)

**Comment by rgnarok** [comment]
@MaroofTech  close this is done

**Comment by MaroofTech** [comment]
@pankajVayuz please check
