### ISSUE TITLE
Profile >> Add video resume not working,also add loader in button

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#820]

**Comment by rgnarok** [comment]
<img width="1440" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/85341053/6f19c6b0-68be-4b8f-a493-d90e9d5a21b9">

Not fixed i am not able to access the page

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/c0f58448-2ee5-4aae-a666-640d3ed9a5a4)
Done
