### ISSUE TITLE
Profile >>  I can add empty professional details and no state management while add/edit details

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#821]

**Comment by MaroofTech** [comment]
@pankajVayuz After editing the first professional details it's coming in last and can update end date, also in case of edit its adding

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/df4a67cc-0d36-4e97-b32d-244d606377a7)
Done
