### ISSUE TITLE
Web > Jobseeker > Sign Up > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#847]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/3417ffbe-5467-42a7-911d-913a6c1377f1)
Kindly align the fields as per Figma, Make the email id above the contact number.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/6cb07b81-6a20-492a-86cc-421e725a1535">
Done
