### ISSUE TITLE
Institute > Course Detail 

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#851]
Show the updated data in course detail page

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/d6b32925-e33f-4612-970a-733a59a23f0e)
Data is there but the icons are same.

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/7206ac8d-ba29-4136-94a0-e2e64d34f7bc)
Icons and field alignment should be there.

**Comment by vinayak-vayuz** [comment]
<img width="877" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0360fd8a-67de-478a-a427-598bc07dd1f3">
Done
