### ISSUE TITLE
my resume 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#864]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/c342e146-1081-47e1-9d45-3d2799361a41)

fix this ui

**Comment by vinayak-vayuz** [comment]
As discussed It's showing on two pages: 
<img width="763" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/e95ea4c3-498e-4003-b7d7-14d1580d3209">
