### ISSUE TITLE
Web > Jobseeker > Sign up > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#865]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/0797121a-30ec-4b46-a4d6-28f432126d08)
Shadow is displayed in contact field.

**Comment by vinayak-vayuz** [comment]
I need additional time as this is a third party package that need more time.

**Comment by vinayak-vayuz** [comment]
<img width="298" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/81d75638-b27c-4d86-90a7-b2df17b0ce51">
Done
