### ISSUE TITLE
Web > Jobseeker > Apply jobs > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#867]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/0ddece15-325a-4b60-accf-2b3a864c9b09)
Without filling anything ,apply button is visible.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/c07d9d3f-68e1-453e-b65f-90c4a537f9db)
