### ISSUE TITLE
Web > Jobseeker > Job detail > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#870]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/f7d055d2-44da-4e17-a0ed-14ceec3fbe33)
In job detail page , 'jobs from top companies' are static.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/c8b1ea4b-9e3e-41c1-8203-e266ae918799)
Done
