### ISSUE TITLE
Web > Jobseeker > General > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#874]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/98dd1b72-9294-4a64-a3aa-e708c8bcf53f)
In dark mode, UI is torned.

**Comment by vinayak-vayuz** [comment]
<img width="487" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/244efa78-ce9a-47e6-ae60-0a28025c6cc8">
Done
