### ISSUE TITLE
Web >Jobseeker > Homepage > Apply jobs > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#890]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/646f2483-19a8-4d7e-a11f-e8459ca5d879)
Improve the UI for withdrawing the application.

**Comment by vinayak-vayuz** [comment]
<img width="588" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/5550f985-9aa1-4b19-b89e-ee4a7d478c1c">
Done

**Comment by vinayak-vayuz** [comment]
@SaurabhattJi Please review its functions
