### ISSUE TITLE
Web > Jobseeker > Profile 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#891]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/eaa504b8-59a9-4660-8346-10c9adb7e14f)
While selecting a month , the full page is scrollable.

**Comment by vinayak-vayuz** [comment]
<img width="628" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/7353d151-d60c-473d-bb0f-cfc9410e0675">
