### ISSUE TITLE
Web > Jobseeker > Profile > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#905]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/911f6a4e-ec79-4fa7-b1c8-fadb477ad086)
Fix the UI of cropping image.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/95a7e9a7-ae22-484c-9cb3-a50fb1d4748a)
Buttons has been fixed
