### ISSUE TITLE
Web > Course Seeker > Homepage

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#906]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/e2cb761c-c41e-4ae1-9f13-f88964bcaab6)
After clicking on report page is refreshing and not able to report a course

**Comment by MaroofTech** [comment]
Toast is not coming after reporting

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/f382ed12-3c7b-46cd-a474-b3066817b3f2)
Done

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/2897817f-9bd3-4ec7-8867-7bf38a06fc79)
