### ISSUE TITLE
Web > Course Seeker > Homepage

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#908]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/faab23f5-18f4-4022-a584-c488fab3a9b1)
Add a new button to remove the current filters.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/73a5ccdb-9cd1-430f-a5e5-9bd7ce34a8d7)
Done

**Comment by MaroofTech** [comment]
![Screenshot from 2023-09-26 13-16-28](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/d293590a-cbe3-455a-aade-7be656c440eb)
