### ISSUE TITLE
web > course seeker > course detail

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#911]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/4ad30199-e326-4d88-814b-7aad8b7045a4)
The text under the card is not visible on dark mode

**Comment by vinayak-vayuz** [comment]
<img width="325" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/7bedd1e9-dc6e-4438-8a23-edeafd8d69dd">
Done
