### ISSUE TITLE
Web > Jobseeker > Profile > Ui 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#917]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/b07da662-d49a-4f70-9c9a-51583cb2581b)
On dark mode video, Background is white.

**Comment by vinayak-vayuz** [comment]
<img width="284" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/58e9f0d3-3dc6-4ae4-9186-b0e3c43e4ded">
