### ISSUE TITLE
Web > Jobseeker >Profile > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#921]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/9006237d-8c17-4709-8953-7ea1f30969b7)
On dark mode, the add icon is not visible.

**Comment by vinayak-vayuz** [comment]
![Uploading image.png…]()
Done

**Comment by vinayak-vayuz** [comment]
<img width="113" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/6d7285ef-29e5-4ada-b861-0e7a57bac3d6">
Done
