### ISSUE TITLE
job seeker | my resume | 

### ISSUE THREAD

**Issue by pankajVayuz** [Anupriyabanger/Bee-Recruiter#926]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/7b22dffa-c4f4-4f44-b202-be1d0d43c2f8)
when we print the resume. font size is very small.

**Comment by vinayak-vayuz** [comment]
<img width="328" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/cf39c318-55ed-4467-9f8d-15b501aaa398">
Done
