### ISSUE TITLE
Please work on the margins

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#927]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/b4c2b1fa-adee-424e-be19-3a2ab1301506)

**Comment by vinayak-vayuz** [comment]
<img width="946" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/62a04570-e3bc-487f-a60f-be18230c7e8c">
Now looking better
