### ISSUE TITLE
The dot in here is wrong you have to use one with no border just with fill

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#928]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/55a9fbb1-1184-4ef7-8563-199a13292afa)

**Comment by vinayak-vayuz** [comment]
<img width="953" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/3b3628f5-d1f4-4e07-9ec7-126f6476dfb6">
Done
