### ISSUE TITLE
Put a dot after Top companies as well

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#929]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/cd0ba929-237a-44d1-ad93-e4e89f29d9b3)

**Comment by vinayak-vayuz** [comment]
<img width="953" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/cbada066-08c0-4d71-af21-b4db3127abe6">
Done
