### ISSUE TITLE
The save button is not working in job feed( not getting saved or unsavd0

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#930]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/ada38f42-d990-42b0-a564-cbb8ca0e142e)

**Comment by MaroofTech** [comment]
![Screenshot from 2023-09-26 13-15-04](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/3c8f5768-3774-4c75-96f2-1514354d6179)
