### ISSUE TITLE
Change the filled save icon

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#932]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/f0f9dd87-4172-4ac7-96a0-76d9fe4dcdf4)

**Comment by vinayak-vayuz** [comment]
![Uploading image.png…]()
Done

**Comment by vinayak-vayuz** [comment]
<img width="95" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/e5aaa76d-14b6-478c-ae40-5bcc0739cb3e">
Done

**Comment by vinayak-vayuz** [comment]
<img width="285" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/bcba8d0a-19b4-4af1-80e9-a42f6ea38cd8">
Done
