### ISSUE TITLE
increase the size of 3 dots by 2-3 pixels

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#933]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/da5b3628-41c8-45c0-a9a8-24bf71025266)

**Comment by vinayak-vayuz** [comment]
<img width="246" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0f71f260-ee16-4d19-bafb-36b796c4b798">
Done
