### ISSUE TITLE
Add borders on every job container or fill it

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#934]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/7acb55ea-3eeb-415b-a943-9527208fff42)

**Comment by vinayak-vayuz** [comment]
<img width="946" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/58758013-e962-4fd3-acde-8139b02136a0">
Bg color has been added.
