### ISSUE TITLE
As you can see in the screenshot there is line coming over the button once it had been hovered on

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#935]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/636ce6cd-9f9a-48a3-9b5b-5d1e9e0cfc2d)

**Comment by vinayak-vayuz** [comment]
Can't find the button, please mention where @naveesha-vayuz

**Comment by vinayak-vayuz** [comment]
<img width="166" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/b42430f9-463d-49e2-b31f-48b44f1df052">
Fixed
