### ISSUE TITLE
Increase the border radius in such a way that its in pill shape

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#936]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/f96bbed4-bf5c-44cb-8ccf-a483144a8fa3)

**Comment by vinayak-vayuz** [comment]
<img width="948" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/8916dbd5-49b1-46d9-a2ce-cdec4a36f41c">
Done
