### ISSUE TITLE
Please work upon this black box coming over phone number

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#937]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/3f8cd329-2d1a-4907-9689-11bd84bb0222)

**Comment by vinayak-vayuz** [comment]
<img width="472" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/5fac91e1-7ed5-4dcb-81cd-496e2d9ffd62">
Done
