### ISSUE TITLE
Inc. the space in between fields once like this

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#938]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/7cd201eb-6cf8-44fd-8a1b-e124caa27a80)

**Comment by vinayak-vayuz** [comment]
<img width="471" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/1187b2ce-5022-4ee9-a7e5-268afddb7b37">
Done
