### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#939]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/2a7cf547-f690-4e2a-8ab5-316653489288)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/27b5da25-8635-4f53-8df8-9051066ca3ca)
Check
