### ISSUE TITLE
Also the user should have the option to upload resume by clicking on upload button as well

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#940]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/4e6312cb-2f86-402b-a0eb-1d88652855b4)

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/79c5176b-c4ed-432a-87fd-b65be866f323)
Done
