### ISSUE TITLE
Please differentiate the color of upload text from normal text as it is a text button.

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#941]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/66588cc4-0513-479e-8805-e1c56e5ca464)

**Comment by vinayak-vayuz** [comment]
<img width="463" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/968ba7ca-1386-4def-bbc9-f3c9089a4631">
Done
