### ISSUE TITLE
not able to click on the check box

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#943]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/1848cdcc-cb16-462f-bc87-3d887ec848cb)

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/8c7800fc-036e-4006-b7fb-ed56495b0409)
Done
