### ISSUE TITLE
Increase the size of the filter its should be balancing the text on the left side

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#945]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/162f7efa-a386-45a7-8291-473a298f36a0)

**Comment by vinayak-vayuz** [comment]
<img width="943" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/d86bfaaf-2553-4619-acea-ec32476a53dd">
Done
