### ISSUE TITLE
Change the color of the dropdown of filter to white

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#946]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/a1caa213-38f9-41e5-8eb1-e1062f6cf30f)

**Comment by vinayak-vayuz** [comment]
<img width="202" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/90548cdf-1adc-41dd-aba4-6b39c973d7d6">
Done
