### ISSUE TITLE
Keep all the first letters capital

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#947]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/8c10cd17-2469-480d-8a14-485c17f4c3e6)

**Comment by vinayak-vayuz** [comment]
<img width="235" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/81c5ac1c-2748-4a41-bb13-94926306ce97">
Done
