### ISSUE TITLE
Keep the thickness of icons similar

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#948]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/2c3c864f-6423-498d-adb3-5e12a1a4ddb8)

**Comment by vinayak-vayuz** [comment]
<img width="319" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/7d50dc73-871e-4ec4-bf36-7187e240f2cd">
Added thickness in search icon

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/62ec7377-de2e-4a1f-ac5e-f8b567ea6fe3)
Done
