### ISSUE TITLE
Change the font of jobs

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#949]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/60218e6f-0722-4ff6-a008-57463b503553)

**Comment by vinayak-vayuz** [comment]
<img width="280" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/48867d69-d2fe-4ec9-95bd-636a092daab6">
Done

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/1f2d50f2-65e8-4f29-a9b6-6c93df2935b2)
Done
