### ISSUE TITLE
Maintain the space on the left and right of the header

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#950]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/84806430-f4c5-4516-a818-19c9eb3a7f32)

**Comment by vinayak-vayuz** [comment]
<img width="943" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/eea57f78-37f2-403d-a8bd-6241aeddfee8">
Done

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/b82ab171-f5ed-435b-9178-b1fa7fae21ba)
