### ISSUE TITLE
Web > Course seeker > Homepage > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#953]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/bf2368ff-5339-462f-abe7-944a6a5c5908)
The apply button is not functional.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/7fb39fe4-5864-4e27-831a-09888c5269f7)
Done

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/25c8e459-974e-427a-b7dc-fc0c4a14ec4e)
Done
