### ISSUE TITLE
Web > Course seeker > My calendar > UI > Dark mode 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/Bee-Recruiter#955]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/1bcd7816-e16e-4dcb-a901-efea0cdc4de5)
UI is torned, white background is displayed.

**Comment by vinayak-vayuz** [comment]
<img width="894" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0e6f23ef-581b-4f99-8146-338fe52e25c8">
Done
