### ISSUE TITLE
Fix advertisement UI

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#968]

**Comment by vinayak-vayuz** [comment]
<img width="265" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/8ececb21-c9d2-4615-84b6-2ad7a601a7ff">
Done

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/14889255-5860-44bf-a57c-fe95799c72bf)
Done
