### ISSUE TITLE
Web > Homepage > Share jobs

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#988]
In job details , add meta-tag, add meta description and image to share a job.

**Comment by pankajVayuz** [comment]
when we share the link meta tag title and description show. but the image does not show properly.
@MaroofTech  sir, please fix this issue.

**Comment by PrakVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/158542726/af66049e-cacc-44a6-bdd3-d251f63e44cf)
