### ISSUE TITLE
Web > homepage > report job

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#990]
report ,fix white space from the pop-up.

**Comment by vinayak-vayuz** [comment]
<img width="494" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/614ff606-c2b9-48de-a6da-ed49f8ca8165">
Done

**Comment by vinayak-vayuz** [comment]
<img width="495" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/0e11ae68-123f-48a5-adab-4db35f9b34ee">
Done
