### ISSUE TITLE
Web > Job seeker > Apply job

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#992]
Apply Job - After closing the pop-up of apply job show a pop-up ex-are you sure and after closing the pop-up the details are empty.

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/dd5c0ff7-396c-4f25-9ec3-4006448b14e7">
Done
