### ISSUE TITLE
Web > Job Seeker > Job card

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#998]
fix the UI of report button.

**Comment by vinayak-vayuz** [comment]
<img width="230" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/83337c5f-9b7e-4f28-99d0-b45d29b35003">
Done

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/2f671b83-a9e3-42d0-946a-8d3f3bd4c0d2)
Done
