### ISSUE TITLE
Web > job seeker > job feed 

### ISSUE THREAD

**Issue by SaurabhattJi** [Anupriyabanger/Bee-Recruiter#999]
add filters in job feed section.

**Comment by SaurabhattJi** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/40480617-aa83-4d1f-90e4-37e2638b596d)
Done

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/4cca8b9d-f26f-4899-87ee-ab08b5ba3f3b)
Filters are not clickable
